/* Lógico_mod5: */

CREATE TABLE RESULTADOS (
    RST_COLOCACAO ENUM('1', '2', ',3'),
    RST_ID INT PRIMARY KEY,
    FK_CAMPUS_CMP_ID INT,
    FK_EVENTOS_MODALIDADES_EVM_ID INT
);

CREATE TABLE EVENTOS (
    EVT_ID INT PRIMARY KEY,
    EVT_DATA DATE,
    EVT_NOME VARCHAR(100),
    EVT_LOGO VARCHAR(255)
);

CREATE TABLE ALUNOS (
    ALN_ID INT PRIMARY KEY,
    ALN_NOME VARCHAR(100),
    FK_CAMPUS_CMP_ID INT
);

CREATE TABLE RESPONSAVEL_EQUIPE (
    RSP_ID INT PRIMARY KEY,
    RSP_NOME VARCHAR(100),
    FK_CAMPUS_CMP_ID INT
);

CREATE TABLE ORGANIZADOR_EVENTO (
    ORG_NOME VARCHAR(100),
    ORG_ID INT PRIMARY KEY
);

CREATE TABLE MODALIDADES (
    MDL_NOME VARCHAR(50),
    MDL_ID INT PRIMARY KEY
);

CREATE TABLE CAMPUS (
    CMP_ID INT PRIMARY KEY,
    CMP_NOME VARCHAR(100)
);

CREATE TABLE DENUNCIA (
    DNC_TITULO VARCHAR(100),
    DNC_STATUS ENUM('DEVERIDA','INDEFERIDA','PENDENTE'),
    DNC_DESCRICAO TEXT,
    DNC_DATA DATETIME,
    DNC_ID INT PRIMARY KEY,
    FK_EVENTOS_EVT_ID INT,
    FK_RESPONSAVEL_EQUIPE_RSP_ID INT,
    FK_ORGANIZADOR_EVENTO_ORG_ID INT,
    FK_SECRETARIOS_EVENTO_SCT_ID INT
);

CREATE TABLE FOTOS (
    FTS_ID INT PRIMARY KEY,
    FTS_LEGENDA VARCHAR(200),
    FTS_CAMPUS VARCHAR(100),
    FTS_DATA DATETIME,
    FK_EVENTOS_EVT_ID INT,
    FK_ALUNOS_ALN_ID INT
);

CREATE TABLE EVENTOS_MODALIDADES (
    EVM_ID INT PRIMARY KEY,
    FK_MODALIDADES_MDL_ID INT,
    FK_EVENTOS_EVT_ID INT,
    FK_RESPONSAVEL_EQUIPE_RSP_ID INT
);

CREATE TABLE SECRETARIOS_EVENTO (
    SCT_ID INT PRIMARY KEY,
    SCT_NOME VARCHAR(100)
);

CREATE TABLE FEEDBACK_ALUNO (
    FK_ALUNOS_ALN_ID INT,
    FK_EVENTOS_EVT_ID INT,
    FDB_NOTA_ORGANIZACAO ENUM('0',1','2','3','4','5','N'),
    FDB_NOTA_ARBITRAGEM ENUM('0',1','2','3','4','5','N'),
    FDB_NOTA_SEGURANCA ENUM('0',1','2','3','4','5','N'),
    FDB_NOTA_HIGIENE ENUM('0',1','2','3','4','5','N'),
    FDB_NOTA_LOCOMOCAO ENUM('0',1','2','3','4','5','N'),
    FDB_NOTA_ALIMENTACAO ENUM('0',1','2','3','4','5','N'),
    FDB_NOTA_COMPLEXOS ENUM('0',1','2','3','4','5','N'),
    FDB_NOTA_COMODIDADE ENUM('0',1','2','3','4','5','N'),
    FDB_ID INT PRIMARY KEY
);

CREATE TABLE ALUNOS_SELECIONADOS_MODALIDADES (
    FK_EVENTOS_MODALIDADES_EVM_ID INT,
    FK_ALUNOS_ALN_ID INT,
    ASM_ID INT PRIMARY KEY
);
 
ALTER TABLE RESULTADOS ADD CONSTRAINT FK_RESULTADOS_2
    FOREIGN KEY (FK_CAMPUS_CMP_ID)
    REFERENCES CAMPUS (CMP_ID)
    ON DELETE CASCADE;
 
ALTER TABLE RESULTADOS ADD CONSTRAINT FK_RESULTADOS_3
    FOREIGN KEY (FK_EVENTOS_MODALIDADES_EVM_ID)
    REFERENCES EVENTOS_MODALIDADES (EVM_ID)
    ON DELETE CASCADE;
 
ALTER TABLE ALUNOS ADD CONSTRAINT FK_ALUNOS_2
    FOREIGN KEY (FK_CAMPUS_CMP_ID)
    REFERENCES CAMPUS (CMP_ID)
    ON DELETE CASCADE;
 
ALTER TABLE RESPONSAVEL_EQUIPE ADD CONSTRAINT FK_RESPONSAVEL_EQUIPE_2
    FOREIGN KEY (FK_CAMPUS_CMP_ID)
    REFERENCES CAMPUS (CMP_ID)
    ON DELETE CASCADE;
 
ALTER TABLE DENUNCIA ADD CONSTRAINT FK_DENUNCIA_2
    FOREIGN KEY (FK_EVENTOS_EVT_ID)
    REFERENCES EVENTOS (EVT_ID)
    ON DELETE CASCADE;
 
ALTER TABLE DENUNCIA ADD CONSTRAINT FK_DENUNCIA_3
    FOREIGN KEY (FK_RESPONSAVEL_EQUIPE_RSP_ID)
    REFERENCES RESPONSAVEL_EQUIPE (RSP_ID)
    ON DELETE CASCADE;
 
ALTER TABLE DENUNCIA ADD CONSTRAINT FK_DENUNCIA_4
    FOREIGN KEY (FK_ORGANIZADOR_EVENTO_ORG_ID)
    REFERENCES ORGANIZADOR_EVENTO (ORG_ID)
    ON DELETE SET NULL;
 
ALTER TABLE DENUNCIA ADD CONSTRAINT FK_DENUNCIA_5
    FOREIGN KEY (FK_SECRETARIOS_EVENTO_SCT_ID)
    REFERENCES SECRETARIOS_EVENTO (SCT_ID)
    ON DELETE SET NULL;
 
ALTER TABLE FOTOS ADD CONSTRAINT FK_FOTOS_2
    FOREIGN KEY (FK_EVENTOS_EVT_ID)
    REFERENCES EVENTOS (EVT_ID)
    ON DELETE CASCADE;
 
ALTER TABLE FOTOS ADD CONSTRAINT FK_FOTOS_3
    FOREIGN KEY (FK_ALUNOS_ALN_ID)
    REFERENCES ALUNOS (ALN_ID)
    ON DELETE CASCADE;
 
ALTER TABLE EVENTOS_MODALIDADES ADD CONSTRAINT FK_EVENTOS_MODALIDADES_2
    FOREIGN KEY (FK_MODALIDADES_MDL_ID)
    REFERENCES MODALIDADES (MDL_ID)
    ON DELETE CASCADE;
 
ALTER TABLE EVENTOS_MODALIDADES ADD CONSTRAINT FK_EVENTOS_MODALIDADES_3
    FOREIGN KEY (FK_EVENTOS_EVT_ID)
    REFERENCES EVENTOS (EVT_ID)
    ON DELETE CASCADE;
 
ALTER TABLE EVENTOS_MODALIDADES ADD CONSTRAINT FK_EVENTOS_MODALIDADES_4
    FOREIGN KEY (FK_RESPONSAVEL_EQUIPE_RSP_ID)
    REFERENCES RESPONSAVEL_EQUIPE (RSP_ID)
    ON DELETE CASCADE;
 
ALTER TABLE FEEDBACK_ALUNO ADD CONSTRAINT FK_FEEDBACK_ALUNO_2
    FOREIGN KEY (FK_ALUNOS_ALN_ID)
    REFERENCES ALUNOS (ALN_ID)
    ON DELETE SET NULL;
 
ALTER TABLE FEEDBACK_ALUNO ADD CONSTRAINT FK_FEEDBACK_ALUNO_3
    FOREIGN KEY (FK_EVENTOS_EVT_ID)
    REFERENCES EVENTOS (EVT_ID)
    ON DELETE SET NULL;
 
ALTER TABLE ALUNOS_SELECIONADOS_MODALIDADES ADD CONSTRAINT FK_ALUNOS_SELECIONADOS_MODALIDADES_2
    FOREIGN KEY (FK_EVENTOS_MODALIDADES_EVM_ID)
    REFERENCES EVENTOS_MODALIDADES (EVM_ID)
    ON DELETE SET NULL;
 
ALTER TABLE ALUNOS_SELECIONADOS_MODALIDADES ADD CONSTRAINT FK_ALUNOS_SELECIONADOS_MODALIDADES_3
    FOREIGN KEY (FK_ALUNOS_ALN_ID)
    REFERENCES ALUNOS (ALN_ID)
    ON DELETE SET NULL;