CREATE DATABASE IF NOT EXISTS MODULO1;
USE MODULO1;

CREATE TABLE  NUTRICIONISTAS (
NUT_CRN VARCHAR(10) NOT NULL,
NUT_FOCO INTEGER NOT NULL,
NUT_DESC_PROFISSIONAL VARCHAR(500),
NUT_STATUS INTEGER NOT NULL,
USU_CODIGO INTEGER NOT NULL PRIMARY KEY
);

CREATE TABLE PESOS_ALTURAS (
PEA_ALTURA DECIMAL(5,2) NOT NULL,
PEA_PESO DECIMAL(5,2) NOT NULL,
PEA_DATA_HORA_CADASTRO DATETIME NOT NULL,
PEA_CODIGO INTEGER AUTO_INCREMENT NOT NULL PRIMARY KEY,
USU_CODIGO INTEGER
);

CREATE TABLE FALE_CONOSCO (
FAL_TITULO VARCHAR(50) NOT NULL,
FAL_NOME VARCHAR(100) NOT NULL,
FAL_TIPO_MENSAGEM INTEGER NOT NULL,
FAL_MENSAGEM VARCHAR(500) NOT NULL,
FAL_EMAIL VARCHAR(255) NOT NULL,
FAL_CODIGO INTEGER AUTO_INCREMENT NOT NULL PRIMARY KEY,
USU_CODIGO INTEGER
);

CREATE TABLE PATOLOGIAS_MEDICACOES (
PAT_NOME VARCHAR(100) NOT NULL,
PAT_MED_NOME VARCHAR(100) NOT NULL,
PAT_DATA_INICIO DATE NOT NULL,
PAT_DATA_FIM DATE NOT NULL,
PAT_CODIGO INTEGER AUTO_INCREMENT NOT NULL PRIMARY KEY,
USU_CODIGO INTEGER
);

CREATE TABLE ADMINISTRADORES (
ADM_NOME VARCHAR(100) NOT NULL,
ADM_SENHA VARCHAR(50) NOT NULL,
ADM_ROOT INTEGER NOT NULL,
ADM_EMAIL VARCHAR(255) NOT NULL,
ADM_CODIGO INTEGER AUTO_INCREMENT NOT NULL PRIMARY KEY
);

CREATE TABLE USUARIOS (
USU_CPF VARCHAR(14) NOT NULL UNIQUE,
USU_ENDERECO VARCHAR(100),
USU_DATA_CADASTRO_ADM DATE NOT NULL,
USU_GENERO INTEGER,
USU_DATA_NASCIMENTO DATE NOT NULL,
USU_TELEFONE VARCHAR(20),
USU_AVISOS INTEGER,
USU_NOME VARCHAR(100) NOT NULL,
USU_FOTO VARCHAR(100),
USU_SENHA VARCHAR(50) NOT NULL,
USU_EMAIL VARCHAR(255) NOT NULL,
USU_TIPO INTEGER NOT NULL,
USU_CODIGO INTEGER AUTO_INCREMENT NOT NULL PRIMARY KEY
);

CREATE TABLE EDUCADORES_FISICO (
EDF_CREF VARCHAR(12) NOT NULL,
EDF_FOCO INTEGER NOT NULL,
EDF_DESC_PROFISSIONAL VARCHAR(500),
EDF_STATUS INTEGER NOT NULL,
USU_CODIGO INTEGER NOT NULL PRIMARY KEY,
FOREIGN KEY(USU_CODIGO) REFERENCES USUARIOS (USU_CODIGO)
);

ALTER TABLE  NUTRICIONISTAS ADD FOREIGN KEY(USU_CODIGO) REFERENCES USUARIOS (USU_CODIGO);
ALTER TABLE PESOS_ALTURAS ADD FOREIGN KEY(USU_CODIGO) REFERENCES USUARIOS (USU_CODIGO);
ALTER TABLE FALE_CONOSCO ADD FOREIGN KEY(USU_CODIGO) REFERENCES USUARIOS (USU_CODIGO);
ALTER TABLE PATOLOGIAS_MEDICACOES ADD FOREIGN KEY(USU_CODIGO) REFERENCES USUARIOS (USU_CODIGO);
