/* modulo 6 - logicoVERSAOFINAL: */

CREATE DATABASE IF NOT EXISTS MODULO6;
USE MODULO6;

CREATE TABLE USUARIOS (
    USU_NOME VARCHAR(100) NOT NULL,
    USU_EMAIL VARCHAR(100) UNIQUE,
    USU_RECEBER_LEMBRETES BOOLEAN NOT NULL,
    USU_CPF INTEGER UNIQUE PRIMARY KEY
);

CREATE TABLE EDUCADORES_FISICOS (
    EDU_NOME VARCHAR(80) NOT NULL,
    EDU_EMAIL VARCHAR(80) UNIQUE,
    EDU_CREF INTEGER UNIQUE PRIMARY KEY
);

CREATE TABLE TESTES_PSICOLOGICOS (
    TPS_CODIGO INTEGER AUTO_INCREMENT PRIMARY KEY,
    TPS_RESULTADO VARCHAR(20) NOT NULL,
    TPS_DATA DATE,
    TPS_PONTUACAO INTEGER,
    FK_USUARIOS_USU_CPF INTEGER
);

CREATE TABLE PERGUNTAS_TESTE_PSICOLOGICO (
    PTP_CODIGO INTEGER AUTO_INCREMENT PRIMARY KEY,
    PTP_PERGUNTA VARCHAR(100)
);

CREATE TABLE EXERCICIOS_FISICOS (
    EXF_CODIGO INTEGER AUTO_INCREMENT PRIMARY KEY,
    EXF_DESCRICAO VARCHAR(100),
    EXF_COMO_EXECUTAR_GIF VARCHAR(100),
    EXF_DEMONSTRACAO_YOUTUBE VARCHAR(100),
    EXF_NOME VARCHAR(80) NOT NULL,
    FK_TIPOS_EXECICIOS_FISICOS_TEF_CODIGO INTEGER,
    FK_UNIDADES_DE_MEDIDAS_UNM_CODIGO INTEGER
);

CREATE TABLE GUIAS_DE_SUPLEMENTACAO (
    GSP_CODIGO INTEGER AUTO_INCREMENT PRIMARY KEY,
    GSP_NOME VARCHAR(100) NOT NULL,
    GSP_DESCRICAO VARCHAR(100),
    GSP_ACAO VARCHAR(100),
    GSP_DOSE VARCHAR(100),
    GSP_PERIODO VARCHAR(100),
    GSP_COMPOSICAO VARCHAR(100)
);

CREATE TABLE PROGRAMAS_DE_TREINAMENTO (
    PGT_CODIGO INTEGER AUTO_INCREMENT PRIMARY KEY,
    PGT_NOME VARCHAR(80) NOT NULL,
    PGT_DIFICULDADE VARCHAR(80)
);

CREATE TABLE UNIDADES_DE_MEDIDAS (
    UNM_CODIGO INTEGER AUTO_INCREMENT PRIMARY KEY,
    UNM_NOME VARCHAR(80) NOT NULL,
    UNM_ABREVIACAO VARCHAR(20)
);

CREATE TABLE TIPOS_EXECICIOS_FISICOS (
    TEF_CODIGO INTEGER AUTO_INCREMENT PRIMARY KEY,
    TEF_NOME VARCHAR(80)
);

CREATE TABLE GRUPOS_MUSCULARES (
    GMC_CODIGO INTEGER AUTO_INCREMENT PRIMARY KEY,
    GMC_NOME VARCHAR(80) NOT NULL
);

CREATE TABLE RESPOSTAS_TESTE_PERGUNTAS (
    FK_PERGUNTAS_TESTE_PSICOLOGICO_PTP_CODIGO INTEGER,
    FK_TESTES_PSICOLOGICOS_TPS_CODIGO INTEGER,
    RTP_RESPOSTA INTEGER NOT NULL,
    RTP_CODIGO INTEGER AUTO_INCREMENT PRIMARY KEY
);

CREATE TABLE USUARIOS_EXERCICIOS_FISICOS (
    FK_USUARIOS_USU_CPF INTEGER,
    FK_EXERCICIOS_FISICOS_EXF_CODIGO INTEGER,
    USU_GEF_CODIGO INTEGER AUTO_INCREMENT PRIMARY KEY
);

CREATE TABLE USUARIOS_GUIA_SUPLEMENTACAO (
    FK_GUIAS_DE_SUPLEMENTACAO_GSP_CODIGO INTEGER,
    FK_USUARIOS_USU_CPF INTEGER,
    USU_GSP_CODIGO INTEGER AUTO_INCREMENT PRIMARY KEY
);

CREATE TABLE EDUCADORES_PROGRAMAS_TREINAMENTO (
    FK_EDUCADORES_FISICOS_EDU_CREF INTEGER,
    FK_PROGRAMAS_DE_TREINAMENTO_PGT_CODIGO INTEGER
);

CREATE TABLE EDUCADORES_EXERCICIOS_FISICOS (
    FK_EDUCADORES_FISICOS_EDU_CREF INTEGER,
    FK_EXERCICIOS_FISICOS_EXF_CODIGO INTEGER,
    EEX_CODIGO INTEGER AUTO_INCREMENT PRIMARY KEY
);

CREATE TABLE EXERCICIOS_FISICOS_GRUPOS_MUSCULARES (
    FK_GRUPOS_MUSCULARES_GMC_CODIGO INTEGER,
    FK_EXERCICIOS_FISICOS_EXF_CODIGO INTEGER,
    EGM_CODIGO INTEGER AUTO_INCREMENT PRIMARY KEY
);

CREATE TABLE EXERCICIOS_FISICOS_PROGRAMAS_TREINAMENTO (
    FK_PROGRAMAS_DE_TREINAMENTO_PGT_CODIGO INTEGER,
    FK_EXERCICIOS_FISICOS_EXF_CODIGO INTEGER,
    EPT_CARGA_PESO INTEGER,
    EPT_PGT_REPETICOES INTEGER,
    EPT_INTERVALO VARCHAR(80),
    EPT_CODIGO INTEGER AUTO_INCREMENT PRIMARY KEY
);
 
ALTER TABLE TESTES_PSICOLOGICOS ADD CONSTRAINT FK_TESTES_PSICOLOGICOS_1
    FOREIGN KEY (FK_USUARIOS_USU_CPF)
    REFERENCES USUARIOS (USU_CPF)
    ON DELETE CASCADE ON UPDATE CASCADE;
 
ALTER TABLE EXERCICIOS_FISICOS ADD CONSTRAINT FK_EXERCICIOS_FISICOS_1
    FOREIGN KEY (FK_TIPOS_EXECICIOS_FISICOS_TEF_CODIGO)
    REFERENCES TIPOS_EXECICIOS_FISICOS (TEF_CODIGO)
    ON DELETE CASCADE ON UPDATE CASCADE;
 
ALTER TABLE EXERCICIOS_FISICOS ADD CONSTRAINT FK_EXERCICIOS_FISICOS_2
    FOREIGN KEY (FK_UNIDADES_DE_MEDIDAS_UNM_CODIGO)
    REFERENCES UNIDADES_DE_MEDIDAS (UNM_CODIGO)
    ON DELETE CASCADE ON UPDATE CASCADE;
 
ALTER TABLE RESPOSTAS_TESTE_PERGUNTAS ADD CONSTRAINT FK_RESPOSTAS_TESTE_PERGUNTAS_1
    FOREIGN KEY (FK_PERGUNTAS_TESTE_PSICOLOGICO_PTP_CODIGO)
    REFERENCES PERGUNTAS_TESTE_PSICOLOGICO (PTP_CODIGO)
    ON DELETE SET NULL ON UPDATE CASCADE;
 
ALTER TABLE RESPOSTAS_TESTE_PERGUNTAS ADD CONSTRAINT FK_RESPOSTAS_TESTE_PERGUNTAS_2
    FOREIGN KEY (FK_TESTES_PSICOLOGICOS_TPS_CODIGO)
    REFERENCES TESTES_PSICOLOGICOS (TPS_CODIGO)
    ON DELETE SET NULL ON UPDATE CASCADE;
 
ALTER TABLE USUARIOS_EXERCICIOS_FISICOS ADD CONSTRAINT FK_USUARIOS_EXERCICIOS_FISICOS_1
    FOREIGN KEY (FK_USUARIOS_USU_CPF)
    REFERENCES USUARIOS (USU_CPF)
    ON DELETE SET NULL ON UPDATE CASCADE;
 
ALTER TABLE USUARIOS_EXERCICIOS_FISICOS ADD CONSTRAINT FK_USUARIOS_EXERCICIOS_FISICOS_2
    FOREIGN KEY (FK_EXERCICIOS_FISICOS_EXF_CODIGO)
    REFERENCES EXERCICIOS_FISICOS (EXF_CODIGO)
    ON DELETE SET NULL ON UPDATE CASCADE;
 
ALTER TABLE USUARIOS_GUIA_SUPLEMENTACAO ADD CONSTRAINT FK_USUARIOS_GUIA_SUPLEMENTACAO_1
    FOREIGN KEY (FK_GUIAS_DE_SUPLEMENTACAO_GSP_CODIGO)
    REFERENCES GUIAS_DE_SUPLEMENTACAO (GSP_CODIGO)
    ON DELETE SET NULL ON UPDATE CASCADE;
 
ALTER TABLE USUARIOS_GUIA_SUPLEMENTACAO ADD CONSTRAINT FK_USUARIOS_GUIA_SUPLEMENTACAO_2
    FOREIGN KEY (FK_USUARIOS_USU_CPF)
    REFERENCES USUARIOS (USU_CPF)
    ON DELETE SET NULL ON UPDATE CASCADE;
 
ALTER TABLE EDUCADORES_PROGRAMAS_TREINAMENTO ADD CONSTRAINT FK_EDUCADORES_PROGRAMAS_TREINAMENTO_0
    FOREIGN KEY (FK_EDUCADORES_FISICOS_EDU_CREF)
    REFERENCES EDUCADORES_FISICOS (EDU_CREF)
    ON DELETE SET NULL ON UPDATE CASCADE;
 
ALTER TABLE EDUCADORES_PROGRAMAS_TREINAMENTO ADD CONSTRAINT FK_EDUCADORES_PROGRAMAS_TREINAMENTO_1
    FOREIGN KEY (FK_PROGRAMAS_DE_TREINAMENTO_PGT_CODIGO)
    REFERENCES PROGRAMAS_DE_TREINAMENTO (PGT_CODIGO)
    ON DELETE SET NULL ON UPDATE CASCADE;
 
ALTER TABLE EDUCADORES_EXERCICIOS_FISICOS ADD CONSTRAINT FK_EDUCADORES_EXERCICIOS_FISICOS_1
    FOREIGN KEY (FK_EDUCADORES_FISICOS_EDU_CREF)
    REFERENCES EDUCADORES_FISICOS (EDU_CREF)
    ON DELETE SET NULL ON UPDATE CASCADE;
 
ALTER TABLE EDUCADORES_EXERCICIOS_FISICOS ADD CONSTRAINT FK_EDUCADORES_EXERCICIOS_FISICOS_2
    FOREIGN KEY (FK_EXERCICIOS_FISICOS_EXF_CODIGO)
    REFERENCES EXERCICIOS_FISICOS (EXF_CODIGO)
    ON DELETE SET NULL ON UPDATE CASCADE;
 
ALTER TABLE EXERCICIOS_FISICOS_GRUPOS_MUSCULARES ADD CONSTRAINT FK_EXERCICIOS_FISICOS_GRUPOS_MUSCULARES_1
    FOREIGN KEY (FK_GRUPOS_MUSCULARES_GMC_CODIGO)
    REFERENCES GRUPOS_MUSCULARES (GMC_CODIGO)
    ON DELETE SET NULL ON UPDATE CASCADE;
 
ALTER TABLE EXERCICIOS_FISICOS_GRUPOS_MUSCULARES ADD CONSTRAINT FK_EXERCICIOS_FISICOS_GRUPOS_MUSCULARES_2
    FOREIGN KEY (FK_EXERCICIOS_FISICOS_EXF_CODIGO)
    REFERENCES EXERCICIOS_FISICOS (EXF_CODIGO)
    ON DELETE SET NULL ON UPDATE CASCADE;
 
ALTER TABLE EXERCICIOS_FISICOS_PROGRAMAS_TREINAMENTO ADD CONSTRAINT FK_EXERCICIOS_FISICOS_PROGRAMAS_TREINAMENTO_1
    FOREIGN KEY (FK_PROGRAMAS_DE_TREINAMENTO_PGT_CODIGO)
    REFERENCES PROGRAMAS_DE_TREINAMENTO (PGT_CODIGO)
    ON DELETE SET NULL ON UPDATE CASCADE;
 
ALTER TABLE EXERCICIOS_FISICOS_PROGRAMAS_TREINAMENTO ADD CONSTRAINT FK_EXERCICIOS_FISICOS_PROGRAMAS_TREINAMENTO_2
    FOREIGN KEY (FK_EXERCICIOS_FISICOS_EXF_CODIGO)
    REFERENCES EXERCICIOS_FISICOS (EXF_CODIGO)
    ON DELETE SET NULL ON UPDATE CASCADE;