CREATE DATABASE IF NOT EXISTS BANCO_MOD04;
USE BANCO_MOD04;

CREATE TABLE EDUCADORES_FISICOS (
EDU_CODIGO INTEGER AUTO_INCREMENT PRIMARY KEY,
EDU_NOME VARCHAR(100) NOT NULL,
EDU_GENERO INTEGER NOT NULL,
EDU_FORMACAO VARCHAR(100) NOT NULL,
EDU_FOCO INTEGER NOT NULL,
EDU_DESCRICAO VARCHAR(1000),
EDU_DATA_NASCIMENTO DATE NOT NULL
);

CREATE TABLE SUPLEMENTOS (
SUP_CODIGO INTEGER AUTO_INCREMENT PRIMARY KEY,
SUP_NOME VARCHAR(100) NOT NULL,
SUP_FOTO VARCHAR(255),
SUP_DESCRICAO VARCHAR(1000) NOT NULL,
SUP_UTILIZAÇÃO VARCHAR(1000) NOT NULL,
SUP_COMPOSICAO VARCHAR(1000) NOT NULL,
SUP_TIPO VARCHAR(100) NOT NULL,
EDU_CODIGO INTEGER,
FOREIGN KEY(EDU_CODIGO) REFERENCES EDUCADORES_FISICOS (EDU_CODIGO)
);

CREATE TABLE DISPONIBILIDADE_AGENDA_EDUCADOR_FISICO (
DIS_CODIGO INTEGER AUTO_INCREMENT PRIMARY KEY,
DIS_HORA TIME NOT NULL,
DIS_DIA_SEMANA VARCHAR(10) NOT NULL,
DIS_LOCAL VARCHAR(1000) NOT NULL,
EDU_CODIGO INTEGER,
FOREIGN KEY(EDU_CODIGO) REFERENCES EDUCADORES_FISICOS (EDU_CODIGO)
);

CREATE TABLE DOBRAS_CUTANEAS (
DOB_CODIGO INTEGER AUTO_INCREMENT PRIMARY KEY,
DOB_COXA DECIMAL(10,2) NOT NULL,
DOB_TORAXICA DECIMAL(10,2) NOT NULL,
DOB_BICIPTAL DECIMAL(10,2) NOT NULL,
DOB_PANTURRILHA_MEDIAL DECIMAL(10,2) NOT NULL,
DOB_DATA DATE NOT NULL,
DOB_TRICIPTAL DECIMAL(10,2) NOT NULL,
DOB_SUBESCAPULAR DECIMAL(10,2) NOT NULL,
DOB_AXILAR_MEDIA DECIMAL(10,2) NOT NULL,
DOB_ABDOMINAL DECIMAL(10,2) NOT NULL,
DOB_SUPRA_ILIACA DECIMAL(10,2) NOT NULL,
POP_CODIGO INTEGER
);

CREATE TABLE PERFIL_DE_TREINAMENTO (
PER_CODIGO INTEGER AUTO_INCREMENT PRIMARY KEY,
PER_DATA_ATUALIZACAO DATE NOT NULL,
PER_EXPERIENCIA INTEGER NOT NULL,
PER_OBJETIVO INTEGER NOT NULL,
POP_CODIGO INTEGER
);

CREATE TABLE MEDIDAS_CORPORAIS (
MED_PESCOCO DECIMAL(10,2) NOT NULL,
MED_BICEPS_DIREITO DECIMAL(10,2) NOT NULL,
MED_PANTURRILHA_DIREITA DECIMAL(10,2) NOT NULL,
MED_ALTURA DECIMAL(10,2) NOT NULL,
MED_PESO DECIMAL(10,2) NOT NULL,
MED_COXA_DIREITA DECIMAL(10,2) NOT NULL,
MED_QUADRIS DECIMAL(10,2) NOT NULL,
MED_PANTURRILHA_ESQUERDA DECIMAL(10,2) NOT NULL,
MED_BICEPS_ESQUERDO DECIMAL(10,2) NOT NULL,
MED_COXA_ESQUERDA DECIMAL(10,2) NOT NULL,
MED_PEITO DECIMAL(10,2) NOT NULL,
MED_DATA DATE NOT NULL,
MED_CINTURA DECIMAL(10,2) NOT NULL,
MED_CODIGO INTEGER AUTO_INCREMENT PRIMARY KEY,
POP_CODIGO INTEGER,
DAD_CODIGO INTEGER 
);

CREATE TABLE POPULAÇÃO (
POP_CODIGO INTEGER AUTO_INCREMENT PRIMARY KEY,
POP_NOME VARCHAR(100) NOT NULL,
POP_SOBRENOME VARCHAR(100) NOT NULL,
POP_DATA_NASCIMENTO DATE NOT NULL,
POP_ENDERECO VARCHAR(1000) NOT NULL,
POP_TELEFONE VARCHAR(10) NOT NULL,
POP_EMAIL VARCHAR(100) NOT NULL,
POP_GENERO INTEGER NOT NULL,
POP_FOTO VARCHAR(255),
POP_CPF VARCHAR(11) UNIQUE NOT NULL,
EDU_CODIGO INTEGER ,
FOREIGN KEY(EDU_CODIGO) REFERENCES EDUCADORES_FISICOS (EDU_CODIGO)
);

CREATE TABLE DADOS_CONSULTA (
DAD_CODIGO INTEGER AUTO_INCREMENT PRIMARY KEY,
DAD_PESO DECIMAL(10,2) NOT NULL,
DAD_ALTURA DECIMAL(10,2) NOT NULL,
DAD_IMC INTEGER NOT NULL,
DAD_ANOTACOES VARCHAR(1000) NOT NULL,
POP_CODIGO INTEGER ,
CON_CODIGO INTEGER ,
FOREIGN KEY(POP_CODIGO) REFERENCES POPULAÇÃO (POP_CODIGO)
);

CREATE TABLE HISTORICO_SOLICITACOES_ACOMPANHAMENTO (
HIS_CODIGO INTEGER AUTO_INCREMENT PRIMARY KEY,
HIS_DATA_SOLICITACAO DATE NOT NULL,
HIS_RESPOSTA_SOLICITACAO BOOLEAN NOT NULL,
EDU_CODIGO INTEGER ,
POP_CODIGO INTEGER ,
FOREIGN KEY(EDU_CODIGO) REFERENCES EDUCADORES_FISICOS (EDU_CODIGO),
FOREIGN KEY(POP_CODIGO) REFERENCES POPULAÇÃO (POP_CODIGO)
);

CREATE TABLE CONSULTAS_MARCADAS_EDUCADOR_FISICO (
CON_CODIGO INTEGER AUTO_INCREMENT PRIMARY KEY,
CON_DATA DATE NOT NULL,
CON_LOCAL VARCHAR(1000) NOT NULL,
CON_STATUS INTEGER NOT NULL,
CON_LINK_GOOGLEMAPS VARCHAR(1000) NOT NULL,
CON_HORA TIME NOT NULL,
EDU_CODIGO INTEGER ,
POP_CODIGO INTEGER ,
FOREIGN KEY(EDU_CODIGO) REFERENCES EDUCADORES_FISICOS (EDU_CODIGO),
FOREIGN KEY(POP_CODIGO) REFERENCES POPULAÇÃO (POP_CODIGO)
);

CREATE TABLE TREINOS (
TRE_CODIGO INTEGER AUTO_INCREMENT PRIMARY KEY,
TRE_NOME VARCHAR(100) NOT NULL,
TRE_SEGUNDA BOOLEAN NOT NULL,
TRE_TERCA BOOLEAN NOT NULL,
TRE_QUARTA BOOLEAN NOT NULL,
TRE_QUINTA BOOLEAN NOT NULL,
TRE_SEXTA BOOLEAN NOT NULL,
TRE_SABADO BOOLEAN NOT NULL,
FIC_CODIGO INTEGER
);

CREATE TABLE FICHAS_DE_TREINAMENTO (
FIC_CODIGO INTEGER AUTO_INCREMENT PRIMARY KEY,
FIC_DATA_INICIO DATE NOT NULL,
FIC_DATA_TERMINO DATE NOT NULL,
POP_CODIGO INTEGER ,
EDU_CODIGO INTEGER ,
FOREIGN KEY(POP_CODIGO) REFERENCES POPULAÇÃO (POP_CODIGO),
FOREIGN KEY(EDU_CODIGO) REFERENCES EDUCADORES_FISICOS (EDU_CODIGO)
);

CREATE TABLE EXERCICIOS (
EXE_CODIGO INTEGER AUTO_INCREMENT PRIMARY KEY,
EXE_DESCRICAO VARCHAR(1000) NOT NULL,
EXE_NOME VARCHAR(100) NOT NULL,
TIP_CODIGO INTEGER 
);

CREATE TABLE TIPOS_EXERCICIOS (
TIP_CODIGO INTEGER AUTO_INCREMENT PRIMARY KEY,
TIP_NOME VARCHAR(50) NOT NULL
);

CREATE TABLE GRUPOS_MUSCULARES (
GRU_CODIGO INTEGER AUTO_INCREMENT PRIMARY KEY,
GRU_NOME VARCHAR(50) NOT NULL
);

CREATE TABLE EXERCICIOS_GRUPOS_MUSCULARES (
EXE_GRU_CODIGO INTEGER AUTO_INCREMENT PRIMARY KEY,
GRU_CODIGO INTEGER ,
EXE_CODIGO INTEGER ,
FOREIGN KEY(GRU_CODIGO) REFERENCES GRUPOS_MUSCULARES (GRU_CODIGO),
FOREIGN KEY(EXE_CODIGO) REFERENCES EXERCICIOS (EXE_CODIGO)
);

CREATE TABLE TREINOS_EXERCICIOS (
TRE_EXE_CODIGO INTEGER AUTO_INCREMENT PRIMARY KEY,
TRE_EXE_SERIES INTEGER NOT NULL,
TRE_EXE_REPETICOES INTEGER NOT NULL,
TRE_EXE_QUANTIDADE DECIMAL(10,2) NOT NULL,
EXE_CODIGO INTEGER ,
TRE_CODIGO INTEGER ,
FOREIGN KEY(EXE_CODIGO) REFERENCES EXERCICIOS (EXE_CODIGO),
FOREIGN KEY(TRE_CODIGO) REFERENCES TREINOS (TRE_CODIGO)
);

ALTER TABLE DOBRAS_CUTANEAS ADD FOREIGN KEY(POP_CODIGO) REFERENCES POPULAÇÃO (POP_CODIGO);
ALTER TABLE PERFIL_DE_TREINAMENTO ADD FOREIGN KEY(POP_CODIGO) REFERENCES POPULAÇÃO (POP_CODIGO);
ALTER TABLE MEDIDAS_CORPORAIS ADD FOREIGN KEY(POP_CODIGO) REFERENCES POPULAÇÃO (POP_CODIGO);
ALTER TABLE MEDIDAS_CORPORAIS ADD FOREIGN KEY(DAD_CODIGO) REFERENCES DADOS_CONSULTA (DAD_CODIGO);
ALTER TABLE DADOS_CONSULTA ADD FOREIGN KEY(CON_CODIGO) REFERENCES CONSULTAS_MARCADAS_EDUCADOR_FISICO (CON_CODIGO);
ALTER TABLE TREINOS ADD FOREIGN KEY(FIC_CODIGO) REFERENCES FICHAS_DE_TREINAMENTO (FIC_CODIGO);
ALTER TABLE EXERCICIOS ADD FOREIGN KEY(TIP_CODIGO) REFERENCES TIPOS_EXERCICIOS (TIP_CODIGO);
