/* REL_Mod01: */

CREATE TABLE CIDADAOS (
    USU_ID INTEGER AUTO_INCREMENT PRIMARY KEY,
    USU_CPF CHAR(11) NOT NULL,
    USU_RG VARCHAR(10) NOT NULL,
    USU_DATA_NASCIMENTO DATE NOT NULL,
    USU_EMAIL VARCHAR(255) NOT NULL,
    USU_SENHA VARCHAR(12) NOT NULL,
    USU_CELULAR CHAR(13) NOT NULL,
    USU_ESTADO CHAR(2) NOT NULL,
    USU_CIDADE VARCHAR(50) NOT NULL,
    USU_RUA VARCHAR(100) NOT NULL,
    USU_NUMERO_RESIDENCIA VARCHAR(5) NOT NULL,
    USU_BAIRRO VARCHAR(50) NOT NULL,
    USU_CEP CHAR(8) NOT NULL,
    USU_SEXO ENUM('F', 'M', 'P'),
    USU_FOTO_PERFIL VARCHAR(255),
    USU_NOME VARCHAR(100) NOT NULL,
    UNIQUE (USU_CPF, USU_RG, USU_CELULAR, USU_EMAIL, USU_NOME)
);

CREATE TABLE GESTORES (
    GES_PRONTUARIO VARCHAR(7) NOT NULL,
    GES_RAMAL VARCHAR(10) NOT NULL,
    USU_ID INTEGER AUTO_INCREMENT PRIMARY KEY,
    USU_CPF CHAR(11) NOT NULL,
    USU_RG VARCHAR(10) NOT NULL,
    USU_DATA_NASCIMENTO DATE NOT NULL,
    USU_EMAIL VARCHAR(255) NOT NULL,
    USU_SENHA VARCHAR(12) NOT NULL,
    USU_CELULAR CHAR(13) NOT NULL,
    USU_ESTADO CHAR(2) NOT NULL,
    USU_CIDADE VARCHAR(50) NOT NULL,
    USU_RUA VARCHAR(100) NOT NULL,
    USU_NUMERO_RESIDENCIA VARCHAR(5) NOT NULL,
    USU_BAIRRO VARCHAR(50) NOT NULL,
    USU_CEP CHAR(8) NOT NULL,
    USU_SEXO ENUM('F', 'M', 'P'),
    USU_FOTO_PERFIL VARCHAR(255),
    USU_NOME VARCHAR(100) NOT NULL,
    FK_SETORES_SET_ID INTEGER,
    UNIQUE (USU_CPF, USU_RG, GES_PRONTUARIO, USU_EMAIL, USU_CELULAR, USU_NOME)
);

CREATE TABLE SETORES (
    SET_ID INTEGER AUTO_INCREMENT PRIMARY KEY,
    SET_NOME VARCHAR(100) NOT NULL
);

CREATE TABLE DUVIDAS_FEEDBACKS (
    DEF_DATA_HORA DATETIME NOT NULL,
    DEF_URGENCIA ENUM('1', '2', '3') NOT NULL,
    DEF_TEMA VARCHAR(80) NOT NULL,
    DEF_ID INTEGER AUTO_INCREMENT PRIMARY KEY,
    DEF_DESCRICAO TEXT NOT NULL,
    DEF_ANEXO VARCHAR(255),
    DEF_STATUS BOOLEAN NOT NULL,
    FK_CIDADAOS_USU_ID INTEGER
);

CREATE TABLE RESPOSTAS_DUVIDAS_FEEDBACKS (
    RES_TEXTO TEXT NOT NULL,
    RES_ANEXO VARCHAR(255),
    RES_ID INTEGER AUTO_INCREMENT PRIMARY KEY,
    RES_DATA_HORA DATETIME NOT NULL,
    FK_SERVIDORES_USU_ID INTEGER,
    FK_DUVIDAS_FEEDBACKS_DEF_ID INTEGER
);
 
ALTER TABLE GESTORES ADD CONSTRAINT FK_GESTORES_2
    FOREIGN KEY (FK_SETORES_SET_ID)
    REFERENCES SETORES (SET_ID)
    ON DELETE CASCADE;
 
ALTER TABLE DUVIDAS_FEEDBACKS ADD CONSTRAINT FK_DUVIDAS_FEEDBACKS_2
    FOREIGN KEY (FK_CIDADAOS_USU_ID)
    REFERENCES CIDADAOS (USU_ID)
    ON DELETE CASCADE;
 
ALTER TABLE RESPOSTAS_DUVIDAS_FEEDBACKS ADD CONSTRAINT FK_RESPOSTAS_DUVIDAS_FEEDBACKS_2
    FOREIGN KEY (FK_SERVIDORES_USU_ID)
    REFERENCES GESTORES (USU_ID)
    ON DELETE CASCADE;
 
ALTER TABLE RESPOSTAS_DUVIDAS_FEEDBACKS ADD CONSTRAINT FK_RESPOSTAS_DUVIDAS_FEEDBACKS_3
    FOREIGN KEY (FK_DUVIDAS_FEEDBACKS_DEF_ID)
    REFERENCES DUVIDAS_FEEDBACKS (DEF_ID)
    ON DELETE CASCADE;