CREATE SCHEMA mod01;
USE mod01;

CREATE TABLE LOCALIZACOES (
LOC_ESTADO VARCHAR(50) NOT NULL,
LOC_BAIRRO VARCHAR(100) NOT NULL,
LOC_ID INTEGER AUTO_INCREMENT UNIQUE NOT NULL PRIMARY KEY,
LOC_CIDADE VARCHAR(100) NOT NULL,
LOC_RUA VARCHAR(100) NOT NULL,
LOC_CEP VARCHAR(10) NOT NULL
);

CREATE TABLE CONSUMIDORES (
CON_SENHA INTEGER(20) NOT NULL,
CON_CONFIRMAR_SENHA INTEGER(20) NOT NULL,
CON_TELEFONE1 VARCHAR(15) NOT NULL,
CON_COMPLEMENTO VARCHAR(500),
CON_SOBRENOME VARCHAR(100) NOT NULL,
CON_NOME VARCHAR(100) NOT NULL,
CON_CPF INTEGER(12) UNIQUE NOT NULL,
CON_FOTO_PERFIL VARCHAR(100),
CON_TELEFONE2 INTEGER(15),
CON_ID INTEGER AUTO_INCREMENT UNIQUE NOT NULL PRIMARY KEY,
CON_DATA_NASCIMENTO DATE NOT NULL,
CON_EMAIL VARCHAR(100) UNIQUE NOT NULL,
CON_NUMERO INTEGER NOT NULL,
CON_CADASTRO_VALIDADO VARCHAR(50) NOT NULL,
CON_DATA_HORA_EMAIL_VALIDACAO DATETIME NOT NULL,
CON_STATUS_BLOQUEIO BOOLEAN NOT NULL,
LOC_ID INTEGER UNIQUE NOT NULL,
FOREIGN KEY(LOC_ID) REFERENCES LOCALIZACOES (LOC_ID)
);

CREATE TABLE CONTATOS (
CNT_TITULO VARCHAR(100) NOT NULL,
CNT_ANEXO VARCHAR(100),
CNT_NOME VARCHAR(100) NOT NULL,
CNT_DESCRICAO VARCHAR(1000) NOT NULL,
CNT_ID INTEGER AUTO_INCREMENT UNIQUE NOT NULL PRIMARY KEY,
CNT_EMAIL VARCHAR(100) NOT NULL,
CON_ID INTEGER UNIQUE NOT NULL,
FOREIGN KEY(CON_ID) REFERENCES CONSUMIDORES (CON_ID)
);


CREATE TABLE PROJETO_RECLAMACOES (
PRE_PROBLEMA VARCHAR(1000) NOT NULL,
PRE_DESCRICAO VARCHAR(1000) NOT NULL,
PRE_ID INTEGER  AUTO_INCREMENT UNIQUE NOT NULL PRIMARY KEY,
PRE_SOLUCAO VARCHAR(1000) NOT NULL
);

CREATE TABLE ADMINISTRADORES (
ADM_ID INTEGER AUTO_INCREMENT UNIQUE NOT NULL PRIMARY KEY
);

CREATE TABLE CONVERSAS (
COV_ID INTEGER AUTO_INCREMENT UNIQUE NOT NULL PRIMARY KEY,
COV_CONTEUDO_USUARIO TEXT NOT NULL,
COV_ANEXO_ADM VARCHAR(500),
COV_DATA_HORA_USUARIO DATETIME NOT NULL,
COV_LIDA BOOLEAN NOT NULL,
COV_DATA_HORA_ADM DATETIME NOT NULL,
COV_CONTEUDO_ADM TEXT NOT NULL,
COV_ANEXO_USUARIO VARCHAR(500),
CON_ID INTEGER UNIQUE NOT NULL,
ADM_ID INTEGER UNIQUE NOT NULL,
FOREIGN KEY(CON_ID) REFERENCES CONSUMIDORES (CON_ID),
FOREIGN KEY(ADM_ID) REFERENCES ADMINISTRADORES (ADM_ID)
);

CREATE TABLE INTEGRANTES (
ING_REDES_SOCIAIS VARCHAR(100),
ING_NOME VARCHAR(50) NOT NULL,
ING_ID INTEGER AUTO_INCREMENT UNIQUE NOT NULL PRIMARY KEY,
ING_CURRICULO VARCHAR(500) NOT NULL,
PRE_ID INTEGER  UNIQUE NOT NULL,
FOREIGN KEY(PRE_ID) REFERENCES PROJETO_RECLAMACOES (PRE_ID)
);

CREATE TABLE HISTORICOS_BLOQUEIO (
HIS_ID INTEGER AUTO_INCREMENT UNIQUE NOT NULL PRIMARY KEY,
HIS_DATA_HORA_BLOQUEIO DATETIME NOT NULL,
HIS_DATA_HORA_DESBLOQUEIO DATETIME NOT NULL,
HIS_MOTIVO VARCHAR(500) NOT NULL,
CON_ID INTEGER UNIQUE NOT NULL,
FOREIGN KEY(CON_ID) REFERENCES CONSUMIDORES (CON_ID)
);

ALTER TABLE CONTATOS ADD FOREIGN KEY(CON_ID) REFERENCES CONSUMIDORES (CON_ID);
ALTER TABLE CONSUMIDORES ADD FOREIGN KEY(LOC_ID) REFERENCES LOCALIZACOES (LOC_ID);

