CREATE DATABASE IF NOT EXISTS CHECKUPS;

USE CHECKUPS;

CREATE TABLE IF NOT EXISTS POPULACAO (
    POP_COD INT NOT NULL PRIMARY KEY,
    POP_SEXO VARCHAR NOT NULL 
);

CREATE TABLE IF NOT EXISTS BPM (
	BPM_STATUS varchar(50),
    BPM_BATIMENTOS INT,
    BPM_DATA DATE,
    BPM_COD INT PRIMARY KEY,
    POP_COD INT NOT NULL,
    FOREIGN KEY (POP_COD) REFERENCES POPULACAO (POP_COD)
);

CREATE TABLE IF NOT EXISTS IMC (
	IMC_STATUS varchar(50),
    IMC_COD INT NOT NULL PRIMARY KEY,
    IMC_IMC DEC(10,3),
    IMC_DATA DATE,
    IMC_PESO DEC (10,3) NOT NULL,
    IMC_ALTURA DEC(10,3) NOT NULL,
    POP_COD INT NOT NULL,
    FOREIGN KEY (POP_COD) REFERENCES POPULACAO (POP_COD)
);

CREATE TABLE IF NOT EXISTS SATURACAO_OXIGENIO (
	SAT_STATUS varchar(50),
    SAT_DATA DATE,
    SAT_COD INT PRIMARY KEY,
    SAT_PORCENTAGEM DEC(10,3),
    POP_COD INT,
    FOREIGN KEY (POP_COD) REFERENCES POPULACAO (POP_COD)
);

CREATE TABLE IF NOT EXISTS VISAO (
	VIS_STATUS varchar(50),
    VIS_ASTIGMATISMO DEC(10,3),
    VIS_COD INT NOT NULL PRIMARY KEY,
    VIS_MIOPIA DEC(10,3),
    VIS_HIPERMETROPIA DEC(10,3),
    VIS_DATA DATE,
    POP_COD INT NOT NULL,
    VIS_STATUS_ASTIGMATISMO VARCHAR(50) NOT NULL,
    VIS_STATUS_MIOPIA VARCHAR(50) NOT NULL,
    VIS_STATUS_HIPERMETROPIA VARCHAR(50) NOT NULL,
    VIS_STATUS_DALTONISMO VARCHAR(50) NOT NULL,
    VIS_DALT_2 INT NOT NULL,
	VIS_DALT_3 INT NOT NULL,
	VIS_DALT_6 INT NOT NULL,
	VIS_DALT_12 INT NOT NULL,
    VIS_RES_ASTIGMATISMO BOOLEAN NOT NULL,
    VIS_RES_MIOPIA BOOLEAN NOT NULL,
    VIS_RES_DALTONISMO BOOLEAN NOT NULL,
    VIS_RES_HIPERMETROPIA BOOLEAN NOT NULL,
    FOREIGN KEY (POP_COD) REFERENCES POPULACAO (POP_COD),
    
);

CREATE TABLE IF NOT EXISTS PRESSAO_ARTERIAL (
	PRA_STATUS varchar(50),
    PRA_COD INT NOT NULL PRIMARY KEY,
    PRA_DATA DATE,
    PRA_PRESSAO_DIASTOLICA DEC(10,3),
    PRA_PRESSAO_SISTOLICA DEC(10,3),
    POP_COD INT NOT NULL,
    FOREIGN KEY (POP_COD) REFERENCES POPULACAO (POP_COD)
);

CREATE TABLE IF NOT EXISTS CAPACIDADE_PULMONAR (
	CPR_STATUS varchar(50),
    CPR_DATA DATE,
    CPR_CAPACIDADE DEC(10,3),
    CPR_COD INT NOT NULL PRIMARY KEY,
    CPR_INSPIRACAO DEC(10,3) NOT NULL,
    CPR_EXPIRACAO DEC(10,3) NOT NULL,
    POP_COD INT NOT NULL,
    FOREIGN KEY (POP_COD) REFERENCES POPULACAO (POP_COD)
    
);

CREATE TABLE IF NOT EXISTS TAXA_GORDURA (
	TXG_STATUS varchar(50),
    TXG_COD INT NOT NULL PRIMARY KEY,
    TXG_DATA DATE,
    TXG_PERCENTUAL DEC(10,3),
    TXG_IMC DEC(10,3) NOT NULL,
    TXG_IDADE INT NOT NULL,
    POP_COD INT NOT NULL,
    FOREIGN KEY (POP_COD) REFERENCES POPULACAO (POP_COD)
);
 
