/* CRIACAO DO BD INTEGRADO */
DROP DATABASE IF EXISTS SUSTENTA_SJ;
CREATE DATABASE SUSTENTA_SJ;
USE SUSTENTA_SJ;

/* DB-Integrado-Relacional: */

CREATE TABLE RESPOSTAS_DUVIDAS_FEEDBACKS (
    RES_TEXTO TEXT NOT NULL,
    RES_ID INTEGER AUTO_INCREMENT PRIMARY KEY,
    RES_ANEXO VARCHAR(255),
    RES_DATA_HORA DATETIME,
    FK_DUVIDAS_FEEDBACKS_DEF_ID INTEGER,
    FK_GESTORES_USU_ID INTEGER
);

CREATE TABLE DUVIDAS_FEEDBACKS (
    DEF_DESCRICAO TEXT NOT NULL,
    DEF_URGENCIA ENUM('1', '2', '3'),
    DEF_TEMA VARCHAR(80) NOT NULL,
    DEF_STATUS BOOLEAN,
    DEF_DATA_HORA DATETIME,
    DEF_ID INTEGER AUTO_INCREMENT PRIMARY KEY,
    DEF_ANEXO VARCHAR(255),
    FK_CIDADAOS_USU_ID INTEGER,
    FK_SETORES_SET_ID INTEGER
);

CREATE TABLE CIDADAOS (
    USU_CELULAR CHAR(13),
    USU_EMAIL VARCHAR(255) UNIQUE,
    USU_RG VARCHAR(10),
    USU_ID INTEGER AUTO_INCREMENT PRIMARY KEY,
    USU_CEP CHAR(8),
    USU_CIDADE VARCHAR(50),
    USU_NUMERO_RESIDENCIA VARCHAR(5),
    USU_ESTADO CHAR(2),
    USU_RUA VARCHAR(100),
    USU_BAIRRO VARCHAR(50),
    USU_DATA_NASCIMENTO DATE,
    USU_SEXO ENUM('F', 'M', 'P'),
    USU_SENHA VARCHAR(50) NOT NULL,
    USU_FOTO_PERFIL VARCHAR(255),
    USU_CPF CHAR(11),
    USU_NOME VARCHAR(100)
);

CREATE TABLE GESTORES (
    GES_PRONTUARIO VARCHAR(7),
    USU_CELULAR CHAR(13),
    USU_EMAIL VARCHAR(255) UNIQUE,
    USU_RG VARCHAR(10),
    USU_ID INTEGER AUTO_INCREMENT PRIMARY KEY,
    USU_CEP CHAR(8),
    USU_CIDADE VARCHAR(50),
    USU_NUMERO_RESIDENCIA VARCHAR(5),
    USU_ESTADO CHAR(2),
    USU_RUA VARCHAR(100),
    USU_BAIRRO VARCHAR(50),
    USU_DATA_NASCIMENTO DATE,
    USU_SEXO ENUM('F', 'M', 'P'),
    USU_SENHA VARCHAR(50) NOT NULL,
    USU_FOTO_PERFIL VARCHAR(255),
    USU_CPF CHAR(11),
    USU_NOME VARCHAR(100),
    FK_SETORES_SET_ID INTEGER,
    GES_RAMAL VARCHAR(10)
);

CREATE TABLE SETORES (
    SET_NOME VARCHAR(200) UNIQUE,
    SET_ID INTEGER AUTO_INCREMENT PRIMARY KEY,
    SET_DATA_CRIACAO DATE,
    SET_DESCRICAO_SERVICOS TEXT
);

CREATE TABLE DENUNCIAS (
    DEN_DESCRICAO TEXT NOT NULL,
    DEN_COMPLEMENTO VARCHAR(100),
    DEN_CEP INTEGER,
    DEN_NUMERO INTEGER,
    DEN_RUA VARCHAR(100),
    DEN_BAIRRO VARCHAR(100),
    DEN_STATUS_DENUNCIA ENUM( 'R', 'A', 'NR'),
    DEN_DATA_PUBLICACAO DATETIME,
    DEN_DATA_ALT_STATUS DATETIME,
    DEN_QDE_CURTIDAS INTEGER,
    DEN_TITULO VARCHAR(100) NOT NULL,
    DEN_FOTO_VIDEO VARCHAR(255),
    DEN_ID INTEGER AUTO_INCREMENT PRIMARY KEY,
    FK_CIDADAOS_USU_ID INTEGER,
    FK_SETORES_SET_ID INTEGER,
    FK_GESTORES_USU_ID INTEGER
);

CREATE TABLE COMENTARIOS (
    COM_DATA_HORA DATETIME,
    COM_TEXTO TEXT NOT NULL,
    COM_ID INTEGER AUTO_INCREMENT PRIMARY KEY,
    FK_CIDADAOS_USU_ID INTEGER,
    FK_DENUNCIAS_DEN_ID INTEGER
);

CREATE TABLE PUNICOES (
    PUN_TEMPO ENUM('24 HORAS','7 DIAS','1 MES','BANIMENTO DEFINITIVO') NOT NULL,
    PUN_ID INTEGER AUTO_INCREMENT PRIMARY KEY,
    PUN_JUSTIFICATIVA TEXT NOT NULL,
    PUN_MOTIVO ENUM('PALAVRAS PERJORATIVAS','ODIO GRATUITO','CONTEUDO PORNOGRAFICO','COMENTARIOS OFENSIVOS') NOT NULL
);

CREATE TABLE VIOLACOES (
    VIO_DESCRICAO TEXT NOT NULL,
    VIO_ID INTEGER AUTO_INCREMENT PRIMARY KEY,
    VIO_IMAGEM VARCHAR(255),
    FK_PUNICOES_PUN_ID INTEGER,
    FK_DENUNCIAS_DEN_ID INTEGER,
    FK_CIDADAOS_USU_ID INTEGER
);

CREATE TABLE DESCARTE_RESIDUOS (
    DSR_QUANTIDADE DECIMAL(8,2) NOT NULL,
    DSR_DATA_HORA_DESCARTE DATETIME,
    DSR_ID INTEGER AUTO_INCREMENT PRIMARY KEY,
    FK_CIDADAOS_USU_ID INTEGER,
    FK_RESIDUOS_SOLIDOS_RES_ID INTEGER,
    FK_PONTOS_COLETA_PCO_ID INTEGER
);

CREATE TABLE RESIDUOS_SOLIDOS (
    RES_NOME_RESIDUO VARCHAR(50) NOT NULL,
    RES_ID INTEGER AUTO_INCREMENT PRIMARY KEY,
    RES_DESCRICAO VARCHAR(255)
);

CREATE TABLE PONTOS_COLETA_PROPRIETARIOS (
    PCO_NOME VARCHAR(50) UNIQUE,
    PCO_ID INTEGER AUTO_INCREMENT PRIMARY KEY,
    PCO_DATA_TERMINO DATE,
    PCO_AVALIACAO ENUM('1', '2', '3', '4', '5'),
    PCO_RUA VARCHAR(100),
    PCO_LONGITUDE DECIMAL(8,6),
    PCO_NUMERO INT(4),
    PCO_LOGRADOURO TEXT,
    PCO_LATITUDE DECIMAL(8,6),
    PCO_BAIRRO VARCHAR(100),
    PCO_CEP VARCHAR(8),
    PCO_MODELO_DATA ENUM('M','S','A'),
    PCO_IMAGEM VARCHAR(255),
    PCO_CNPJ VARCHAR(18),
    PCO_TELEFONE VARCHAR(20),
    PCO_DATA_INICIO DATE,
    PRO_TELEFONE VARCHAR(15),
    PRO_RG VARCHAR(15),
    PRO_LOGRADOURO TEXT,
    PRO_CEP VARCHAR(8),
    PRO_RUA VARCHAR(100),
    PRO_NUMERO INT(4),
    PRO_BAIRRO VARCHAR(100),
    PRO_NOME VARCHAR(100),
    PRO_CPF VARCHAR(11)
);

CREATE TABLE SANEAMENTOS (
    SAN_DATA_CRIACAO DATE,
    SAN_NOME VARCHAR(100) NOT NULL,
    SAN_ID INTEGER AUTO_INCREMENT PRIMARY KEY,
    FK_TIPOS_SANEAMENTOS_TSS_ID INTEGER,
    FK_SETORES_SET_ID INTEGER
);

CREATE TABLE TIPOS_SANEAMENTOS (
    TSS_ID INTEGER AUTO_INCREMENT PRIMARY KEY,
    TSS_NOME VARCHAR(100) UNIQUE
);

CREATE TABLE RECLAMACOES (
    REC_TITULO_RECLAMACAO VARCHAR(200) NOT NULL,
    REC_ID INTEGER AUTO_INCREMENT PRIMARY KEY,
    REC_NOTA_AVALIACAO ENUM('1', '2', '3', '4', '5'),
    REC_ANEXO VARCHAR(255),
    REC_STATUS ENUM('R','P','A'),
    REC_DESCRICAO TEXT NOT NULL,
    REC_DATAHORA DATETIME,
    FK_CIDADAOS_USU_ID INTEGER,
    FK_SETORES_SET_ID INTEGER,
    FK_GESTORES_USU_ID INTEGER,
    REC_RESPOSTA_RECLAMACAO TEXT
);

CREATE TABLE DENUNCIAS_CURTIDAS (
    FK_CIDADAOS_USU_ID INTEGER,
    FK_DENUNCIAS_DEN_ID INTEGER,
    DEC_ID INTEGER AUTO_INCREMENT PRIMARY KEY
);

CREATE TABLE PONTOS_COLETA_RESIDUOS_ACEITOS (
    FK_PONTOS_COLETA_PROPRIETARIOS_PCO_ID INTEGER,
    FK_RESIDUOS_RES_ID INTEGER,
    PRA_ID INTEGER AUTO_INCREMENT PRIMARY KEY
);
 
ALTER TABLE RESPOSTAS_DUVIDAS_FEEDBACKS ADD CONSTRAINT FK_RESPOSTAS_DUVIDAS_FEEDBACKS_2
    FOREIGN KEY (FK_DUVIDAS_FEEDBACKS_DEF_ID)
    REFERENCES DUVIDAS_FEEDBACKS (DEF_ID)
    ON DELETE CASCADE;
 
ALTER TABLE RESPOSTAS_DUVIDAS_FEEDBACKS ADD CONSTRAINT FK_RESPOSTAS_DUVIDAS_FEEDBACKS_3
    FOREIGN KEY (FK_GESTORES_USU_ID)
    REFERENCES GESTORES (USU_ID)
    ON DELETE CASCADE;
 
ALTER TABLE DUVIDAS_FEEDBACKS ADD CONSTRAINT FK_DUVIDAS_FEEDBACKS_2
    FOREIGN KEY (FK_CIDADAOS_USU_ID)
    REFERENCES CIDADAOS (USU_ID)
    ON DELETE CASCADE;
 
ALTER TABLE DUVIDAS_FEEDBACKS ADD CONSTRAINT FK_DUVIDAS_FEEDBACKS_3
    FOREIGN KEY (FK_SETORES_SET_ID)
    REFERENCES SETORES (SET_ID);
 
ALTER TABLE GESTORES ADD CONSTRAINT FK_GESTORES_2
    FOREIGN KEY (FK_SETORES_SET_ID)
    REFERENCES SETORES (SET_ID)
    ON DELETE RESTRICT;
 
ALTER TABLE DENUNCIAS ADD CONSTRAINT FK_DENUNCIAS_2
    FOREIGN KEY (FK_CIDADAOS_USU_ID)
    REFERENCES CIDADAOS (USU_ID)
    ON DELETE CASCADE;
 
ALTER TABLE DENUNCIAS ADD CONSTRAINT FK_DENUNCIAS_3
    FOREIGN KEY (FK_SETORES_SET_ID)
    REFERENCES SETORES (SET_ID)
    ON DELETE CASCADE;
 
ALTER TABLE DENUNCIAS ADD CONSTRAINT FK_DENUNCIAS_4
    FOREIGN KEY (FK_GESTORES_USU_ID)
    REFERENCES GESTORES (USU_ID)
    ON DELETE SET NULL;
 
ALTER TABLE COMENTARIOS ADD CONSTRAINT FK_COMENTARIOS_2
    FOREIGN KEY (FK_CIDADAOS_USU_ID)
    REFERENCES CIDADAOS (USU_ID)
    ON DELETE CASCADE;
 
ALTER TABLE COMENTARIOS ADD CONSTRAINT FK_COMENTARIOS_3
    FOREIGN KEY (FK_DENUNCIAS_DEN_ID)
    REFERENCES DENUNCIAS (DEN_ID)
    ON DELETE CASCADE;
 
ALTER TABLE VIOLACOES ADD CONSTRAINT FK_VIOLACOES_2
    FOREIGN KEY (FK_PUNICOES_PUN_ID)
    REFERENCES PUNICOES (PUN_ID)
    ON DELETE CASCADE;
 
ALTER TABLE VIOLACOES ADD CONSTRAINT FK_VIOLACOES_3
    FOREIGN KEY (FK_DENUNCIAS_DEN_ID)
    REFERENCES DENUNCIAS (DEN_ID)
    ON DELETE CASCADE;
 
ALTER TABLE VIOLACOES ADD CONSTRAINT FK_VIOLACOES_4
    FOREIGN KEY (FK_CIDADAOS_USU_ID)
    REFERENCES CIDADAOS (USU_ID)
    ON DELETE CASCADE;
 
ALTER TABLE DESCARTE_RESIDUOS ADD CONSTRAINT FK_DESCARTE_RESIDUOS_2
    FOREIGN KEY (FK_CIDADAOS_USU_ID)
    REFERENCES CIDADAOS (USU_ID)
    ON DELETE CASCADE;
 
ALTER TABLE DESCARTE_RESIDUOS ADD CONSTRAINT FK_DESCARTE_RESIDUOS_3
    FOREIGN KEY (FK_RESIDUOS_SOLIDOS_RES_ID)
    REFERENCES RESIDUOS_SOLIDOS (RES_ID)
    ON DELETE CASCADE;
 
ALTER TABLE DESCARTE_RESIDUOS ADD CONSTRAINT FK_DESCARTE_RESIDUOS_4
    FOREIGN KEY (FK_PONTOS_COLETA_PCO_ID)
    REFERENCES PONTOS_COLETA_PROPRIETARIOS (PCO_ID);
 
ALTER TABLE SANEAMENTOS ADD CONSTRAINT FK_SANEAMENTOS_2
    FOREIGN KEY (FK_TIPOS_SANEAMENTOS_TSS_ID)
    REFERENCES TIPOS_SANEAMENTOS (TSS_ID)
    ON DELETE CASCADE;
 
ALTER TABLE SANEAMENTOS ADD CONSTRAINT FK_SANEAMENTOS_3
    FOREIGN KEY (FK_SETORES_SET_ID)
    REFERENCES SETORES (SET_ID)
    ON DELETE CASCADE;
 
ALTER TABLE RECLAMACOES ADD CONSTRAINT FK_RECLAMACOES_2
    FOREIGN KEY (FK_CIDADAOS_USU_ID)
    REFERENCES CIDADAOS (USU_ID)
    ON DELETE CASCADE;
 
ALTER TABLE RECLAMACOES ADD CONSTRAINT FK_RECLAMACOES_3
    FOREIGN KEY (FK_SETORES_SET_ID)
    REFERENCES SETORES (SET_ID)
    ON DELETE CASCADE;
 
ALTER TABLE RECLAMACOES ADD CONSTRAINT FK_RECLAMACOES_4
    FOREIGN KEY (FK_GESTORES_USU_ID)
    REFERENCES GESTORES (USU_ID)
    ON DELETE CASCADE;
 
ALTER TABLE DENUNCIAS_CURTIDAS ADD CONSTRAINT FK_DENUNCIAS_CURTIDAS_2
    FOREIGN KEY (FK_CIDADAOS_USU_ID)
    REFERENCES CIDADAOS (USU_ID)
    ON DELETE SET NULL;
 
ALTER TABLE DENUNCIAS_CURTIDAS ADD CONSTRAINT FK_DENUNCIAS_CURTIDAS_3
    FOREIGN KEY (FK_DENUNCIAS_DEN_ID)
    REFERENCES DENUNCIAS (DEN_ID)
    ON DELETE SET NULL;
 
ALTER TABLE PONTOS_COLETA_RESIDUOS_ACEITOS ADD CONSTRAINT FK_PONTOS_COLETA_RESIDUOS_ACEITOS_2
    FOREIGN KEY (FK_PONTOS_COLETA_PROPRIETARIOS_PCO_ID)
    REFERENCES PONTOS_COLETA_PROPRIETARIOS (PCO_ID)
    ON DELETE SET NULL;
 
ALTER TABLE PONTOS_COLETA_RESIDUOS_ACEITOS ADD CONSTRAINT FK_PONTOS_COLETA_RESIDUOS_ACEITOS_3
    FOREIGN KEY (FK_RESIDUOS_RES_ID)
    REFERENCES RESIDUOS_SOLIDOS (RES_ID);
	
INSERT INTO `setores` (`SET_NOME`, `SET_DATA_CRIACAO`, `SET_DESCRICAO_SERVICOS`) VALUES ('Gabinete do prefeito', '0000-00-00', '-');
INSERT INTO `setores` (`SET_NOME`, `SET_DATA_CRIACAO`, `SET_DESCRICAO_SERVICOS`) VALUES ('Administração da Prefeitura', '0000-00-00', '-');
INSERT INTO `setores` (`SET_NOME`, `SET_DATA_CRIACAO`, `SET_DESCRICAO_SERVICOS`) VALUES ('Desenvolvimento Econômico', '0000-00-00', '-');
INSERT INTO `setores` (`SET_NOME`, `SET_DATA_CRIACAO`, `SET_DESCRICAO_SERVICOS`) VALUES ('Segurança e Trânsito', '0000-00-00', '-');
INSERT INTO `setores` (`SET_NOME`, `SET_DATA_CRIACAO`, `SET_DESCRICAO_SERVICOS`) VALUES ('Assistência Social', '0000-00-00', '-');
INSERT INTO `setores` (`SET_NOME`, `SET_DATA_CRIACAO`, `SET_DESCRICAO_SERVICOS`) VALUES ('Comunicação Social', '0000-00-00', '-');
INSERT INTO `setores` (`SET_NOME`, `SET_DATA_CRIACAO`, `SET_DESCRICAO_SERVICOS`) VALUES ('Cultura', '0000-00-00', '-');
INSERT INTO `setores` (`SET_NOME`, `SET_DATA_CRIACAO`, `SET_DESCRICAO_SERVICOS`) VALUES ('Educação', '0000-00-00', '-');
INSERT INTO `setores` (`SET_NOME`, `SET_DATA_CRIACAO`, `SET_DESCRICAO_SERVICOS`) VALUES ('Engenharia', '0000-00-00', '-');
INSERT INTO `setores` (`SET_NOME`, `SET_DATA_CRIACAO`, `SET_DESCRICAO_SERVICOS`) VALUES ('Esportes', '0000-00-00', '-');
INSERT INTO `setores` (`SET_NOME`, `SET_DATA_CRIACAO`, `SET_DESCRICAO_SERVICOS`) VALUES ('Finanças', '0000-00-00', '-');
INSERT INTO `setores` (`SET_NOME`, `SET_DATA_CRIACAO`, `SET_DESCRICAO_SERVICOS`) VALUES ('Procuradoria-Geral do Município', '0000-00-00', '-');
INSERT INTO `setores` (`SET_NOME`, `SET_DATA_CRIACAO`, `SET_DESCRICAO_SERVICOS`) VALUES ('Meio Ambiente, Agricultura e Abastecimento', '0000-00-00', '-');
INSERT INTO `setores` (`SET_NOME`, `SET_DATA_CRIACAO`, `SET_DESCRICAO_SERVICOS`) VALUES ('Gestão e Planejamento Urbano', '0000-00-00', '-');
INSERT INTO `setores` (`SET_NOME`, `SET_DATA_CRIACAO`, `SET_DESCRICAO_SERVICOS`) VALUES ('Recursos Humanos', '0000-00-00', '-');
INSERT INTO `setores` (`SET_NOME`, `SET_DATA_CRIACAO`, `SET_DESCRICAO_SERVICOS`) VALUES ('Saúde', '0000-00-00', '-');
INSERT INTO `setores` (`SET_NOME`, `SET_DATA_CRIACAO`, `SET_DESCRICAO_SERVICOS`) VALUES ('Secretaria Geral', '0000-00-00', '-');
INSERT INTO `setores` (`SET_NOME`, `SET_DATA_CRIACAO`, `SET_DESCRICAO_SERVICOS`) VALUES ('Obras e Serviços Públicos', '0000-00-00', '-');
INSERT INTO `setores` (`SET_NOME`, `SET_DATA_CRIACAO`, `SET_DESCRICAO_SERVICOS`) VALUES ('Turismo', '0000-00-00', '-');
INSERT INTO `setores` (`SET_NOME`, `SET_DATA_CRIACAO`, `SET_DESCRICAO_SERVICOS`) VALUES ('Habitação', '0000-00-00', '-');
INSERT INTO `setores` (`SET_NOME`, `SET_DATA_CRIACAO`, `SET_DESCRICAO_SERVICOS`) VALUES ('Tecnologia da Informação', '0000-00-00', '-');
INSERT INTO `setores` (`SET_NOME`, `SET_DATA_CRIACAO`, `SET_DESCRICAO_SERVICOS`) VALUES ('Proteção e Bem-Estar Animal', '0000-00-00', '-');
