/* Banco_Logico_Modulo04_#01: */

CREATE TABLE ORGANIZADORES_EVENTOS (
    ORE_ID INTEGER AUTO_INCREMENT PRIMARY KEY,
    ORE_NOME VARCHAR(80) NOT NULL,
    ORE_NOME_SOCIAL VARCHAR(80) NULL,
    ORE_DATA_NASCIMENTO DATE NOT NULL,
    ORE_CPF VARCHAR(11) NOT NULL UNIQUE,
    ORE_RG VARCHAR(10) NOT NULL,
    ORE_TELEFONE VARCHAR(11) NOT NULL,
    ORE_SEXO ENUM('F', 'M') NOT NULL,
    ORE_ETNIA ENUM('Amarelo', 'Branco', 'Indigena', 'Pardo', 'Preto', 'Sem declaracao') NOT NULL,
    ORE_PRONTUARIO VARCHAR(10) NOT NULL,
    ORE_FOTO VARCHAR(255) NOT NULL,
    FK_LOGIN_LGN_ID INTEGER,
    FK_CAMPUS_CAM_ID INTEGER
);

CREATE TABLE LOGIN (
    LGN_ID INTEGER AUTO_INCREMENT PRIMARY KEY,
    LGN_SENHA VARCHAR(20) NOT NULL,
    LGN_EMAIL VARCHAR(255) NOT NULL UNIQUE,
    LGN_TIPO ENUM('AD', 'OE', 'SE', 'RE', 'AL') NOT NULL,
    LGN_ATIVO BOOLEAN NOT NULL,
    LGN_JUSTIFICATIVA_RESTRICAO TEXT NOT NULL
);

CREATE TABLE SECRETARIO_EVENTOS (
    SCE_ID INTEGER AUTO_INCREMENT PRIMARY KEY,
    SCE_NOME VARCHAR(80) NOT NULL,
    SCE_NOME_SOCIAL VARCHAR(80) NULL,
    SCE_DATA_NASCIMENTO DATE NOT NULL,
    SCE_CPF VARCHAR(11) NOT NULL UNIQUE,
    SCE_RG VARCHAR(10) NOT NULL,
    SCE_TELEFONE VARCHAR(11) NOT NULL,
    SCE_SEXO ENUM('F', 'M') NOT NULL,
    SCE_ETNIA ENUM('Amarelo', 'Branco', 'Indigena', 'Pardo', 'Preto', 'Sem declaracao') NOT NULL,
    SCE_PRONTUARIO VARCHAR(10) NOT NULL,
    SCE_FOTO VARCHAR(255) NOT NULL,
    FK_LOGIN_LGN_ID INTEGER,
    FK_CAMPUS_CAM_ID INTEGER
);

CREATE TABLE EVENTOS (
    EVO_ID INTEGER AUTO_INCREMENT PRIMARY KEY,
    EVO_NOME VARCHAR(100) NOT NULL,
    EVO_DATA_INICIO DATE NOT NULL,
    EVO_DATA_FIM DATE NOT NULL,
    EVO_STATUS ENUM('Concluido', 'Em andamento', 'Nao Realizado', 'Cancelado') NOT NULL,
    EVO_RESTRICAO_IDADE_MIN INTEGER NOT NULL,
    EVO_RESTRICAO_IDADE_MAX INTEGER NULL,
    EVO_RESTRICAO_GENERO ENUM('F', 'M', 'A') NOT NULL,
    EVO_RESTRICAO_QTD_INSCRICOES_INDIVIDUAIS_MIN INTEGER NOT NULL,
    EVO_RESTRICAO_QTD_INSCRICOES_INDIVIDUAIS_MAX INTEGER NULL,
    EVO_RESTRICAO_QTD_INSCRICOES_COLETIVA_MIN INTEGER NOT NULL,
    EVO_RESTRICAO_QTD_INSCRICOES_COLETIVA_MAX INTEGER NULL,
    EVO_RESTRICAO_OUTRAS VARCHAR(100) NULL,
    FK_ORGANIZADORES_EVENTOS_ORE_ID INTEGER,
    FK_CAMPUS_CAM_ID INTEGER
);

CREATE TABLE MODALIDADES (
    MDE_ID INTEGER AUTO_INCREMENT PRIMARY KEY,
    MDE_NOME VARCHAR(80) NOT NULL,
    MDE_GENERO ENUM('Feminino', 'Masculino') NOT NULL,
    MDE_TIPO ENUM('Coletiva', 'Individual') NOT NULL
);

CREATE TABLE CAMPUS (
    CAM_ID INTEGER AUTO_INCREMENT PRIMARY KEY,
    CAM_NOME VARCHAR(80) NOT NULL,
    CAM_NUMERO VARCHAR(10) NOT NULL,
    CAM_CEP VARCHAR(8) NOT NULL,
    CAM_COMPLEMENTO VARCHAR(30) NULL
);

CREATE TABLE EVENTOS_SECRETARIOS (
    EVS_ID INTEGER AUTO_INCREMENT PRIMARY KEY,
    FK_SECRETARIO_EVENTOS_SCE_ID INTEGER,
    FK_EVENTOS_EVO_ID INTEGER
);

CREATE TABLE EVENTOS_MODALIDADES (
    EVM_ID INTEGER AUTO_INCREMENT PRIMARY KEY,
    MDE_QUANTIDADE_MINIMA_JOGADORES INTEGER NOT NULL,
    MDE_QUANTIDADE_MAXIMA_JOGADORES INTEGER NOT NULL,
    FK_MODALIDADES_MDE_ID INTEGER,
    FK_EVENTOS_EVO_ID INTEGER
);
 
ALTER TABLE ORGANIZADORES_EVENTOS ADD CONSTRAINT FK_ORGANIZADORES_EVENTOS_2
    FOREIGN KEY (FK_LOGIN_LGN_ID)
    REFERENCES LOGIN (LGN_ID)
    ON DELETE CASCADE;
 
ALTER TABLE ORGANIZADORES_EVENTOS ADD CONSTRAINT FK_ORGANIZADORES_EVENTOS_3
    FOREIGN KEY (FK_CAMPUS_CAM_ID)
    REFERENCES CAMPUS (CAM_ID)
    ON DELETE CASCADE;
 
ALTER TABLE SECRETARIO_EVENTOS ADD CONSTRAINT FK_SECRETARIO_EVENTOS_2
    FOREIGN KEY (FK_LOGIN_LGN_ID)
    REFERENCES LOGIN (LGN_ID)
    ON DELETE CASCADE;
 
ALTER TABLE SECRETARIO_EVENTOS ADD CONSTRAINT FK_SECRETARIO_EVENTOS_3
    FOREIGN KEY (FK_CAMPUS_CAM_ID)
    REFERENCES CAMPUS (CAM_ID)
    ON DELETE CASCADE;
 
ALTER TABLE EVENTOS ADD CONSTRAINT FK_EVENTOS_2
    FOREIGN KEY (FK_ORGANIZADORES_EVENTOS_ORE_ID)
    REFERENCES ORGANIZADORES_EVENTOS (ORE_ID)
    ON DELETE CASCADE;
 
ALTER TABLE EVENTOS ADD CONSTRAINT FK_EVENTOS_3
    FOREIGN KEY (FK_CAMPUS_CAM_ID)
    REFERENCES CAMPUS (CAM_ID)
    ON DELETE CASCADE;
 
ALTER TABLE EVENTOS_SECRETARIOS ADD CONSTRAINT FK_EVENTOS_SECRETARIOS_2
    FOREIGN KEY (FK_SECRETARIO_EVENTOS_SCE_ID)
    REFERENCES SECRETARIO_EVENTOS (SCE_ID)
    ON DELETE SET NULL;
 
ALTER TABLE EVENTOS_SECRETARIOS ADD CONSTRAINT FK_EVENTOS_SECRETARIOS_3
    FOREIGN KEY (FK_EVENTOS_EVO_ID)
    REFERENCES EVENTOS (EVO_ID)
    ON DELETE SET NULL;
 
ALTER TABLE EVENTOS_MODALIDADES ADD CONSTRAINT FK_EVENTOS_MODALIDADES_2
    FOREIGN KEY (FK_MODALIDADES_MDE_ID)
    REFERENCES MODALIDADES (MDE_ID)
    ON DELETE SET NULL;
 
ALTER TABLE EVENTOS_MODALIDADES ADD CONSTRAINT FK_EVENTOS_MODALIDADES_3
    FOREIGN KEY (FK_EVENTOS_EVO_ID)
    REFERENCES EVENTOS (EVO_ID)
    ON DELETE SET NULL;