/* Lógico_1: */

CREATE TABLE RECLAMACOES (
    REC_ID INTEGER AUTO_INCREMENT PRIMARY KEY,
    REC_TITULO_RECLAMACAO VARCHAR(200) NOT NULL,
    REC_STATUS ENUM('R','P','A') NOT NULL,
    REC_DESCRICAO TEXT NOT NULL,
    REC_DATAHORA DATETIME NOT NULL,
    REC_ANEXO VARCHAR(255),
    REC_NOTA_AVALIACAO ENUM('1', '2', '3', '4', '5'),
    FK_USUARIOS_USU_ID INTEGER,
    FK_SETORES_SET_ID INTEGER,
    FK_GESTORES_GES_ID INTEGER,
    REC_RESPOSTA_RECLAMACAO TEXT NOT NULL
);

CREATE TABLE SETORES (
    SET_ID INTEGER AUTO_INCREMENT PRIMARY KEY,
    SET_NOME VARCHAR(200) NOT NULL UNIQUE
);

CREATE TABLE USUARIOS (
    USU_ID INTEGER AUTO_INCREMENT PRIMARY KEY
);

CREATE TABLE GESTORES (
    GES_ID INTEGER AUTO_INCREMENT PRIMARY KEY,
    FK_SETORES_SET_ID INTEGER
);
 
ALTER TABLE RECLAMACOES ADD CONSTRAINT FK_RECLAMACOES_2
    FOREIGN KEY (FK_USUARIOS_USU_ID)
    REFERENCES USUARIOS (USU_ID)
    ON DELETE CASCADE;
 
ALTER TABLE RECLAMACOES ADD CONSTRAINT FK_RECLAMACOES_3
    FOREIGN KEY (FK_SETORES_SET_ID)
    REFERENCES SETORES (SET_ID)
    ON DELETE CASCADE;
 
ALTER TABLE RECLAMACOES ADD CONSTRAINT FK_RECLAMACOES_4
    FOREIGN KEY (FK_GESTORES_GES_ID)
    REFERENCES GESTORES (GES_ID)
    ON DELETE CASCADE;
 
ALTER TABLE GESTORES ADD CONSTRAINT FK_GESTORES_2
    FOREIGN KEY (FK_SETORES_SET_ID)
    REFERENCES SETORES (SET_ID)
    ON DELETE RESTRICT;