/* MERLÓGICO_MÓDULO5: */

CREATE TABLE PAGAMENTOS (
    PAG_DATAVENCIMENTO DATE,
    PAG_ID INTEGER PRIMARY KEY,
    PAG_VALORPAGAMENTO DECIMAL(8,2),
    PAG_DATAPAGAMENTO DATE,
    FK_PACIENTES_PAC_ID INTEGER,
    FK_PLANOS_MEDICOS_PLA_ID INTEGER
);

CREATE TABLE CONTATOS_SETORIAIS (
    CON_WHATSAAP VARCHAR(50),
    CON_ID INTEGER PRIMARY KEY,
    CON_TELEFONE VARCHAR(20),
    CON_RESPONSAVEL VARCHAR(50),
    CON_SETOR VARCHAR(50) NOT NULL UNIQUE,
    CON_EMAIL VARCHAR(50)
);

CREATE TABLE PACIENTES (
    PAC_CONDICAO INTEGER NOT NULL,
    PAC_NOME VARCHAR(50) NOT NULL UNIQUE,
    PAC_ID INTEGER PRIMARY KEY,
    PAC_CPF VARCHAR(11) NOT NULL,
    PAC_EMAIL VARCHAR(255),
    FK_PLANOS_MEDICOS_PLA_ID INTEGER
);

CREATE TABLE PLANOS_MEDICOS (
    PLA_QUANTIDADEEXAMES INTEGER,
    PLA_CONTATO VARCHAR(100),
    PLA_PRECO DECIMAL(8,2) NOT NULL,
    PLA_QUANTIDADECONSULTAS INTEGER,
    PLA_ID INTEGER PRIMARY KEY,
    PLA_NOME VARCHAR(50) NOT NULL,
    PLA_AGENCIA VARCHAR(50) NOT NULL,
    UNIQUE (PLA_ID, PLA_NOME)
);

CREATE TABLE CONSULTAS (
    CON_DATA_CONSULTA NOT NULL DATE NOT NULL,
    CON_ID INTEGER PRIMARY KEY,
    FK_PACIENTES_PAC_ID INTEGER,
    FK_MEDICOS_ESPECIALIDADES_MEDICAS_MED_ID INTEGER
);

CREATE TABLE OUVIDORIA (
    OUV_MOTIVO VARCHAR(50),
    OUV_ID INTEGER PRIMARY KEY,
    OUV_RECADO NOT NULL VARCHAR(500) NOT NULL,
    OUV_SITUACAO INTEGER NOT NULL,
    FK_USUARIOS_USU_ID INTEGER
);

CREATE TABLE MEDICOS_ESPECIALIDADES_MEDICAS (
    MED_NOME VARCHAR(50) NOT NULL,
    MED_TELEFONE VARCHAR(9),
    MED_EMAIL NOT NULL VARCHAR(50),
    MED_WHATSAPP VARCHAR(9),
    MED_VALOR_CONSULTA DECIMAL(10,2) NOT NULL,
    MED_FORMACAO VARCHAR(50) NOT NULL,
    MED_ID INTEGER,
    MED_ENDERECO VARCHAR(50),
    MED_OBSERVACOES TEXT,
    ESP_NOME VARCHAR(50) NOT NULL,
    ESP_ID INTEGER,
    PRIMARY KEY (MED_ID, ESP_ID),
    UNIQUE (ESP_NOME, MED_NOME)
);

CREATE TABLE USUARIOS (
    USU_TIPO_USUARIO INTEGER NOT NULL,
    USU_ID INTEGER PRIMARY KEY,
    USU_NOME VARCHAR(100) NOT NULL
);

CREATE TABLE REMEDIOS (
    REM_OBSERVACOES TEXT,
    REM_NOME VARCHAR(50) NOT NULL UNIQUE,
    REM_INDICACAO VARCHAR(200) NOT NULL,
    REM_CONTRAINDICACAO VARCHAR(500) NOT NULL,
    REM_ID INTEGER PRIMARY KEY,
    REM_DOSAGEM VARCHAR(50) NOT NULL,
    FK_TIPOS_REMEDIOS_TIP_ID INTEGER NOT NULL
);

CREATE TABLE TIPOS_REMEDIOS (
    TIP_OBSERVACOES TEXT,
    TIP_NOME VARCHAR(50) NOT NULL UNIQUE,
    TIP_ID INTEGER NOT NULL PRIMARY KEY
);
 
ALTER TABLE PAGAMENTOS ADD CONSTRAINT FK_PAGAMENTOS_2
    FOREIGN KEY (FK_PACIENTES_PAC_ID)
    REFERENCES PACIENTES (PAC_ID)
    ON DELETE CASCADE;
 
ALTER TABLE PAGAMENTOS ADD CONSTRAINT FK_PAGAMENTOS_3
    FOREIGN KEY (FK_PLANOS_MEDICOS_PLA_ID)
    REFERENCES PLANOS_MEDICOS (PLA_ID)
    ON DELETE CASCADE;
 
ALTER TABLE PACIENTES ADD CONSTRAINT FK_PACIENTES_2
    FOREIGN KEY (FK_PLANOS_MEDICOS_PLA_ID)
    REFERENCES PLANOS_MEDICOS (PLA_ID)
    ON DELETE CASCADE;
 
ALTER TABLE CONSULTAS ADD CONSTRAINT FK_CONSULTAS_2
    FOREIGN KEY (FK_PACIENTES_PAC_ID)
    REFERENCES PACIENTES (PAC_ID)
    ON DELETE CASCADE;
 
ALTER TABLE CONSULTAS ADD CONSTRAINT FK_CONSULTAS_3
    FOREIGN KEY (FK_MEDICOS_ESPECIALIDADES_MEDICAS_MED_ID, ???)
    REFERENCES MEDICOS_ESPECIALIDADES_MEDICAS (MED_ID, ???)
    ON DELETE CASCADE;
 
ALTER TABLE OUVIDORIA ADD CONSTRAINT FK_OUVIDORIA_2
    FOREIGN KEY (FK_USUARIOS_USU_ID)
    REFERENCES USUARIOS (USU_ID)
    ON DELETE CASCADE;
 
ALTER TABLE REMEDIOS ADD CONSTRAINT FK_REMEDIOS_2
    FOREIGN KEY (FK_TIPOS_REMEDIOS_TIP_ID)
    REFERENCES TIPOS_REMEDIOS (TIP_ID)
    ON DELETE CASCADE;