-- Geração de Modelo físico
-- Sql ANSI 2003 - brModelo.

CREATE DATABASE RECLAMACAO;
USE RECLAMACAO;

CREATE TABLE CONSUMIDORES (
CON_TELEFONE VARCHAR(16),
CON_ID_CONSUMIDORES INTEGER PRIMARY KEY,
CON_NOME VARCHAR(100)
);

CREATE TABLE AVALIACOES (
AVA_ID_AVALIACAO INTEGER PRIMARY KEY,
AVA_NOTA INT,
AVA_DATA_HORA DATETIME,
AVA_DESCRICAO TEXT,
AVA_MEDIA FLOAT,
CON_ID_CONSUMIDORES INTEGER,
EST_ID_ESTABELECIMENTO INTEGER,
FOREIGN KEY(CON_ID_CONSUMIDORES) REFERENCES CONSUMIDORES (CON_ID_CONSUMIDORES)
);

CREATE TABLE TIPO_RECLAMACOES (
TRC_ID_TIPO_RECLAMACAO INTEGER PRIMARY KEY,
TRC_DESCRICAO VARCHAR(50)
);

CREATE TABLE NOTIFICACOES (
NOT_ID_NOTIFICACAO INTEGER PRIMARY KEY,
NOT_VISUALIZADO BOOLEAN,
REC_ID_RECLAMACAO INTEGER
);

CREATE TABLE MOTIVO_EXCLUSAO_RECLAMACAO (
MEX_DATA DATE,
MEX_MOTIVO_EXCLUSAO TEXT,
MEX_RECLAMACAO_CONSUMIDOR TEXT,
MEX_ID INTEGER PRIMARY KEY,
CON_ID_CONSUMIDORES INTEGER,
FOREIGN KEY(CON_ID_CONSUMIDORES) REFERENCES CONSUMIDORES (CON_ID_CONSUMIDORES)
);

CREATE TABLE RECLAMACOES (
REC_DATA_VISITA DATE,
REC_DATA_HORA DATETIME,
REC_DESCRICAO TEXT,
REC_LINK_IMAGEM VARCHAR(200),
REC_ID_RECLAMACAO INTEGER PRIMARY KEY,
REC_APROVADA BOOLEAN,
REC_TITULO_RECLAMACAO VARCHAR(50),
REC_NOTA INT,
CON_ID_CONSUMIDORES INTEGER,
TRC_ID_TIPO_RECLAMACAO INTEGER,
PDT_TIPO_PRODUTO VARCHAR(50),
PDT_DESCRICAO Varchar(50),
EST_ID_ESTABELECIMENTO INTEGER,
FOREIGN KEY(CON_ID_CONSUMIDORES) REFERENCES CONSUMIDORES (CON_ID_CONSUMIDORES),
FOREIGN KEY(TRC_ID_TIPO_RECLAMACAO) REFERENCES TIPO_RECLAMACOES (TRC_ID_TIPO_RECLAMACAO)
);

CREATE TABLE PRODUTO (
PDT_ID_PRODUTO INTEGER,
PDT_TIPO_PRODUTO VARCHAR(50),
PDT_DESCRICAO Varchar(50),
PRIMARY KEY(PDT_TIPO_PRODUTO,PDT_DESCRICAO)
);

CREATE TABLE ESTABELECIMENTOS (
EST_TOTAL_AVALIACAO INT,
EST_LINK_IMAGEM TEXT,
EST_DATA_RESPOSTA DATETIME,
EST_NOME VARCHAR(50),
EST_TOTAL_RECLAMACAO INT,
EST_NOME_FANTASIA VARCHAR(20),
EST_ID_ESTABELECIMENTO INTEGER PRIMARY KEY AUTO_INCREMENT,
EST_ENDERECO VARCHAR(100),
EST_TELEFONE VARCHAR(16),
EST_FACEBOOK_EMPRESA VARCHAR(50),
EST_LATITUDE_LONGITUDE VARCHAR(20),
EST_MEDIA_AVALIACAO_RECLAMACAO FLOAT,
EST_SITE VARCHAR(20)
);

ALTER TABLE AVALIACOES ADD FOREIGN KEY(EST_ID_ESTABELECIMENTO) REFERENCES ESTABELECIMENTOS (EST_ID_ESTABELECIMENTO);
ALTER TABLE NOTIFICACOES ADD FOREIGN KEY(REC_ID_RECLAMACAO) REFERENCES RECLAMACOES (REC_ID_RECLAMACAO);
ALTER TABLE RECLAMACOES ADD FOREIGN KEY(PDT_DESCRICAO,PDT_TIPO_PRODUTO) REFERENCES PRODUTO (PDT_TIPO_PRODUTO,PDT_DESCRICAO);
ALTER TABLE RECLAMACOES ADD FOREIGN KEY(EST_ID_ESTABELECIMENTO) REFERENCES ESTABELECIMENTOS (EST_ID_ESTABELECIMENTO);
