/* MER_MOD05: */

CREATE TABLE SETORES (
    SET_ID INTEGER AUTO_INCREMENT PRIMARY KEY,
    SET_NOME VARCHAR(125) NOT NULL,
    SET_DATA_CRIACAO DATE,
    SET_DESCRICAO_SERVICOS TEXT
);

CREATE TABLE USUARIOS (
    USU_ID INTEGER AUTO_INCREMENT PRIMARY KEY
);

CREATE TABLE DENUNCIAS (
    DEN_ID INTEGER AUTO_INCREMENT PRIMARY KEY,
    DEN_TITULO VARCHAR(100) NOT NULL,
    DEN_PONTO_REFERENCIA VARCHAR(100),
    DEN_DESCRICAO TEXT,
    DEN_DATA_POSTAGEM DATE NOT NULL,
    FK_USUARIOS_USU_ID INTEGER
);

CREATE TABLE PUNICOES (
    PUN_ID INTEGER AUTO_INCREMENT PRIMARY KEY,
    PUN_OUTRO TEXT,
    PUN_MOTIVO ENUM('PALAVRA PERJORATIVA','ÓDIO GRATUITO','OUTROS') NOT NULL,
    PUN_TEMPO ENUM('24H','7 DIAS','1 MÊS','BANIMENTO DEFINITIVO') NOT NULL
);

CREATE TABLE SANEAMENTOS (
    SAN_ID INTEGER AUTO_INCREMENT PRIMARY KEY,
    SAN_NOME VARCHAR(100) NOT NULL,
    SAN_DATA_CRIACAO DATE NOT NULL,
    SAN_TIPO_SANEAMENTO VARCHAR(125) NOT NULL,
    FK_SETORES_SET_ID INTEGER
);

CREATE TABLE RESPONSAVEIS (
    RES_ID INTEGER AUTO_INCREMENT PRIMARY KEY,
    RES_NOME_FUNCIONARIO VARCHAR(125) NOT NULL,
    RES_DATA_NASCIMENTO DATE NOT NULL,
    FK_SETORES_SET_ID INTEGER
);

CREATE TABLE VIOLACOES (
    VIO_DESCRICAO TEXT,
    VIO_IMAGEM VARCHAR(255),
    FK_USUARIOS_USU_ID INTEGER,
    VIO_ID INTEGER AUTO_INCREMENT PRIMARY KEY
);
 
ALTER TABLE DENUNCIAS ADD CONSTRAINT FK_DENUNCIAS_2
    FOREIGN KEY (FK_USUARIOS_USU_ID)
    REFERENCES USUARIOS (USU_ID)
    ON DELETE CASCADE;
 
ALTER TABLE SANEAMENTOS ADD CONSTRAINT FK_SANEAMENTOS_2
    FOREIGN KEY (FK_SETORES_SET_ID)
    REFERENCES SETORES (SET_ID)
    ON DELETE CASCADE;
 
ALTER TABLE RESPONSAVEIS ADD CONSTRAINT FK_RESPONSAVEIS_2
    FOREIGN KEY (FK_SETORES_SET_ID)
    REFERENCES SETORES (SET_ID)
    ON DELETE RESTRICT;
 
ALTER TABLE VIOLACOES ADD CONSTRAINT FK_VIOLACOES_1
    FOREIGN KEY (FK_USUARIOS_USU_ID)
    REFERENCES USUARIOS (USU_ID)
    ON DELETE CASCADE;