/* DER v1.1: */

CREATE TABLE PROCESSOS_DE_CERVEJA (
    PRO_ID INTEGER PRIMARY KEY,
    PRO_DATA DATETIME NOT NULL,
    PRO_IBU INTEGER NOT NULL,
    PRO_ABV DECIMAL(4,2) NOT NULL,
    PRO_COR INTEGER NOT NULL,
    PRO_FG INTEGER NOT NULL,
    PRO_OG INTEGER NOT NULL,
    REC_CODIGO INTEGER NOT NULL,
    FK_RECEITAS_CERVEJA_REC_ID INTEGER
);

CREATE TABLE USUARIOS (
    USU_ID INTEGER PRIMARY KEY,
    USU_TIPO INTEGER NOT NULL
);

CREATE TABLE CALCULOS_QUANTIDADE_DE_GARRAFAS (
    GAR_ID INTEGER PRIMARY KEY,
    GAR_QUANTIDADE INTEGER NOT NULL,
    GAR_VOLUME DECIMAL(5,2) NOT NULL,
    FK_PROCESSOS_DE_CERVEJA_PRO_ID INTEGER
);

CREATE TABLE PROCESSOS_BRASSAGEM (
    BRA_ID INTEGER PRIMARY KEY,
    BRA_VOLUME_INICIAL INTEGER NOT NULL,
    BRA_TEMPO INTEGER NOT NULL,
    BRA_VOLUME_LAVAGEM INTEGER NOT NULL,
    BRA_TEMPERATURA_LAVAGEM DECIMAL(5,2) NOT NULL,
    BRA_TEMPERATURA_BRASSAGEM DECIMAL(5,2) NOT NULL,
    BRA_TEMPERATURA_INICIAL DECIMAL(5,2) NOT NULL,
    BRA_OBSERVACOES TEXT NOT NULL,
    BRA_TESTE_IODO INTEGER NOT NULL,
    FK_PROCESSOS_DE_CERVEJA_PRO_ID INTEGER
);

CREATE TABLE PROCESSOS_FERVURA (
    FRV_ID INTEGER PRIMARY KEY,
    FRV_DENSIDADE_PRE_BRIX INTEGER NOT NULL,
    FRV_INGREDIENTES_TEMPO INTEGER NOT NULL,
    FRV_INGREDIENTES_INGREDIENTES VARCHAR(30) NOT NULL,
    FRV_INGREDIENTES_QUANTIDADE INTEGER NOT NULL,
    FRV_TEMPO INTEGER NOT NULL,
    FRV_DENSIDADE_PRE_SG INTEGER NOT NULL,
    FRV_VOLUME INTEGER NOT NULL,
    FRV_OBSERVACOES TEXT NOT NULL,
    FK_PROCESSOS_DE_CERVEJA_PRO_ID INTEGER
);

CREATE TABLE PROCESSOS_FERMENTACAO (
    FRM_ID INTEGER PRIMARY KEY,
    FRM_SG INTEGER NOT NULL,
    FRM_BRIX DECIMAL(4,2) NOT NULL,
    FRM_LEVEDURAS_TEMPO INTEGER NOT NULL,
    FRM_LEVEDURAS_QUANTIDADE INTEGER NOT NULL,
    FRM_LEVEDURAS_TIPO VARCHAR(100) NOT NULL,
    FMR_OBSERVACOES TEXT NOT NULL,
    FRM_TEMPO INTEGER NOT NULL,
    FRM_TEMPERATURA DECIMAL(5,2) NOT NULL,
    FK_PROCESSOS_DE_CERVEJA_PRO_ID INTEGER
);

CREATE TABLE PROCESSOS_MATURACAO (
    MAT_ID INTEGER PRIMARY KEY,
    MAT_TEMPERATURA DECIMAL(5,2) NOT NULL,
    MAT_OBSERVACOES TEXT NOT NULL,
    MAT_TEMPO INTEGER NOT NULL,
    FK_PROCESSOS_DE_CERVEJA_PRO_ID INTEGER
);

CREATE TABLE PROCESSOS_ENVASE (
    ENV_ID INTEGER PRIMARY KEY,
    ENV_ACUCAR DECIMAL(5,2) NOT NULL,
    ENV_ESPERA INTEGER NOT NULL,
    ENV_TEMPERATURA DECIMAL(5,2) NOT NULL,
    ENV_OBSERVACOES TEXT NOT NULL,
    FK_PROCESSOS_DE_CERVEJA_PRO_ID INTEGER
);

CREATE TABLE RECEITAS_CERVEJA (
    REC_NOME VARCHAR(50) NOT NULL,
    REC_ID INTEGER PRIMARY KEY,
    REC_NOME_CRIADOR VARCHAR(50) NOT NULL,
    REC_HARMONIZACAO VARCHAR(50)
);

CREATE TABLE USUARIOS_RECEITAS (
    FK_USUARIOS_USU_ID INTEGER,
    FK_RECEITAS_CERVEJA_REC_ID INTEGER,
    USR_ID INTEGER PRIMARY KEY
);
 
ALTER TABLE PROCESSOS_DE_CERVEJA ADD CONSTRAINT FK_PROCESSOS_DE_CERVEJA_2
    FOREIGN KEY (FK_RECEITAS_CERVEJA_REC_ID)
    REFERENCES RECEITAS_CERVEJA (REC_ID)
    ON DELETE CASCADE;
 
ALTER TABLE PROCESSOS_BRASSAGEM ADD CONSTRAINT FK_PROCESSOS_BRASSAGEM_2
    FOREIGN KEY (FK_PROCESSOS_DE_CERVEJA_PRO_ID)
    REFERENCES PROCESSOS_DE_CERVEJA (PRO_ID)
    ON DELETE CASCADE;
 
ALTER TABLE PROCESSOS_FERVURA ADD CONSTRAINT FK_PROCESSOS_FERVURA_2
    FOREIGN KEY (FK_PROCESSOS_DE_CERVEJA_PRO_ID)
    REFERENCES PROCESSOS_DE_CERVEJA (PRO_ID)
    ON DELETE CASCADE;
 
ALTER TABLE PROCESSOS_FERMENTACAO ADD CONSTRAINT FK_PROCESSOS_FERMENTACAO_2
    FOREIGN KEY (FK_PROCESSOS_DE_CERVEJA_PRO_ID)
    REFERENCES PROCESSOS_DE_CERVEJA (PRO_ID)
    ON DELETE CASCADE;
 
ALTER TABLE PROCESSOS_MATURACAO ADD CONSTRAINT FK_PROCESSOS_MATURACAO_2
    FOREIGN KEY (FK_PROCESSOS_DE_CERVEJA_PRO_ID)
    REFERENCES PROCESSOS_DE_CERVEJA (PRO_ID)
    ON DELETE CASCADE;
 
ALTER TABLE PROCESSOS_ENVASE ADD CONSTRAINT FK_PROCESSOS_ENVASE_2
    FOREIGN KEY (FK_PROCESSOS_DE_CERVEJA_PRO_ID)
    REFERENCES PROCESSOS_DE_CERVEJA (PRO_ID)
    ON DELETE CASCADE;
 
ALTER TABLE CALCULOS_QUANTIDADE_DE_GARRAFAS ADD CONSTRAINT FK_CALCULOS_QUANTIDADE_DE_GARRAFAS_2
    FOREIGN KEY (FK_PROCESSOS_DE_CERVEJA_PRO_ID)
    REFERENCES PROCESSOS_DE_CERVEJA (PRO_ID)
    ON DELETE CASCADE;
 
ALTER TABLE USUARIOS_RECEITAS ADD CONSTRAINT FK_USUARIOS_RECEITAS_2
    FOREIGN KEY (FK_USUARIOS_USU_ID)
    REFERENCES USUARIOS (USU_ID)
    ON DELETE SET NULL;
 
ALTER TABLE USUARIOS_RECEITAS ADD CONSTRAINT FK_USUARIOS_RECEITAS_3
    FOREIGN KEY (FK_RECEITAS_CERVEJA_REC_ID)
    REFERENCES RECEITAS_CERVEJA (REC_ID)
    ON DELETE SET NULL;