/* Lógico_1: */

CREATE TABLE PATOLOGIAS (
    PAT_NOME VARCHAR(100),
    PAT_SINTOMAS VARCHAR(500),
    PAT_TRATAMENTO VARCHAR(500),
    PAT_PREVENCAO VARCHAR(100),
    PAT_ID INTEGER PRIMARY KEY,
    FK_TIPO_PATOLOGIA_TIPO_PAT_ID INTEGER
);

CREATE TABLE MEDICAMENTOS (
    MED_NOME_QUIMICO VARCHAR(100),
    MED_LABORATORIO VARCHAR(50),
    MED_ID INTEGER PRIMARY KEY,
    MED_NOME_COMERCIAL VARCHAR(100),
    FK_TIPOS_MEDICAMENTOS_TIPO_ID INTEGER,
    FK_VIA_MEDICAMENTOS_VIA_ID INTEGER,
    FK_TARJA_MEDICAMENTOS_TARJA_ID INTEGER,
    FK_FUNCAO_MEDICAMENTOS_FUNCAO_ID INTEGER,
    FK_LABORATORIOS_LAB_ID INTEGER
);

CREATE TABLE TIPO_PATOLOGIA (
    TIPO_PAT_ID INTEGER PRIMARY KEY,
    TIPO_PAT_DESCRICAO VARCHAR(50)
);

CREATE TABLE VIA_MEDICAMENTOS (
    VIA_ID INTEGER PRIMARY KEY,
    VIA_DESCRICAO VARCHAR(50)
);

CREATE TABLE VACINAS (
    VAC_COMPOSICAO VARCHAR(100),
    VAC_ID INTEGER PRIMARY KEY,
    VAC_OBSERVACOES VARCHAR(500),
    VAC_NOME_COMERCIAL VARCHAR(100),
    VAC_NOME_QUIMICO VARCHAR(100),
    FK_VACINA_PERIODICIDADE_VAC_TEM_ID INTEGER,
    FK_LABORATORIOS_LAB_ID INTEGER
);

CREATE TABLE TIPOS_MEDICAMENTOS (
    TIPO_DESCRICAO VARCHAR(50),
    TIPO_ID INTEGER PRIMARY KEY
);

CREATE TABLE TARJA_MEDICAMENTOS (
    TARJA_ID INTEGER PRIMARY KEY,
    TARJA_DESCRICAO VARCHAR(50)
);

CREATE TABLE FUNCAO_MEDICAMENTOS (
    FUNCAO_ID INTEGER PRIMARY KEY,
    FUNCAO_DESCRICAO VARCHAR(50)
);

CREATE TABLE VACINA_FUNCAO (
    VAC_FUN_DESCRICAO VARCHAR(50),
    VAC_FUN_ID INTEGER PRIMARY KEY
);

CREATE TABLE VACINA_PERIODICIDADE (
    VAC_TEM_ID INTEGER PRIMARY KEY,
    VAC_TEM_DESCRICAO VARCHAR(20)
);

CREATE TABLE IDOSOS (
    IDOSO_ID INTEGER PRIMARY KEY,
    IDOSO_NOME VARCHAR(100)
);

CREATE TABLE USUARIOS (
    USUARIOS_TIPO INT
);

CREATE TABLE _PATOLOGIAS_IDOSO (
    PAT_IDO_DATA_HORA DATETIME,
    PAT_IDO_OBSERVACOES VARCHAR(500),
    PAT_IDO_ID INTEGER PRIMARY KEY,
    FK_GRAU_PATOLOGIA_GRAU_ID INTEGER,
    FK_IDOSOS_IDOSO_ID INTEGER,
    FK_PATOLOGIAS_PAT_ID INTEGER
);

CREATE TABLE _VACINAS_IDOSO (
    VAC_IDO_DATA_HORA DATETIME,
    VAC_IDO_DOSE FLOAT,
    VAC_IDO_OBSERVACOES VARCHAR(500),
    VAC_IDO_ID INTEGER PRIMARY KEY,
    FK_IDOSOS_IDOSO_ID INTEGER,
    FK_VACINAS_VAC_ID INTEGER
);

CREATE TABLE _PRESCRICOES_MEDICAS (
    PRE_MED_IDO_HORA_DATA DATETIME,
    PRE_MED_IDO_POSOLOGIA VARCHAR(200),
    PRE_MED_IDO_VALIDADE_PRESCRICAO VARCHAR(20),
    PRE_MED_IDO_ID INTEGER PRIMARY KEY,
    PRE_MED_IDO_OBSERVACOES VARCHAR(500),
    FK_IDOSOS_IDOSO_ID INTEGER,
    FK_MEDICAMENTOS_MED_ID INTEGER
);

CREATE TABLE TIPOS_ANALISE_CLINICA (
    ANC_TIPO_ID INTEGER PRIMARY KEY,
    ANC_TIPO_DESCRICAO VARCHAR(20)
);

CREATE TABLE INCIDENTES_IDOSOS (
    INC_ID INTEGER PRIMARY KEY,
    INC_DATA_HORA DATETIME,
    INC_OBSERVACOES VARCHAR(500),
    FK_TIPO_INCIDENTE_TIPO_INC_ID INTEGER,
    FK_IDOSOS_IDOSO_ID INTEGER
);

CREATE TABLE TIPO_INCIDENTE (
    ITIPO_INC_DESCRICAO VARCHAR(50),
    TIPO_INC_ID INTEGER PRIMARY KEY
);

CREATE TABLE LABORATORIOS (
    LAB_DESCRICAO VARCHAR(500),
    LAB_ID INTEGER PRIMARY KEY
);

CREATE TABLE ANALISES_CLINICAS (
    ANC_ID INTEGER PRIMARY KEY,
    ANC_DATA_HORA DATETIME,
    ANC_SINTOMAS VARCHAR(500),
    ANC_OBSERVACOES VARCHAR(500),
    ANC_PESO FLOAT,
    ANC_ALTURA INTEGER,
    FK_IDOSOS_IDOSO_ID INTEGER,
    FK_TIPOS_ANALISE_CLINICA_ANC_TIPO_ID INTEGER,
    FK_PATOLOGIAS_PAT_ID INTEGER
);

CREATE TABLE GRAU_PATOLOGIA (
    GRAU_ID INTEGER PRIMARY KEY,
    GRAU_DESCRICAO VARCHAR(50)
);

CREATE TABLE VACINAS_FUNCOES (
    FK_VACINA_FUNCAO_VAC_FUN_ID INTEGER,
    FK_VACINAS_VAC_ID INTEGER,
    VAF_ID INTEGER PRIMARY KEY
);
 
ALTER TABLE PATOLOGIAS ADD CONSTRAINT FK_PATOLOGIAS_2
    FOREIGN KEY (FK_TIPO_PATOLOGIA_TIPO_PAT_ID)
    REFERENCES TIPO_PATOLOGIA (TIPO_PAT_ID)
    ON DELETE CASCADE;
 
ALTER TABLE MEDICAMENTOS ADD CONSTRAINT FK_MEDICAMENTOS_2
    FOREIGN KEY (FK_TIPOS_MEDICAMENTOS_TIPO_ID)
    REFERENCES TIPOS_MEDICAMENTOS (TIPO_ID)
    ON DELETE CASCADE;
 
ALTER TABLE MEDICAMENTOS ADD CONSTRAINT FK_MEDICAMENTOS_3
    FOREIGN KEY (FK_VIA_MEDICAMENTOS_VIA_ID)
    REFERENCES VIA_MEDICAMENTOS (VIA_ID)
    ON DELETE CASCADE;
 
ALTER TABLE MEDICAMENTOS ADD CONSTRAINT FK_MEDICAMENTOS_4
    FOREIGN KEY (FK_TARJA_MEDICAMENTOS_TARJA_ID)
    REFERENCES TARJA_MEDICAMENTOS (TARJA_ID)
    ON DELETE CASCADE;
 
ALTER TABLE MEDICAMENTOS ADD CONSTRAINT FK_MEDICAMENTOS_5
    FOREIGN KEY (FK_FUNCAO_MEDICAMENTOS_FUNCAO_ID)
    REFERENCES FUNCAO_MEDICAMENTOS (FUNCAO_ID)
    ON DELETE CASCADE;
 
ALTER TABLE MEDICAMENTOS ADD CONSTRAINT FK_MEDICAMENTOS_6
    FOREIGN KEY (FK_LABORATORIOS_LAB_ID)
    REFERENCES LABORATORIOS (LAB_ID)
    ON DELETE CASCADE;
 
ALTER TABLE VACINAS ADD CONSTRAINT FK_VACINAS_2
    FOREIGN KEY (FK_VACINA_PERIODICIDADE_VAC_TEM_ID)
    REFERENCES VACINA_PERIODICIDADE (VAC_TEM_ID)
    ON DELETE CASCADE;
 
ALTER TABLE VACINAS ADD CONSTRAINT FK_VACINAS_3
    FOREIGN KEY (FK_LABORATORIOS_LAB_ID)
    REFERENCES LABORATORIOS (LAB_ID)
    ON DELETE CASCADE;
 
ALTER TABLE _PATOLOGIAS_IDOSO ADD CONSTRAINT FK__PATOLOGIAS_IDOSO_2
    FOREIGN KEY (FK_GRAU_PATOLOGIA_GRAU_ID)
    REFERENCES GRAU_PATOLOGIA (GRAU_ID)
    ON DELETE CASCADE;
 
ALTER TABLE _PATOLOGIAS_IDOSO ADD CONSTRAINT FK__PATOLOGIAS_IDOSO_3
    FOREIGN KEY (FK_IDOSOS_IDOSO_ID)
    REFERENCES IDOSOS (IDOSO_ID);
 
ALTER TABLE _PATOLOGIAS_IDOSO ADD CONSTRAINT FK__PATOLOGIAS_IDOSO_4
    FOREIGN KEY (FK_PATOLOGIAS_PAT_ID)
    REFERENCES PATOLOGIAS (PAT_ID);
 
ALTER TABLE _VACINAS_IDOSO ADD CONSTRAINT FK__VACINAS_IDOSO_2
    FOREIGN KEY (FK_IDOSOS_IDOSO_ID)
    REFERENCES IDOSOS (IDOSO_ID);
 
ALTER TABLE _VACINAS_IDOSO ADD CONSTRAINT FK__VACINAS_IDOSO_3
    FOREIGN KEY (FK_VACINAS_VAC_ID)
    REFERENCES VACINAS (VAC_ID);
 
ALTER TABLE _PRESCRICOES_MEDICAS ADD CONSTRAINT FK__PRESCRICOES_MEDICAS_2
    FOREIGN KEY (FK_IDOSOS_IDOSO_ID)
    REFERENCES IDOSOS (IDOSO_ID);
 
ALTER TABLE _PRESCRICOES_MEDICAS ADD CONSTRAINT FK__PRESCRICOES_MEDICAS_3
    FOREIGN KEY (FK_MEDICAMENTOS_MED_ID)
    REFERENCES MEDICAMENTOS (MED_ID);
 
ALTER TABLE INCIDENTES_IDOSOS ADD CONSTRAINT FK_INCIDENTES_IDOSOS_2
    FOREIGN KEY (FK_TIPO_INCIDENTE_TIPO_INC_ID)
    REFERENCES TIPO_INCIDENTE (TIPO_INC_ID)
    ON DELETE CASCADE;
 
ALTER TABLE INCIDENTES_IDOSOS ADD CONSTRAINT FK_INCIDENTES_IDOSOS_3
    FOREIGN KEY (FK_IDOSOS_IDOSO_ID)
    REFERENCES IDOSOS (IDOSO_ID)
    ON DELETE CASCADE;
 
ALTER TABLE ANALISES_CLINICAS ADD CONSTRAINT FK_ANALISES_CLINICAS_2
    FOREIGN KEY (FK_IDOSOS_IDOSO_ID)
    REFERENCES IDOSOS (IDOSO_ID)
    ON DELETE CASCADE;
 
ALTER TABLE ANALISES_CLINICAS ADD CONSTRAINT FK_ANALISES_CLINICAS_3
    FOREIGN KEY (FK_TIPOS_ANALISE_CLINICA_ANC_TIPO_ID)
    REFERENCES TIPOS_ANALISE_CLINICA (ANC_TIPO_ID)
    ON DELETE CASCADE;
 
ALTER TABLE ANALISES_CLINICAS ADD CONSTRAINT FK_ANALISES_CLINICAS_4
    FOREIGN KEY (FK_PATOLOGIAS_PAT_ID)
    REFERENCES PATOLOGIAS (PAT_ID)
    ON DELETE CASCADE;
 
ALTER TABLE VACINAS_FUNCOES ADD CONSTRAINT FK_VACINAS_FUNCOES_2
    FOREIGN KEY (FK_VACINA_FUNCAO_VAC_FUN_ID)
    REFERENCES VACINA_FUNCAO (VAC_FUN_ID)
    ON DELETE RESTRICT;
 
ALTER TABLE VACINAS_FUNCOES ADD CONSTRAINT FK_VACINAS_FUNCOES_3
    FOREIGN KEY (FK_VACINAS_VAC_ID)
    REFERENCES VACINAS (VAC_ID)
    ON DELETE SET NULL;