/* Lógico_2: */

CREATE TABLE USUARIOS (
    USU_ID INTEGER PRIMARY KEY,
    USU_CPF VARCHAR(12) NOT NULL UNIQUE,
    USU_RG VARCHAR(9) NOT NULL,
    USU_EMAIL VARCHAR(225) NOT NULL UNIQUE,
    USU_SENHA VARCHAR(225) NOT NULL,
    USU_NUMERO_CELULAR VARCHAR(12) NOT NULL,
    USU_TELEFONE VARCHAR(13),
    USU_DATA_DE_NASCIMENTO DATE NOT NULL,
    USU_NOME VARCHAR(255) NOT NULL,
    USU_NUMERO_RESIDENCIA VARCHAR(4) NOT NULL,
    USU_SEXO ENUM('M','F','O') NOT NULL,
    USU_CEP VARCHAR(8) NOT NULL,
    USU_COMPLEMENTO VARCHAR(255),
    USU_FOTO VARCHAR(255),
    USU_ATIVO BOOLEAN
);

CREATE TABLE PACIENTES (
    PAC_ID INTEGER,
    FK_USUARIOS_USU_ID INTEGER,
    FK_PLANOS_PLA_ID INTEGER,
    PRIMARY KEY (PAC_ID, FK_USUARIOS_USU_ID)
);

CREATE TABLE ENFERMEIROS (
    ENF_EMAIL_PROFISSIONAL VARCHAR(255) NOT NULL,
    ENF_ID INTEGER,
    ENF_TELEFONE_PROFISSIONAL VARCHAR(13) NOT NULL,
    ENF_COREN VARCHAR(255) NOT NULL UNIQUE,
    ENF_PRONTUARIO VARCHAR(6) NOT NULL UNIQUE,
    FK_USUARIOS_USU_ID INTEGER,
    PRIMARY KEY (ENF_ID, FK_USUARIOS_USU_ID)
);

CREATE TABLE MEDICOS (
    MED_ID INTEGER,
    MED_CRM VARCHAR(6) NOT NULL UNIQUE,
    MED_TELEFONE_PROFISSIONAL VARCHAR(13) NOT NULL,
    MED_EMAIL_PROFISSIONAL VARCHAR(255) NOT NULL,
    MED_ESPECIALIZACAO VARCHAR(255) NOT NULL,
    MED_PRONTUARIO VARCHAR(6) NOT NULL UNIQUE,
    FK_USUARIOS_USU_ID INTEGER,
    PRIMARY KEY (MED_ID, FK_USUARIOS_USU_ID)
);

CREATE TABLE SECRETARIAS (
    SEC_SETOR VARCHAR(50) NOT NULL,
    SEC_EMAIL_PROFISSIONAL VARCHAR(255) NOT NULL,
    SEC_TELEFONE_PROFISSIONAL VARCHAR(13) NOT NULL,
    SEC_PRONTUARIO VARCHAR(6) NOT NULL UNIQUE,
    FK_USUARIOS_USU_ID INTEGER PRIMARY KEY
);

CREATE TABLE ADMINISTRADORES (
    ADM_TELEFONE_PROFISSIONAL VARCHAR(13) NOT NULL,
    ADM_EMAIL_PROFISSIONAL VARCHAR(255) NOT NULL,
    ADM_ID INTEGER,
    ADM_PRONTUARIO VARCHAR(6) NOT NULL UNIQUE,
    FK_USUARIOS_USU_ID INTEGER,
    PRIMARY KEY (ADM_ID, FK_USUARIOS_USU_ID)
);

CREATE TABLE PLANOS (
    PLA_ID INTEGER PRIMARY KEY,
    PLA_NOME VARCHAR(255) NOT NULL
);

CREATE TABLE DEPENDENTES_PACIENTES (
    DEP_ID INTEGER PRIMARY KEY,
    FK_PACIENTES_PAC_ID INTEGER,
    FK_PACIENTES_FK_USUARIOS_USU_ID INTEGER
);
 
ALTER TABLE PACIENTES ADD CONSTRAINT FK_PACIENTES_2
    FOREIGN KEY (FK_USUARIOS_USU_ID)
    REFERENCES USUARIOS (USU_ID)
    ON DELETE CASCADE;
 
ALTER TABLE PACIENTES ADD CONSTRAINT FK_PACIENTES_3
    FOREIGN KEY (FK_PLANOS_PLA_ID)
    REFERENCES PLANOS (PLA_ID)
    ON DELETE RESTRICT;
 
ALTER TABLE ENFERMEIROS ADD CONSTRAINT FK_ENFERMEIROS_2
    FOREIGN KEY (FK_USUARIOS_USU_ID)
    REFERENCES USUARIOS (USU_ID)
    ON DELETE CASCADE;
 
ALTER TABLE MEDICOS ADD CONSTRAINT FK_MEDICOS_2
    FOREIGN KEY (FK_USUARIOS_USU_ID)
    REFERENCES USUARIOS (USU_ID)
    ON DELETE CASCADE;
 
ALTER TABLE SECRETARIAS ADD CONSTRAINT FK_SECRETARIAS_2
    FOREIGN KEY (FK_USUARIOS_USU_ID)
    REFERENCES USUARIOS (USU_ID)
    ON DELETE CASCADE;
 
ALTER TABLE ADMINISTRADORES ADD CONSTRAINT FK_ADMINISTRADORES_2
    FOREIGN KEY (FK_USUARIOS_USU_ID)
    REFERENCES USUARIOS (USU_ID)
    ON DELETE CASCADE;
 
ALTER TABLE DEPENDENTES_PACIENTES ADD CONSTRAINT FK_DEPENDENTES_PACIENTES_2
    FOREIGN KEY (FK_PACIENTES_PAC_ID, FK_PACIENTES_FK_USUARIOS_USU_ID)
    REFERENCES PACIENTES (PAC_ID, FK_USUARIOS_USU_ID)
    ON DELETE CASCADE;