-- Geração de Modelo físico
-- Sql ANSI 2003 - brModelo.



CREATE TABLE FICHAS_TREINAMENTO (
FTR_CODIGO INTEGER AUTO_INCREMENT PRIMARY KEY,
FTR_DESCRICAO_PRINCIPAIS_EXERCICIOS VARCHAR(150) NOT NULL,
FTR_DATA_INICIO DATE NOT NULL,
FTR_DATA_ULTIMA_ATUALIZACAO DATE NOT NULL,
FTR_DATA_TERMINO DATE NOT NULL,
USU_CODIGO INTEGER NOT NULL
)

CREATE TABLE USUARIOS (
USU_CODIGO INTEGER AUTO_INCREMENT PRIMARY KEY
)

CREATE TABLE TAXAS_GORDURA (
TGU_CODIGO INTEGER AUTO_INCREMENT PRIMARY KEY,
TGU_DATA_MEDICAO DATE NOT NULL,
TGU_VALOR VARCHAR (30) NOT NULL,
USU_CODIGO INTEGER NOT NULL,
FOREIGN KEY(USU_CODIGO) REFERENCES USUARIOS (USU_CODIGO)
)

CREATE TABLE EXERCICIOS_DAS_FICHAS_TREINAMENTO (
EFT_CODIGO INTEGER AUTO_INCREMENT PRIMARY KEY,
EFT_TEMPO_REPETICAO DECIMAL(10,2) NOT NULL,
EFT_QTD_SERIES INTEGER NOT NULL,
EFS_CODIGO INTEGER NOT NULL,
FTR_CODIGO INTEGER NOT NULL,
FOREIGN KEY(FTR_CODIGO) REFERENCES FICHAS_TREINAMENTO (FTR_CODIGO)
)

CREATE TABLE DESEMPENHO_EXERCICIOS_FISICOS (
DEF_CODIGO INTEGER AUTO_INCREMENT PRIMARY KEY,
DEF_DT_ATUALIZACAO DATE NOT NULL,
DEF_PESO_TEMPO DECIMAL(10,2) NOT NULL,
EFT_CODIGO INTEGER NOT NULL,
FOREIGN KEY(EFT_CODIGO) REFERENCES EXERCICIOS_DAS_FICHAS_TREINAMENTO (EFT_CODIGO)
)

CREATE TABLE EXERCICIOS_DOS_PROGRAMAS_TREINAMENTO (
EPT_CODIGO INTEGER AUTO_INCREMENT PRIMARY KEY,
EPT_TEMPO_REPETICAO DECIMAL(10,2) NOT NULL,
EPT_QTD_SERIES INTEGER NOT NULL,
EFS_CODIGO INTEGER NOT NULL,
PTP_CODIGO INTEGER NOT NULL
)

CREATE TABLE EXERCICIOS_FISICOS (
EFS_NOME VARCHAR(30) UNIQUE NOT NULL,
EFS_CODIGO INTEGER AUTO_INCREMENT PRIMARY KEY
)

CREATE TABLE DESEMPENHO_PROGRAMAS_TREINAMENTO (
DPT_PESO VARCHAR(30) NOT NULL,
DPT_DT_ATUALIZACAO DATE NOT NULL,
DPT_CODIGO INTEGER AUTO_INCREMENT PRIMARY KEY,
EPT_CODIGO INTEGER NOT NULL,
FOREIGN KEY(EPT_CODIGO) REFERENCES EXERCICIOS_DOS_PROGRAMAS_TREINAMENTO (EPT_CODIGO)
)

CREATE TABLE MEDIDAS_CORPORAIS (
MEC_CODIGO INTEGER AUTO_INCREMENT PRIMARY KEY,
MEC_NOME VARCHAR (30)
)

CREATE TABLE GASTOS_CALORICOS (
HGC_DT_REGISTRO DATE NOT NULL,
HGC_GASTO VARCHAR(30) AUTO_INCREMENT,
HGC_CODIGO INTEGER AUTO_INCREMENT PRIMARY KEY,
EFS_CODIGO INTEGER NOT NULL,
USU_CODIGO INTEGER NOT NULL,
FOREIGN KEY(EFS_CODIGO) REFERENCES EXERCICIOS_FISICOS (EFS_CODIGO),
FOREIGN KEY(USU_CODIGO) REFERENCES USUARIOS (USU_CODIGO)
)

CREATE TABLE GRUPOS_MUSCULARES (
GRM_CODIGO INTEGER AUTO_INCREMENT PRIMARY KEY,
GRM_NOME VARCHAR(30) UNIQUE NOT NULL
)

CREATE TABLE EXERCICIOS_GRUPOS_MUSCULARES (
EGM_CODIGO INTEGER AUTO_INCREMENT PRIMARY KEY,
EFS_CODIGO INTEGER NOT NULL,
GRM_CODIGO INTEGER NOT NULL,
FOREIGN KEY(EFS_CODIGO) REFERENCES EXERCICIOS_FISICOS (EFS_CODIGO),
FOREIGN KEY(GRM_CODIGO) REFERENCES GRUPOS_MUSCULARES (GRM_CODIGO)
)

CREATE TABLE DOBRAS_CUTANEAS_USUARIOS (
DCU_CODIGO INTEGER AUTO_INCREMENT PRIMARY KEY,
DCU_DATA_MEDICAO DATE NOT NULL,
DCU_VALOR DECIMAL(10,2) NOT NULL,
USU_CODIGO INTEGER NOT NULL,
DBC_CODIGO INTEGER NOT NULL,
FOREIGN KEY(USU_CODIGO) REFERENCES USUARIOS (USU_CODIGO)
)

CREATE TABLE MEDIDAS_CORPORAIS_USUARIO (
MCU_VALOR DECIMAL(10,2) NOT NULL,
MCU_CODIGO INTEGER AUTO_INCREMENT PRIMARY KEY,
MCU_DATA_MEDICAO DATE NOT NULL,
USU_CODIGO INTEGER NOT NULL,
MEC_CODIGO INTEGER NOT NULL,
FOREIGN KEY(USU_CODIGO) REFERENCES USUARIOS (USU_CODIGO),
FOREIGN KEY(MEC_CODIGO) REFERENCES MEDIDAS_CORPORAIS (MEC_CODIGO)
)

CREATE TABLE DOBRAS_CUTANEAS (
DBC_CODIGO INTEGER AUTO_INCREMENT PRIMARY KEY,
DBC_NOME VARCHAR(30) NOT NULL
)

CREATE TABLE USUARIO_TREINAMENTOS_PRONTOS (
USU_CODIGO INTEGER NOT NULL,
PTP_CODIGO INTEGER NOT NULL,
FOREIGN KEY(USU_CODIGO) REFERENCES USUARIOS (USU_CODIGO)
)

CREATE TABLE EDUCADORES_FISICOS (
EDF_CODIGO INTEGER AUTO_INCREMENT PRIMARY KEY
)

CREATE TABLE PROGRAMAS_TREINAMENTOS_PRONTOS (
PTP_DIFICULDADE VARCHAR(30) NOT NULL,
PTP_DESCRICAO VARCHAR(150) NOT NULL,
PTP_CODIGO INTEGER AUTO_INCREMENT PRIMARY KEY,
PTP_DURACAO VARCHAR(40) NOT NULL,
EDF_CODIGO INTEGER NOT NULL,
PTP_DT_CRIACAO DATE NOT NULL,
FOREIGN KEY(EDF_CODIGO) REFERENCES EDUCADORES_FISICOS (EDF_CODIGO)
)

ALTER TABLE FICHAS_TREINAMENTO ADD FOREIGN KEY(USU_CODIGO) REFERENCES USUARIOS (USU_CODIGO)
ALTER TABLE EXERCICIOS_DAS_FICHAS_TREINAMENTO ADD FOREIGN KEY(EFS_CODIGO) REFERENCES EXERCICIOS_FISICOS (EFS_CODIGO)
ALTER TABLE EXERCICIOS_DOS_PROGRAMAS_TREINAMENTO ADD FOREIGN KEY(EFS_CODIGO) REFERENCES EXERCICIOS_FISICOS (EFS_CODIGO)
ALTER TABLE EXERCICIOS_DOS_PROGRAMAS_TREINAMENTO ADD FOREIGN KEY(PTP_CODIGO) REFERENCES PROGRAMAS_TREINAMENTOS_PRONTOS (PTP_CODIGO)
ALTER TABLE DOBRAS_CUTANEAS_USUARIOS ADD FOREIGN KEY(DBC_CODIGO) REFERENCES DOBRAS_CUTANEAS (DBC_CODIGO)
ALTER TABLE USUARIO_TREINAMENTOS_PRONTOS ADD FOREIGN KEY(PTP_CODIGO) REFERENCES PROGRAMAS_TREINAMENTOS_PRONTOS (PTP_CODIGO)
