CREATE SCHEMA MODULO_07;
USE MODULO_07;


CREATE TABLE PERIODO_CARDAPIO_NUTRICIONISTA (
PCN_HR_PERIODO_ALIMENTO TIME NOT NULL,
PCN_NOME_PERIODO VARCHAR(100) NOT NULL,
PCN_CODIGO INTEGER AUTO_INCREMENT PRIMARY KEY NOT NULL,
PCN_QTD_CALORIAS_PERIODO DECIMAL(10,2) NOT NULL,
CAN_CODIGO INTEGER NOT NULL
);

CREATE TABLE CARDAPIO_ALIMENTAR_NUTRICIONISTA (
CAN_CODIGO INTEGER AUTO_INCREMENT PRIMARY KEY NOT NULL,
CAN_DATA_CRIACAO DATE NOT NULL,
CAN_DATA_INICIO DATE NOT NULL,
CAN_DATA_FIM DATE NOT NULL,
USU_CODIGO INTEGER NOT NULL,
NUT_CODIGO INTEGER NOT NULL
);

CREATE TABLE PERFIL_NUTRICIONAL (
PNT_CODIGO INTEGER AUTO_INCREMENT PRIMARY KEY NOT NULL,
PNT_OBJETIVO_INICIAL VARCHAR (100) NOT NULL,
PNT_EXPERIENCIA VARCHAR(100) NOT NULL,
USU_CODIGO INTEGER NOT NULL
);

CREATE TABLE SOLICITACOES_POPULACAO_TRATAMENTO (
SPT_CODIGO INTEGER AUTO_INCREMENT PRIMARY KEY NOT NULL,
SPT_DATA_ACEITA_RECUSA DATE NOT NULL,
SPT_DATA_SOLICITACAO DATE NOT NULL,
NUT_CODIGO INTEGER NOT NULL,
USU_CODIGO INTEGER NOT NULL
);

CREATE TABLE HR_DISPONIBILIDADE_NUTRICIONISTAS (
HDN_SEGUNDA_HR_INICIO TIME NOT NULL,
HDN_SEGUNDA_HR_FIM TIME NOT NULL,
HDN_TERCA_HR_INICIO TIME NOT NULL,
HDN_TERCA_HR_FIM TIME NOT NULL,
HDN_QUARTA_HR_INICIO TIME NOT NULL,
HDN_QUARTA_HR_FIM TIME NOT NULL,
HDN_QUINTA_HR_INICIO TIME NOT NULL,
HDN_QUINTA_HR_FIM TIME NOT NULL,
HDN_SEXTA_HR_FIM TIME NOT NULL,
HDN_ANO INTEGER NOT NULL,
HDN_SABADO_HR_INICIO TIME NOT NULL,
HDN_MES INTEGER NOT NULL,
HDN_SABADO_HR_FIM TIME NOT NULL,
HDN_CODIGO INTEGER AUTO_INCREMENT PRIMARY KEY NOT NULL,
HDN_SEXTA_HR_INICIO TIME NOT NULL,
NUT_CODIGO INTEGER NOT NULL
);

CREATE TABLE CONSULTAS_NUTRICIONISTAS (
CNT_STATUS BOOLEAN NOT NULL,
CNT_HORA_CONSULTA TIME NOT NULL,
CNT_CODIGO INTEGER AUTO_INCREMENT PRIMARY KEY NOT NULL,
CNT_DATA DATE NOT NULL,
NUT_CODIGO INTEGER NOT NULL,
USU_CODIGO INTEGER NOT NULL
);

CREATE TABLE FICHA_CONSULTAS_NUTRICIONISTA (
FCN_SE_N_JA_PRATICOU BOOLEAN NOT NULL,
FCN_SE_JA_ATIV_QUAIS_DURACAO VARCHAR(150) NOT NULL,
FCN_FAZ_DIETA_OU_SUPLEMENTACAO BOOLEAN NOT NULL,
FCN_QUAL_ATIV_QUANTO_TEMPO VARCHAR(100) NOT NULL,
FCN_PRATICA_ATIVIDADE_FISICA BOOLEAN NOT NULL,
FCN_RESTRICAO_ALIMENTAR BOOLEAN NOT NULL,
FCN_QUANTAS_REFEICOES_POR_DIA INTEGER NOT NULL,
FCN_DESCRICAO_ATIV_DURACAO VARCHAR(200) NOT NULL,
FCN_TEM_PLANO_SAUDE BOOLEAN NOT NULL,
FCN_QUAIS_RESTRICOES VARCHAR(150) NOT NULL,
FCN_QUAIS_ALERGIAS VARCHAR(150) NOT NULL,
FCN_TEM_ALERGIA BOOLEAN NOT NULL,
FCN_OBJETIVO VARCHAR(200) NOT NULL,
FCN_ESTATURA DECIMAL(10,2) NOT NULL,
FCN_PESO_ATUAL DECIMAL(10,2) NOT NULL,
FCN_CODIGO INTEGER AUTO_INCREMENT PRIMARY KEY NOT NULL,
FCN_ATIV_VEZES_POR_SEMANA VARCHAR(100) NOT NULL,
FCN_COMENTARIOS_NUTRICIONISTA VARCHAR(200) NOT NULL,
FCN_ULTIMO_ACESSO DATE NOT NULL,
NUT_CODIGO INTEGER NOT NULL,
USU_CODIGO INTEGER NOT NULL
);

CREATE TABLE USUARIOS (
USU_NATURALIDADE VARCHAR(100) NOT NULL,
USU_CIDADE VARCHAR(150) NOT NULL,
USU_CEP VARCHAR(50) NOT NULL,
USU_TELEFONE VARCHAR(15) NOT NULL,
USU_NUMERO_CASA VARCHAR(10) NOT NULL,
USU_RUA VARCHAR(100) NOT NULL,
USU_BAIRRO VARCHAR(100) NOT NULL,
USU_CODIGO INTEGER AUTO_INCREMENT PRIMARY KEY NOT NULL,
USU_NOME VARCHAR(100) NOT NULL,
NUT_CODIGO INTEGER NOT NULL
);

CREATE TABLE ALIMENTO_PERIODO_CARDAPIO (
APC_CODIGO INTEGER AUTO_INCREMENT PRIMARY KEY NOT NULL,
APC_PCN_PORCAO VARCHAR(200) NOT NULL,
APC_ALIMENTO_INDICADO VARCHAR(100) NOT NULL,
APC_VARIACAO_ALIMENTO VARCHAR(100) NOT NULL,
APC_QTD_CALORIAS DECIMAL(10,2) NOT NULL,
PCN_CODIGO INTEGER NOT NULL,
ACN_CODIGO INTEGER NOT NULL,
FOREIGN KEY(PCN_CODIGO) REFERENCES PERIODO_CARDAPIO_NUTRICIONISTA (PCN_CODIGO) NOT NULL
);

CREATE TABLE ALIMENTOS_CARDAPIO_NUTRICIONISTA (
ACN_NOME_VARIACAO_ALIMENTO VARCHAR(100) NOT NULL,
ACN_CODIGO INTEGER AUTO_INCREMENT PRIMARY KEY NOT NULL,
ACN_NOME_ALIMENTO VARCHAR(100) NOT NULL
);

CREATE TABLE VIDA_ALIMENTAR_METAS (
VAM_INDICE_GORDURAS INTEGER NOT NULL,
VAM_INDICE_NUTRIENTES INTEGER NOT NULL,
VAM_INGESTAO_CALORIAS INTEGER NOT NULL,
VAM_METAS_ALCANCAR VARCHAR(100) NOT NULL,
VAM_CODIGO INTEGER AUTO_INCREMENT PRIMARY KEY NOT NULL,
VAM_INDICE_PROTEINAS INTEGER NOT NULL,
VAM_INDICE_VITAMINAS INTEGER NOT NULL,
VAM_INDICE_CARBOIDRATOS INTEGER NOT NULL,
USU_CODIGO INTEGER NOT NULL,
NUT_CODIGO INTEGER NOT NULL,
FOREIGN KEY(USU_CODIGO) REFERENCES USUARIOS (USU_CODIGO)
);

CREATE TABLE NUTRICIONISTAS (
NUT_STATUS BOOLEAN NULL,
NUT_FOCO_NUTRICIONAL VARCHAR(100) NOT NULL,
NUT_NOME VARCHAR(100) NOT NULL,
NUT_DATA_NASCIMENTO DATE NOT NULL,
NUT_GENERO BOOLEAN NOT NULL,
NUT_FORMACAO_ACADEMICA VARCHAR(200) NOT NULL,
NUT_DESCRICAO VARCHAR(100) NOT NULL,
NUT_CODIGO INTEGER AUTO_INCREMENT PRIMARY KEY NOT NULL
);

ALTER TABLE PERIODO_CARDAPIO_NUTRICIONISTA ADD FOREIGN KEY(CAN_CODIGO) REFERENCES CARDAPIO_ALIMENTAR_NUTRICIONISTA (CAN_CODIGO);
ALTER TABLE CARDAPIO_ALIMENTAR_NUTRICIONISTA ADD FOREIGN KEY(USU_CODIGO) REFERENCES USUARIOS (USU_CODIGO);
ALTER TABLE CARDAPIO_ALIMENTAR_NUTRICIONISTA ADD FOREIGN KEY(NUT_CODIGO) REFERENCES NUTRICIONISTAS (NUT_CODIGO);
ALTER TABLE PERFIL_NUTRICIONAL ADD FOREIGN KEY(USU_CODIGO) REFERENCES USUARIOS (USU_CODIGO);
ALTER TABLE SOLICITACOES_POPULACAO_TRATAMENTO ADD FOREIGN KEY(NUT_CODIGO) REFERENCES NUTRICIONISTAS (NUT_CODIGO);
ALTER TABLE SOLICITACOES_POPULACAO_TRATAMENTO ADD FOREIGN KEY(USU_CODIGO) REFERENCES USUARIOS (USU_CODIGO);
ALTER TABLE HR_DISPONIBILIDADE_NUTRICIONISTAS ADD FOREIGN KEY(NUT_CODIGO) REFERENCES NUTRICIONISTAS (NUT_CODIGO);
ALTER TABLE CONSULTAS_NUTRICIONISTAS ADD FOREIGN KEY(NUT_CODIGO) REFERENCES NUTRICIONISTAS (NUT_CODIGO);
ALTER TABLE CONSULTAS_NUTRICIONISTAS ADD FOREIGN KEY(USU_CODIGO) REFERENCES USUARIOS (USU_CODIGO);
ALTER TABLE FICHA_CONSULTAS_NUTRICIONISTA ADD FOREIGN KEY(NUT_CODIGO) REFERENCES NUTRICIONISTAS (NUT_CODIGO);
ALTER TABLE FICHA_CONSULTAS_NUTRICIONISTA ADD FOREIGN KEY(USU_CODIGO) REFERENCES USUARIOS (USU_CODIGO);
ALTER TABLE USUARIOS ADD FOREIGN KEY(NUT_CODIGO) REFERENCES NUTRICIONISTAS (NUT_CODIGO);
ALTER TABLE ALIMENTO_PERIODO_CARDAPIO ADD FOREIGN KEY(ACN_CODIGO) REFERENCES ALIMENTOS_CARDAPIO_NUTRICIONISTA (ACN_CODIGO);
ALTER TABLE VIDA_ALIMENTAR_METAS ADD FOREIGN KEY(NUT_CODIGO) REFERENCES NUTRICIONISTAS (NUT_CODIGO);
