/* Lógico_mod2: */

CREATE TABLE EVENTOS (
    EVE_NOME VARCHAR(50),
    EVE_STATUS ENUM('EM BREVE', 'EM ANDAMENTO', 'FINALIZADO'),
    EVE_NOME_ALUNO VARCHAR(100),
    EVE_STATUS_INSCRICAO BOOLEAN,
    EVE_ID INT PRIMARY KEY,
    EVE_MATRICULA_ALUNO VARCHAR(100),
    FK_CAMPUS_CAM_ID INT
);

CREATE TABLE ALUNOS_INSCRITOS_EVENTOS (
    AIE_FOTO_PESSOAL VARCHAR(255),
    AIE_BOLETIM_ESCOLAR VARCHAR(255),
    AIE_COPIA_RG VARCHAR(255),
    AIE_HOMOLOGA BOOLEAN,
    AIE_ATIVO BOOLEAN,
    AIE_AUTORIZACAO_PAIS VARCHAR(255),
    AIE_JUSTIFICATIVA VARCHAR(255),
    AIE_ID INT PRIMARY KEY,
    FK_EVENTOS_EVE_ID INT,
    FK_ALUNOS_ALU_ID INT
);

CREATE TABLE ALUNOS (
    ALU_ID INT PRIMARY KEY,
    ALU_PRONTUARIO VARCHAR(10),
    ALU_NOME VARCHAR(100),
    ALU_DATA_NASCIMENTO DATE,
    ALU_CPF VARCHAR(11),
    ALU_TELEFONE VARCHAR(11),
    ALU_FOTO VARCHAR(255),
    FK_CAMPUS_CAM_ID INT
);

CREATE TABLE EVENTOS_MODALIDADES (
    EVM_ID INT PRIMARY KEY,
    FK_EVENTOS_EVE_ID INT,
    FK_MODALIDADES_MOD_ID INT
);

CREATE TABLE ALUNOS_INSCRITOS_MODALIDADES (
    AIM_COMPROVANTE_FAIXA VARCHAR(255),
    AIM_JUSTIFICATIVA VARCHAR(255),
    AIM_DEFERIDO BOOLEAN,
    AIM_ID INT PRIMARY KEY,
    FK_ALUNOS_ALU_ID INT,
    FK_EVENTOS_MODALIDADES_EVM_ID INT
);

CREATE TABLE MODALIDADES (
    MOD_ID INT PRIMARY KEY,
    MOD_NOME VARCHAR(100)
);

CREATE TABLE CAMPUS (
    CAM_ID INT PRIMARY KEY,
    CAM_NOME VARCHAR(100)
);
 
ALTER TABLE EVENTOS ADD CONSTRAINT FK_EVENTOS_2
    FOREIGN KEY (FK_CAMPUS_CAM_ID)
    REFERENCES CAMPUS (CAM_ID)
    ON DELETE CASCADE;
 
ALTER TABLE ALUNOS_INSCRITOS_EVENTOS ADD CONSTRAINT FK_ALUNOS_INSCRITOS_EVENTOS_2
    FOREIGN KEY (FK_EVENTOS_EVE_ID)
    REFERENCES EVENTOS (EVE_ID)
    ON DELETE CASCADE;
 
ALTER TABLE ALUNOS_INSCRITOS_EVENTOS ADD CONSTRAINT FK_ALUNOS_INSCRITOS_EVENTOS_3
    FOREIGN KEY (FK_ALUNOS_ALU_ID)
    REFERENCES ALUNOS (ALU_ID)
    ON DELETE CASCADE;
 
ALTER TABLE ALUNOS ADD CONSTRAINT FK_ALUNOS_2
    FOREIGN KEY (FK_CAMPUS_CAM_ID)
    REFERENCES CAMPUS (CAM_ID)
    ON DELETE CASCADE;
 
ALTER TABLE EVENTOS_MODALIDADES ADD CONSTRAINT FK_EVENTOS_MODALIDADES_2
    FOREIGN KEY (FK_EVENTOS_EVE_ID)
    REFERENCES EVENTOS (EVE_ID)
    ON DELETE CASCADE;
 
ALTER TABLE EVENTOS_MODALIDADES ADD CONSTRAINT FK_EVENTOS_MODALIDADES_3
    FOREIGN KEY (FK_MODALIDADES_MOD_ID)
    REFERENCES MODALIDADES (MOD_ID)
    ON DELETE CASCADE;
 
ALTER TABLE ALUNOS_INSCRITOS_MODALIDADES ADD CONSTRAINT FK_ALUNOS_INSCRITOS_MODALIDADES_2
    FOREIGN KEY (FK_ALUNOS_ALU_ID)
    REFERENCES ALUNOS (ALU_ID)
    ON DELETE RESTRICT;
 
ALTER TABLE ALUNOS_INSCRITOS_MODALIDADES ADD CONSTRAINT FK_ALUNOS_INSCRITOS_MODALIDADES_3
    FOREIGN KEY (FK_EVENTOS_MODALIDADES_EVM_ID)
    REFERENCES EVENTOS_MODALIDADES (EVM_ID)
    ON DELETE CASCADE;