/* Lógico versao1 14-06: */

CREATE TABLE REFEICOES_PLANO (
    REF_PLA_ID INTEGER AUTO_INCREMENT PRIMARY KEY,
    REF_PLA_QTD_CALORIAS_REFEICAO DECIMAL(10,2) NOT NULL,
    REF_PLA_DATA_REFEICAO DATE NOT NULL,
    REF_PLA_OBSERVACOES VARCHAR(255) NOT NULL,
    FK_PLANOS_ALIMENTARES_PLA_ALI_ID INTEGER,
    FK_TIPOS_REFEICOES_RFC_ID INTEGER
);

CREATE TABLE ALIMENTOS (
    ALI_QUANTIDADE DECIMAL(10,2) NOT NULL,
    ALI_CALORIA DECIMAL (10,2) NOT NULL,
    ALI_ID INTEGER AUTO_INCREMENT PRIMARY KEY,
    ALI_NOME VARCHAR(50) NOT NULL,
    FK_TIPO_ALIMENTOS_TIP_ALI_ID INTEGER,
    FK_UNIDADES_ALIMENTOS_UNI_ID INTEGER
);

CREATE TABLE PLANOS_ALIMENTARES (
    PLA_ALI_ID INTEGER AUTO_INCREMENT PRIMARY KEY,
    PLA_ALI_DATA_TERMINO DATE NOT NULL,
    PLA_ALI_DATA_INICIO DATE NOT NULL,
    FK_NUTRICIONISTAS_NUT_ID INTEGER
);

CREATE TABLE AMOSTRAS (
    AMT_NOME VARCHAR(50) NOT NULL,
    AMT_ID INTEGER AUTO_INCREMENT PRIMARY KEY,
    AMT_FOTO BLOB NOT NULL,
    AMT_DATA_HORA_SAIDA DATETIME NOT NULL,
    AMT_DATA_HORA_ENTRADA DATETIME NOT NULL,
    FK_REFEICOES_PLANO_REF_PLA_ID INTEGER
);

CREATE TABLE TIPOS_REFEICOES (
    RFC_ID INTEGER AUTO_INCREMENT PRIMARY KEY,
    RFC_NOME VARCHAR(20) NOT NULL
);

CREATE TABLE PADRAO_ALIMENTAR_IDOSO (
    PAI_ID INTEGER AUTO_INCREMENT PRIMARY KEY,
    FK_STATUS_ALIMENTACAO_STA_ALI_ID INTEGER,
    FK_ENFERMEIROS_ENF_ID INTEGER,
    FK_REFEICOES_PLANO_REF_PLA_ID INTEGER,
    FK_IDOSOS_IDO_ID INTEGER
);

CREATE TABLE UNIDADES_ALIMENTOS (
    UNI_ID INTEGER AUTO_INCREMENT PRIMARY KEY,
    UNI_NOME VARCHAR(2) NOT NULL
);

CREATE TABLE TIPO_ALIMENTOS (
    TIP_ALI_NOME VARCHAR(50) NOT NULL,
    TIP_ALI_ID INTEGER AUTO_INCREMENT PRIMARY KEY
);

CREATE TABLE NUTRICIONISTAS (
    NUT_NOME VARCHAR(100) NOT NULL,
    NUT_ID INTEGER AUTO_INCREMENT PRIMARY KEY
);

CREATE TABLE FICHAS_CONSULTAS_NUTRICIONAIS (
    FCN_HISTORICO VARCHAR(250) NOT NULL,
    FCN_ID INTEGER AUTO_INCREMENT,
    FCN_OBSERVACOES VARCHAR(250) NOT NULL,
    CON_NUT_ID INTEGER AUTO_INCREMENT,
    CON_NUT_LOCAL VARCHAR(10) NOT NULL,
    CON_NUT_DATA_HORA DATETIME NOT NULL,
    FK_IDOSOS_IDO_ID INTEGER,
    FK_NUTRICIONISTAS_NUT_ID INTEGER,
    PRIMARY KEY (FCN_ID, CON_NUT_ID)
);

CREATE TABLE IDOSOS (
    IDO_ID INTEGER AUTO_INCREMENT PRIMARY KEY,
    IDO_NOME VARCHAR(100) NOT NULL
);

CREATE TABLE STATUS_ALIMENTACAO (
    STA_ALI_DESCRICAO VARCHAR(20) NOT NULL,
    STA_ALI_ID INTEGER AUTO_INCREMENT PRIMARY KEY
);

CREATE TABLE ENFERMEIROS (
    ENF_ID INTEGER AUTO_INCREMENT PRIMARY KEY,
    ENF_NOME VARCHAR(100) NOT NULL
);

CREATE TABLE REFEICOES_ALIMENTOS (
    FK_ALIMENTOS_ALI_ID INTEGER,
    FK_REFEICOES_PLANO_REF_PLA_ID INTEGER,
    DAD_ALI_ID INTEGER AUTO_INCREMENT PRIMARY KEY,
    DAD_ALI_QUANTIDADE DECIMAL(10,2) NOT NULL
);
 
ALTER TABLE REFEICOES_PLANO ADD CONSTRAINT FK_REFEICOES_PLANO_2
    FOREIGN KEY (FK_PLANOS_ALIMENTARES_PLA_ALI_ID)
    REFERENCES PLANOS_ALIMENTARES (PLA_ALI_ID);
 
ALTER TABLE REFEICOES_PLANO ADD CONSTRAINT FK_REFEICOES_PLANO_3
    FOREIGN KEY (FK_TIPOS_REFEICOES_RFC_ID)
    REFERENCES TIPOS_REFEICOES (RFC_ID);
 
ALTER TABLE ALIMENTOS ADD CONSTRAINT FK_ALIMENTOS_2
    FOREIGN KEY (FK_UNIDADES_ALIMENTOS_UNI_ID)
    REFERENCES UNIDADES_ALIMENTOS (UNI_ID);
 
ALTER TABLE ALIMENTOS ADD CONSTRAINT FK_ALIMENTOS_3
    FOREIGN KEY (FK_TIPO_ALIMENTOS_TIP_ALI_ID)
    REFERENCES TIPO_ALIMENTOS (TIP_ALI_ID);
 
ALTER TABLE PLANOS_ALIMENTARES ADD CONSTRAINT FK_PLANOS_ALIMENTARES_2
    FOREIGN KEY (FK_NUTRICIONISTAS_NUT_ID)
    REFERENCES NUTRICIONISTAS (NUT_ID);
 
ALTER TABLE AMOSTRAS ADD CONSTRAINT FK_AMOSTRAS_2
    FOREIGN KEY (FK_REFEICOES_PLANO_REF_PLA_ID)
    REFERENCES REFEICOES_PLANO (REF_PLA_ID);
 
ALTER TABLE PADRAO_ALIMENTAR_IDOSO ADD CONSTRAINT FK_PADRAO_ALIMENTAR_IDOSO_2
    FOREIGN KEY (FK_STATUS_ALIMENTACAO_STA_ALI_ID)
    REFERENCES STATUS_ALIMENTACAO (STA_ALI_ID);
 
ALTER TABLE PADRAO_ALIMENTAR_IDOSO ADD CONSTRAINT FK_PADRAO_ALIMENTAR_IDOSO_3
    FOREIGN KEY (FK_ENFERMEIROS_ENF_ID)
    REFERENCES ENFERMEIROS (ENF_ID);
 
ALTER TABLE PADRAO_ALIMENTAR_IDOSO ADD CONSTRAINT FK_PADRAO_ALIMENTAR_IDOSO_4
    FOREIGN KEY (FK_REFEICOES_PLANO_REF_PLA_ID)
    REFERENCES REFEICOES_PLANO (REF_PLA_ID);
 
ALTER TABLE PADRAO_ALIMENTAR_IDOSO ADD CONSTRAINT FK_PADRAO_ALIMENTAR_IDOSO_5
    FOREIGN KEY (FK_IDOSOS_IDO_ID)
    REFERENCES IDOSOS (IDO_ID);
 
ALTER TABLE FICHAS_CONSULTAS_NUTRICIONAIS ADD CONSTRAINT FK_FICHAS_CONSULTAS_NUTRICIONAIS_2
    FOREIGN KEY (FK_IDOSOS_IDO_ID)
    REFERENCES IDOSOS (IDO_ID);
 
ALTER TABLE REFEICOES_ALIMENTOS ADD CONSTRAINT FK_REFEICOES_ALIMENTOS_1
    FOREIGN KEY (FK_ALIMENTOS_ALI_ID)
    REFERENCES ALIMENTOS (ALI_ID);
 
ALTER TABLE REFEICOES_ALIMENTOS ADD CONSTRAINT FK_REFEICOES_ALIMENTOS_3
    FOREIGN KEY (FK_REFEICOES_PLANO_REF_PLA_ID)
    REFERENCES REFEICOES_PLANO (REF_PLA_ID);