<?php

require_once 'Conexao.php';


class FICHA_CONSULTAS_NUTRICIONISTA_DAO {

    private $conexao;
    private $sql;
    private $usuario;
    private $resultado;
    private $tabela;

     public function __construct() {
        $conn = new Conexao();
        $this->conexao = $conn->getConexao();
        $this->tabela = "FICHA_CONSULTAS_NUTRICIONISTA";
    }

	public function listarTodos() {
        $this->sql = "select * from $this->tabela";
        $this->resultado = $this->conexao->prepare($this->sql);
        $this->resultado->execute();
        return $this->resultado->fetchAll();
    }

    public function Excluir($id) {
        $sql = "DELETE FROM $this->tabela WHERE ID =  :ID";
		$stmt = $pdo->prepare($sql);
		$stmt->bindParam(':ID', $id, PDO::PARAM_INT);   
		$stmt->execute();
    }
	
	public function Insert($FCN_PESO_ATUAL,$FCN_CODIGO,$FCN_COMENTARIOS_NUTRICIONISTA,$FCN_ULTIMO_ACESSO,$FCN_OBJETIVO,$FCN_ESTATURA,$FCN_QUAIS_ALERGIAS,
		$FCN_TEM_ALERGIA,$FCN_QUAIS_RESTRICOES,$FCN_TEM_PLANO_SAUDE,$FCN_DERCROCAO_ATIV_DURACAO,$FCN_QUANTAS_REFEICOES_POR_DIA,$FCN_ATIV_VEZES_POR_SEMANA,
		$FCN_RESTRICAO_ALIMENTAR,$FCN_PRATICA_ATIVIDADE_FISICA,$FCN_QUAL_ATIV_QUANTO_TEMPO,$FCN_FAZ_DIETA_OU_SUPLEMENTACAO,$FCN_SE_N_JA_PRATICOU,
		$FCN_SE_JA_ATIV_QUAIS_DURACAO){
		
		$sql = "INSERT INTO $this->tabela(
		FCN_PESO_ATUAL, 
		FCN_CODIGO,FCN_COMENTARIOS_NUTRICIONISTA,
		FCN_ULTIMO_ACESSO,
		FCN_OBJETIVO,
		FCN_ESTATURA,
		FCN_QUAIS_ALERGIAS,
		FCN_TEM_ALERGIA,
		FCN_QUAIS_RESTRICOES,
		FCN_TEM_PLANO_SAUDE,
		FCN_DERCROCAO_ATIV_DURACAO,
		FCN_QUANTAS_REFEICOES_POR_DIA,
		FCN_ATIV_VEZES_POR_SEMANA,
		FCN_RESTRICAO_ALIMENTAR,
		FCN_PRATICA_ATIVIDADE_FISICA,
		FCN_QUAL_ATIV_QUANTO_TEMPO,
		FCN_FAZ_DIETA_OU_SUPLEMENTACAO,
		FCN_SE_N_JA_PRATICOU,
		FCN_SE_JA_ATIV_QUAIS_DURACAO) 
		VALUES (
        :FCN_PESO_ATUAL, 
		:FCN_CODIGO,
		:FCN_COMENTARIOS_NUTRICIONISTA,
		:FCN_ULTIMO_ACESSO,
		:FCN_OBJETIVO,
		:FCN_ESTATURA,
		:FCN_QUAIS_ALERGIAS,
		:FCN_TEM_ALERGIA,
		:FCN_QUAIS_RESTRICOES,
		:FCN_TEM_PLANO_SAUDE,
		:FCN_DERCROCAO_ATIV_DURACAO,
		:FCN_QUANTAS_REFEICOES_POR_DIA,
		:FCN_ATIV_VEZES_POR_SEMANA,
		:FCN_RESTRICAO_ALIMENTAR,
		:FCN_PRATICA_ATIVIDADE_FISICA,
		:FCN_QUAL_ATIV_QUANTO_TEMPO,
		:FCN_FAZ_DIETA_OU_SUPLEMENTACAO,
		:FCN_SE_N_JA_PRATICOU,
		:FCN_SE_JA_ATIV_QUAIS_DURACAO)";
                                          
			$stmt = $pdo->prepare($sql);
					
			$stmt->bindParam(':FCN_PESO_ATUAL', $FCN_PESO_ATUAL, PDO::PARAM_STR);
			$stmt->bindParam(':FCN_CODIGO', $FCN_CODIGO, PDO::PARAM_STR); 
			$stmt->bindParam(':FCN_COMENTARIOS_NUTRICIONISTA', $FCN_COMENTARIOS_NUTRICIONISTA, PDO::PARAM_STR); 
			$stmt->bindParam(':FCN_ULTIMO_ACESSO', $FCN_ULTIMO_ACESSO, PDO::PARAM_STR); 
			$stmt->bindParam(':FCN_OBJETIVO', $FCN_OBJETIVO, PDO::PARAM_STR); 
			$stmt->bindParam(':FCN_ESTATURA', $FCN_ESTATURA, PDO::PARAM_STR);
			$stmt->bindParam(':FCN_QUAIS_ALERGIAS', $FCN_QUAIS_ALERGIAS, PDO::PARAM_STR);
			$stmt->bindParam(':FCN_TEM_ALERGIA', $FCN_TEM_ALERGIA, PDO::PARAM_STR);
			$stmt->bindParam(':FCN_QUAIS_RESTRICOES', $FCN_QUAIS_RESTRICOES, PDO::PARAM_STR); 
			$stmt->bindParam(':FCN_TEM_PLANO_SAUDE', $FCN_TEM_PLANO_SAUDE, PDO::PARAM_STR); 
			$stmt->bindParam(':FCN_DERCROCAO_ATIV_DURACAO', $FCN_DERCROCAO_ATIV_DURACAO, PDO::PARAM_STR); 
			$stmt->bindParam(':FCN_QUANTAS_REFEICOES_POR_DIA', $FCN_QUANTAS_REFEICOES_POR_DIA, PDO::PARAM_STR); 
			$stmt->bindParam(':FCN_ATIV_VEZES_POR_SEMANA', $FCN_ATIV_VEZES_POR_SEMANA, PDO::PARAM_STR); 
			$stmt->bindParam(':FCN_RESTRICAO_ALIMENTAR', $FCN_RESTRICAO_ALIMENTAR, PDO::PARAM_STR); 
			$stmt->bindParam(':FCN_PRATICA_ATIVIDADE_FISICA', $FCN_PRATICA_ATIVIDADE_FISICA, PDO::PARAM_STR); 
			$stmt->bindParam(':FCN_QUAL_ATIV_QUANTO_TEMPO', $FCN_QUAL_ATIV_QUANTO_TEMPO, PDO::PARAM_STR); 
			$stmt->bindParam(':FCN_FAZ_DIETA_OU_SUPLEMENTACAO', $FCN_FAZ_DIETA_OU_SUPLEMENTACAO, PDO::PARAM_STR); 
			$stmt->bindParam(':FCN_SE_N_JA_PRATICOU', $FCN_SE_N_JA_PRATICOU, PDO::PARAM_STR); 
			$stmt->bindParam(':FCN_SE_JA_ATIV_QUAIS_DURACAO', $FCN_SE_JA_ATIV_QUAIS_DURACAO, PDO::PARAM_STR); 
												  
			$stmt->execute(); 
		
	}
       
    public function Update($FCN_PESO_ATUAL,$FCN_CODIGO,$FCN_COMENTARIOS_NUTRICIONISTA,$FCN_ULTIMO_ACESSO,$FCN_OBJETIVO,$FCN_ESTATURA,$FCN_QUAIS_ALERGIAS,
		$FCN_TEM_ALERGIA,$FCN_QUAIS_RESTRICOES,$FCN_TEM_PLANO_SAUDE,$FCN_DERCROCAO_ATIV_DURACAO,$FCN_QUANTAS_REFEICOES_POR_DIA,$FCN_ATIV_VEZES_POR_SEMANA,
		$FCN_RESTRICAO_ALIMENTAR,$FCN_PRATICA_ATIVIDADE_FISICA,$FCN_QUAL_ATIV_QUANTO_TEMPO,$FCN_FAZ_DIETA_OU_SUPLEMENTACAO,$FCN_SE_N_JA_PRATICOU,
		$FCN_SE_JA_ATIV_QUAIS_DURACAO){
		
		$sql = "UPDATE $this->tabela SET
		FCN_PESO_ATUAL =:FCN_PESO_ATUAL, 
		FCN_CODIGO=:FCN_CODIGO,
		FCN_COMENTARIOS_NUTRICIONISTA=:FCN_COMENTARIOS_NUTRICIONISTA,
		FCN_ULTIMO_ACESSO=:FCN_ULTIMO_ACESSO,
		FCN_OBJETIVO=:FCN_OBJETIVO,
		FCN_ESTATURA=:FCN_ESTATURA,
		FCN_QUAIS_ALERGIAS=:FCN_QUAIS_ALERGIAS,
		FCN_TEM_ALERGIA=:FCN_TEM_ALERGIA,
		FCN_QUAIS_RESTRICOES=:FCN_QUAIS_RESTRICOES,
		FCN_TEM_PLANO_SAUDE=:FCN_TEM_PLANO_SAUDE,
		FCN_DERCROCAO_ATIV_DURACAO=:FCN_DERCROCAO_ATIV_DURACAO,
		FCN_QUANTAS_REFEICOES_POR_DIA=:FCN_QUANTAS_REFEICOES_POR_DIA,
		FCN_ATIV_VEZES_POR_SEMANA=:FCN_ATIV_VEZES_POR_SEMANA,
		FCN_RESTRICAO_ALIMENTAR=:FCN_RESTRICAO_ALIMENTAR,
		FCN_PRATICA_ATIVIDADE_FISICA=:FCN_PRATICA_ATIVIDADE_FISICA,
		FCN_QUAL_ATIV_QUANTO_TEMPO=:FCN_QUAL_ATIV_QUANTO_TEMPO,
		FCN_FAZ_DIETA_OU_SUPLEMENTACAO=:FCN_FAZ_DIETA_OU_SUPLEMENTACAO,
		FCN_SE_N_JA_PRATICOU=:FCN_SE_N_JA_PRATICOU,
		FCN_SE_JA_ATIV_QUAIS_DURACAO=:FCN_SE_JA_ATIV_QUAIS_DURACAO";
$stmt = $pdo->prepare($sql);                                  
$stmt->bindParam(':FCN_PESO_ATUAL', $FCN_PESO_ATUAL, PDO::PARAM_STR);
			$stmt->bindParam(':FCN_CODIGO', $FCN_CODIGO, PDO::PARAM_STR); 
			$stmt->bindParam(':FCN_COMENTARIOS_NUTRICIONISTA', $FCN_COMENTARIOS_NUTRICIONISTA, PDO::PARAM_STR); 
			$stmt->bindParam(':FCN_ULTIMO_ACESSO', $FCN_ULTIMO_ACESSO, PDO::PARAM_STR); 
			$stmt->bindParam(':FCN_OBJETIVO', $FCN_OBJETIVO, PDO::PARAM_STR); 
			$stmt->bindParam(':FCN_ESTATURA', $FCN_ESTATURA, PDO::PARAM_STR);
			$stmt->bindParam(':FCN_QUAIS_ALERGIAS', $FCN_QUAIS_ALERGIAS, PDO::PARAM_STR);
			$stmt->bindParam(':FCN_TEM_ALERGIA', $FCN_TEM_ALERGIA, PDO::PARAM_STR);
			$stmt->bindParam(':FCN_QUAIS_RESTRICOES', $FCN_QUAIS_RESTRICOES, PDO::PARAM_STR); 
			$stmt->bindParam(':FCN_TEM_PLANO_SAUDE', $FCN_TEM_PLANO_SAUDE, PDO::PARAM_STR); 
			$stmt->bindParam(':FCN_DERCROCAO_ATIV_DURACAO', $FCN_DERCROCAO_ATIV_DURACAO, PDO::PARAM_STR); 
			$stmt->bindParam(':FCN_QUANTAS_REFEICOES_POR_DIA', $FCN_QUANTAS_REFEICOES_POR_DIA, PDO::PARAM_STR); 
			$stmt->bindParam(':FCN_ATIV_VEZES_POR_SEMANA', $FCN_ATIV_VEZES_POR_SEMANA, PDO::PARAM_STR); 
			$stmt->bindParam(':FCN_RESTRICAO_ALIMENTAR', $FCN_RESTRICAO_ALIMENTAR, PDO::PARAM_STR); 
			$stmt->bindParam(':FCN_PRATICA_ATIVIDADE_FISICA', $FCN_PRATICA_ATIVIDADE_FISICA, PDO::PARAM_STR); 
			$stmt->bindParam(':FCN_QUAL_ATIV_QUANTO_TEMPO', $FCN_QUAL_ATIV_QUANTO_TEMPO, PDO::PARAM_STR); 
			$stmt->bindParam(':FCN_FAZ_DIETA_OU_SUPLEMENTACAO', $FCN_FAZ_DIETA_OU_SUPLEMENTACAO, PDO::PARAM_STR); 
			$stmt->bindParam(':FCN_SE_N_JA_PRATICOU', $FCN_SE_N_JA_PRATICOU, PDO::PARAM_STR); 
			$stmt->bindParam(':FCN_SE_JA_ATIV_QUAIS_DURACAO', $FCN_SE_JA_ATIV_QUAIS_DURACAO, PDO::PARAM_STR);    
$stmt->execute(); 
		
	}
	}




?>
