<?php


class PERIODO_CARDAPIO_NUTRICIONISTA{
   private $PCN_CODIGO;
  private $FK_CARDAPIO_ALIMENTAR_NUTRICIONISTA_CAN_CODIGO;
   private $PCN_NOME_PERIODO;
   private $PCN_HORA_PERIODO_ALIMENTO;
   
   function getFK_CARDAPIO_ALIMENTAR_NUTRICIONISTA_CAN_CODIGO() {
       return $this->FK_CARDAPIO_ALIMENTAR_NUTRICIONISTA_CAN_CODIGO;
   }

   function setFK_CARDAPIO_ALIMENTAR_NUTRICIONISTA_CAN_CODIGO($FK_CARDAPIO_ALIMENTAR_NUTRICIONISTA_CAN_CODIGO) {
       $this->FK_CARDAPIO_ALIMENTAR_NUTRICIONISTA_CAN_CODIGO = $FK_CARDAPIO_ALIMENTAR_NUTRICIONISTA_CAN_CODIGO;
   }

      function getPCN_CODIGO() {
       return $this->PCN_CODIGO;
   }

  
   function getPCN_NOME_PERIODO() {
       return $this->PCN_NOME_PERIODO;
   }

   function getPCN_HORA_PERIODO_ALIMENTO() {
       return $this->PCN_HORA_PERIODO_ALIMENTO;
   }

   function setPCN_CODIGO($PCN_CODIGO) {
       $this->PCN_CODIGO = $PCN_CODIGO;
   }


   function setPCN_NOME_PERIODO($PCN_NOME_PERIODO) {
       $this->PCN_NOME_PERIODO = $PCN_NOME_PERIODO;
   }

   function setPCN_HORA_PERIODO_ALIMENTO($PCN_HORA_PERIODO_ALIMENTO) {
       $this->PCN_HORA_PERIODO_ALIMENTO = $PCN_HORA_PERIODO_ALIMENTO;
   }


}
