CREATE TABLE ALUNOS (
    ALN_NOME_SOCIAL VARCHAR(100),
    ALN_SEXO ENUM('MASCULINO', 'FEMININO') NOT NULL,
    ALN_ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    ALN_ETNIA ENUM('Branco', 'Preto', 'Pardo', 'Indígena', 'Amarelo')  NOT NULL,
    ALN_CPF VARCHAR(11) NOT NULL,
    ALN_RG VARCHAR(9) NOT NULL,
    ALN_FOTO VARCHAR(255),
    ALN_PRONTUARIO VARCHAR(9) NOT NULL,
    ALN_CEP VARCHAR(8) NOT NULL,
    ALN_TELEFONE VARCHAR(15) NOT NULL,
    ALN_BAIRRO VARCHAR(100) NOT NULL,
    ALN_RUA VARCHAR(100) NOT NULL,
    ALN_NUMERO VARCHAR(5) NOT NULL,
    ALN_COMPLEMENTO VARCHAR(100),
    ALN_DATA_NASCIMENTO DATE NOT NULL,
    ALN_NOME VARCHAR(100) NOT NULL,
    FK_LOGIN_LGN_ID INT NOT NULL,
    FK_CIDADES_CID_ID INT NOT NULL,
    CID_CAD_ID INT NOT NULL,
    FK_CURSOS_CUR_ID INT NOT NULL,
    PRIMARY KEY (ALN_ID, CID_CAD_ID),
    UNIQUE (ALN_ID, ALN_CPF, ALN_RG, ALN_PRONTUARIO)
);

CREATE TABLE ADMINISTRADORES (
    ADM_ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    FK_LOGIN_LGN_ID INT NOT NULL
);

CREATE TABLE LOGIN (
    LGN_ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    LGN_EMAIL VARCHAR(255) NOT NULL,
    LGN_SENHA VARCHAR(20) NOT NULL,
    LGN_TIPO ENUM('AD', 'OE', 'SE','RE', 'AL') NOT NULL,
    LGN_ATIVO ENUM('S','N') NOT NULL,
    UNIQUE (LGN_ID, LGN_EMAIL)
);

CREATE TABLE RESPONSAVEIS_EQUIPE (
    RSE_ID INT PRIMARY KEY,
    FK_LOGIN_LGN_ID INT
);

CREATE TABLE SECRETARIOS_EVENTOS (
    SCE_ID INT PRIMARY KEY,
    FK_LOGIN_LGN_ID INT
);

CREATE TABLE ORGANIZADORES_EVENTOS (
    ORE_ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    FK_LOGIN_LGN_ID INT NOT NULL
);

CREATE TABLE ESTADOS (
    EST_ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    EST_SIGLA ENUM ('SP') NOT NULL
);

CREATE TABLE CIDADES (
    CID_ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    CID_NOME VARCHAR(100) NOT NULL,
    FK_ESTADOS_EST_ID INT NOT NULL
);

CREATE TABLE CAMPUS (
    CAM_ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    CAM_NOME VARCHAR(100) NOT NULL,
    FK_CIDADES_CID_ID INT NOT NULL
);

CREATE TABLE CURSOS (
    CUR_NOME VARCHAR(100) NOT NULL,
    CUR_ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY
);

CREATE TABLE EVENTOS (
    EVE_ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY
);

CREATE TABLE CAMPUS_CURSOS (
    FK_CURSOS_CUR_ID INT NOT NULL,
    FK_CAMPUS_CAM_ID INT NOT NULL,
    CAM_CUR_ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY
);

CREATE TABLE ALUNOS_INSCRITOS (
    FK_ALUNOS_ALN_ID INT NOT NULL,
    FK_ALUNOS_CID_CAD_ID INT NOT NULL,
    FK_EVENTOS_EVE_ID INT NOT NULL,
    ALI_ID INT NOT NULL PRIMARY KEY
);
 
ALTER TABLE ALUNOS ADD CONSTRAINT FK_ALUNOS_2
    FOREIGN KEY (FK_LOGIN_LGN_ID)
    REFERENCES LOGIN (LGN_ID)
    ON DELETE CASCADE;
 
ALTER TABLE ALUNOS ADD CONSTRAINT FK_ALUNOS_3
    FOREIGN KEY (FK_CIDADES_CID_ID)
    REFERENCES CIDADES (CID_ID)
    ON DELETE CASCADE;
 
ALTER TABLE ALUNOS ADD CONSTRAINT FK_ALUNOS_4
    FOREIGN KEY (FK_CURSOS_CUR_ID)
    REFERENCES CURSOS (CUR_ID)
    ON DELETE CASCADE;
 
ALTER TABLE ADMINISTRADORES ADD CONSTRAINT FK_ADMINISTRADORES_2
    FOREIGN KEY (FK_LOGIN_LGN_ID)
    REFERENCES LOGIN (LGN_ID)
    ON DELETE CASCADE;
 
ALTER TABLE RESPONSAVEIS_EQUIPE ADD CONSTRAINT FK_RESPONSAVEIS_EQUIPE_2
    FOREIGN KEY (FK_LOGIN_LGN_ID)
    REFERENCES LOGIN (LGN_ID)
    ON DELETE CASCADE;
 
ALTER TABLE SECRETARIOS_EVENTOS ADD CONSTRAINT FK_SECRETARIOS_EVENTOS_2
    FOREIGN KEY (FK_LOGIN_LGN_ID)
    REFERENCES LOGIN (LGN_ID)
    ON DELETE CASCADE;
 
ALTER TABLE ORGANIZADORES_EVENTOS ADD CONSTRAINT FK_ORGANIZADORES_EVENTOS_2
    FOREIGN KEY (FK_LOGIN_LGN_ID)
    REFERENCES LOGIN (LGN_ID)
    ON DELETE CASCADE;
 
ALTER TABLE CIDADES ADD CONSTRAINT FK_CIDADES_2
    FOREIGN KEY (FK_ESTADOS_EST_ID)
    REFERENCES ESTADOS (EST_ID)
    ON DELETE CASCADE;
 
ALTER TABLE CAMPUS ADD CONSTRAINT FK_CAMPUS_2
    FOREIGN KEY (FK_CIDADES_CID_ID)
    REFERENCES CIDADES (CID_ID)
    ON DELETE CASCADE;
 
ALTER TABLE CAMPUS_CURSOS ADD CONSTRAINT FK_CAMPUS_CURSOS_2
    FOREIGN KEY (FK_CURSOS_CUR_ID)
    REFERENCES CURSOS (CUR_ID)
    ON DELETE SET NULL;
 
ALTER TABLE CAMPUS_CURSOS ADD CONSTRAINT FK_CAMPUS_CURSOS_3
    FOREIGN KEY (FK_CAMPUS_CAM_ID)
    REFERENCES CAMPUS (CAM_ID)
    ON DELETE SET NULL;
 
ALTER TABLE ALUNOS_INSCRITOS ADD CONSTRAINT FK_ALUNOS_INSCRITOS_2
    FOREIGN KEY (FK_ALUNOS_ALN_ID, FK_ALUNOS_CID_CAD_ID)
    REFERENCES ALUNOS (ALN_ID, CID_CAD_ID)
    ON DELETE SET NULL;
 
ALTER TABLE ALUNOS_INSCRITOS ADD CONSTRAINT FK_ALUNOS_INSCRITOS_3
    FOREIGN KEY (FK_EVENTOS_EVE_ID)
    REFERENCES EVENTOS (EVE_ID)
    ON DELETE SET NULL;