CREATE TABLE ESTABELECIMENTOS (
EST_ID INTEGER AUTO_INCREMENT UNIQUE NOT NULL PRIMARY KEY,
EST_CNPJ VARCHAR(14) UNIQUE NOT NULL,
EST_FOTO_PERFIL VARCHAR(300) NOT NULL,
EST_NOME_FANTASIA VARCHAR(100) NOT NULL,
EST_ENDERECO VARCHAR(300) NOT NULL,
EST_CEP VARCHAR(10) NOT NULL,
EST_NOME_RESPONSAVEL VARCHAR(100) NOT NULL,
EST_NOME_EMPRESA VARCHAR(300) NOT NULL,
EST_PUBLICO_ALVO VARCHAR(100) NOT NULL,
EST_SITE_EMPRESA VARCHAR(100),
EST_EMAIL VARCHAR(100) NOT NULL,
TIP_ID INTEGER
);

CREATE TABLE NOTIFICACOES (
NOT_ID INTEGER AUTO_INCREMENT UNIQUE NOT NULL PRIMARY KEY,
NOT_DATA_EVENTO DATE,
NOT_NOME VARCHAR(100),
NOT_TIPO_NOTIFICACAO INTEGER
);

CREATE TABLE REUNIOES_AGENDADAS (
REU_ID INTEGER AUTO_INCREMENT UNIQUE NOT NULL PRIMARY KEY,
REU_LOCAL VARCHAR(100),
REU_HORARIO_INICIO TIME,
REU_DATA DATE,
REU_HORARIO_TERMINO TIME,
REU_NOME_EVENTO VARCHAR(100),
REU_DESCRICAO VARCHAR(500),
NOT_ID INTEGER,
EST_ID INTEGER,
CON_ID INTEGER,
FOREIGN KEY(NOT_ID) REFERENCES NOTIFICACOES (NOT_ID),
FOREIGN KEY(EST_ID) REFERENCES ESTABELECIMENTOS (EST_ID)
);

CREATE TABLE RESPOSTAS_RECLAMACOES (
POS_ID INTEGER AUTO_INCREMENT UNIQUE NOT NULL PRIMARY KEY,
POS_DATA DATE,
POS_CONTEUDO VARCHAR(800),
POS_AVALIACAO FLOAT(5),
POS_NOME_EMPRESA VARCHAR(100),
POS_STATUS_APROVADO BOOLEAN,
NOT_ID INTEGER,
REC_ID INTEGER,
FOREIGN KEY(NOT_ID) REFERENCES NOTIFICACOES (NOT_ID)
);

CREATE TABLE RECLAMACOES (
REC_ID INTEGER AUTO_INCREMENT UNIQUE NOT NULL PRIMARY KEY,
REC_NOME_CONSUMIDOR VARCHAR(100),
REC_TITULO VARCHAR(100),
REC_CONTEUDO VARCHAR(800),
REC_DATA DATE,
REC_HORA TIME,
CON_ID INTEGER,
NOT_ID INTEGER,
EST_ID INTEGER,
FOREIGN KEY(NOT_ID) REFERENCES NOTIFICACOES (NOT_ID),
FOREIGN KEY(EST_ID) REFERENCES ESTABELECIMENTOS (EST_ID)
);

CREATE TABLE TIPO_ESTABELECIMENTOS (
TIP_ID INTEGER AUTO_INCREMENT UNIQUE NOT NULL PRIMARY KEY,
TIP_NOME VARCHAR(100)
);

CREATE TABLE PRODUTOS (
PRO_ID INTEGER AUTO_INCREMENT UNIQUE NOT NULL PRIMARY KEY,
PRO_NOME_PRODUTO VARCHAR(100),
IPO_ID INTEGER,
EST_ID INTEGER,
FOREIGN KEY(EST_ID) REFERENCES ESTABELECIMENTOS (EST_ID)
);

CREATE TABLE TIPOS_PRODUTOS (
IPO_ID INTEGER AUTO_INCREMENT UNIQUE NOT NULL PRIMARY KEY,
IPO_DESCRICAO VARCHAR(300)
);

CREATE TABLE RECEBEM_NOTIFICACOES (
REN_ID INTEGER AUTO_INCREMENT UNIQUE NOT NULL PRIMARY KEY,
EST_ID INTEGER,
NOT_ID INTEGER,
FOREIGN KEY(EST_ID) REFERENCES ESTABELECIMENTOS (EST_ID),
FOREIGN KEY(NOT_ID) REFERENCES NOTIFICACOES (NOT_ID)
);

CREATE TABLE CONSUMIDORES (
CON_ID INTEGER AUTO_INCREMENT UNIQUE NOT NULL PRIMARY KEY,
NOT_ID INTEGER,
FOREIGN KEY(NOT_ID) REFERENCES NOTIFICACOES (NOT_ID)
);

CREATE TABLE RECLAMACOES_DENUNCIADAS (
DEN_ID INTEGER AUTO_INCREMENT UNIQUE NOT NULL PRIMARY KEY,
DEN_MOTIVO INTEGER,
DEN_JUSTIFICATIVA VARCHAR(500),
DEN_STATUS_APROVADO BOOLEAN,
DEN_DATA DATE,
DEN_HORA TIME,
EST_ID INTEGER,
FOREIGN KEY(EST_ID) REFERENCES ESTABELECIMENTOS (EST_ID)
);

ALTER TABLE ESTABELECIMENTOS ADD FOREIGN KEY(TIP_ID) REFERENCES TIPO_ESTABELECIMENTOS (TIP_ID);
ALTER TABLE REUNIOES_AGENDADAS ADD FOREIGN KEY(CON_ID) REFERENCES CONSUMIDORES (CON_ID);
ALTER TABLE RESPOSTAS_RECLAMACOES ADD FOREIGN KEY(REC_ID) REFERENCES RECLAMACOES (REC_ID);
ALTER TABLE RECLAMACOES ADD FOREIGN KEY(CON_ID) REFERENCES CONSUMIDORES (CON_ID);
ALTER TABLE PRODUTOS ADD FOREIGN KEY(IPO_ID) REFERENCES TIPOS_PRODUTOS (IPO_ID);