/* Lógico_1: */

CREATE TABLE ATIVIDADES_FISICAS (
    AFI_ID INTEGER NOT NULL Auto_Increment PRIMARY KEY,
    AFI_NOME VARCHAR(100)
);

CREATE TABLE IDOSO (
    IDS_NOME VARCHAR(100),
    IDS_DATA_NASC TIMESTAMP,
    IDS_GENERO VARCHAR(15),
    IDS_ID INTEGER NOT NULL Auto_Increment PRIMARY KEY,
    IDS_CPF VARCHAR(15),
    IDS_PESO FLOAT,
    IDS_ALTURA FLOAT
);

CREATE TABLE ATIVIDADES_RECREATIVAS (
    ATR_ID INTEGER NOT NULL Auto_Increment PRIMARY KEY,
    ATR_NOME VARCHAR(100),
    FK_TIPO_ATIVIDADES_RECREATIVAS_TAR_ID INTEGER
);

CREATE TABLE PLANEJAMENTOS_MENSAIS_ATV_RECREATIVAS (
    PMR_ID INTEGER NOT NULL Auto_Increment PRIMARY KEY,
    PMR_MES VARCHAR(50),
    PMR_ANO INTEGER
);

CREATE TABLE TREINAMENTOS_FISICOS_DIARIO (
    TFD_ID INTEGER NOT NULL Auto_Increment PRIMARY KEY,
    TFD_DATA_INICIO TIMESTAMP,
    TFD_FOCO VARCHAR(100),
    TFD_DATA_TERMINO TIMESTAMP,
    TFD_DIA_DA_SEMANA VARCHAR(100),
    FK_IDOSO_IDS_ID INTEGER,
    FK_USUARIOS_USU_ID INTEGER
);

CREATE TABLE CONSULTAS_ESPORTIVAS (
    CES_IMC_IDOSO FLOAT,
    CES_ANOTACOES VARCHAR(100),
    CES_PRESCRICOES VARCHAR(100),
    CES_ID INTEGER NOT NULL Auto_Increment PRIMARY KEY,
    CES_DATA_HORA DATETIME,
    CES_LOCAL VARCHAR(100),
    FK_IDOSO_IDS_ID INTEGER,
    FK_USUARIOS_USU_ID INTEGER
);

CREATE TABLE TIPOS_ATIVIDADES_FISICAS (
    TAF_ID INTEGER,
    TAF_NOME VARCHAR(100)
);

CREATE TABLE TIPO_ATIVIDADES_RECREATIVAS (
    TAR_ID INTEGER NOT NULL Auto_Increment PRIMARY KEY,
    TAR_NOME VARCHAR(100)
);

CREATE TABLE USUARIOS (
    USU_DATA_NASC DATE,
    USU_ID INTEGER NOT NULL Auto_Increment PRIMARY KEY,
    USU_NOME VARCHAR(100),
    USU_GENERO VARCHAR(15),
    USU_CPF VARCHAR(15),
    USU_ESPECIALIDADE VARCHAR(100),
    USU_REGISTRO_PROFISSIONAL VARCHAR(100),
    USUARIOS_TIPO INT
);

CREATE TABLE ATIVIDADES_RECREATIVAS_PLANEJAMENTO (
    ARP_DATA_HORA DATETIME,
    ARP_FOTO BLOB,
    FK_PLANEJAMENTOS_MENSAIS_ATV_RECREATIVAS_PMR_ID INTEGER,
    FK_ATIVIDADES_RECREATIVAS_ATR_ID INTEGER,
    ARP_ID INTEGER NOT NULL Auto_Increment PRIMARY KEY,
    ARP_LOCAL VARCHAR(100),
    ARP_DURACAO TIME
);

CREATE TABLE ATIVIDADES_DOS_TREINAMENTOS_FISICOS (
    FK_ATIVIDADES_FISICAS_AFI_ID INTEGER,
    FK_TREINAMENTOS_FISICOS_DIARIO_TFD_ID INTEGER,
    ATF_ID INTEGER NOT NULL Auto_Increment PRIMARY KEY,
    ATF_PESO FLOAT,
    ATF_REPETICOES INTEGER,
    ATF_TEMPO_INTERVALO INTEGER,
    ATF_OBSERVACOES VARCHAR(500)
);

CREATE TABLE USU_PM (
    FK_USUARIOS_USU_ID INTEGER,
    FK_PLANEJAMENTOS_MENSAIS_ATV_RECREATIVAS_PMR_ID INTEGER
);

CREATE TABLE PARTICIPACAO_IDOSOS_ATV_RECREATIVAS (
    FK_IDOSO_IDS_ID INTEGER,
    PIR_ID INTEGER NOT NULL Auto_Increment PRIMARY KEY
);
 
ALTER TABLE ATIVIDADES_RECREATIVAS ADD CONSTRAINT FK_ATIVIDADES_RECREATIVAS_2
    FOREIGN KEY (FK_TIPO_ATIVIDADES_RECREATIVAS_TAR_ID)
    REFERENCES TIPO_ATIVIDADES_RECREATIVAS (TAR_ID)
    ON DELETE CASCADE;
 
ALTER TABLE TREINAMENTOS_FISICOS_DIARIO ADD CONSTRAINT FK_TREINAMENTOS_FISICOS_DIARIO_2
    FOREIGN KEY (FK_IDOSO_IDS_ID)
    REFERENCES IDOSO (IDS_ID)
    ON DELETE CASCADE;
 
ALTER TABLE TREINAMENTOS_FISICOS_DIARIO ADD CONSTRAINT FK_TREINAMENTOS_FISICOS_DIARIO_3
    FOREIGN KEY (FK_USUARIOS_USU_ID)
    REFERENCES USUARIOS (USU_ID)
    ON DELETE CASCADE;
 
ALTER TABLE CONSULTAS_ESPORTIVAS ADD CONSTRAINT FK_CONSULTAS_ESPORTIVAS_2
    FOREIGN KEY (FK_IDOSO_IDS_ID)
    REFERENCES IDOSO (IDS_ID)
    ON DELETE CASCADE;
 
ALTER TABLE CONSULTAS_ESPORTIVAS ADD CONSTRAINT FK_CONSULTAS_ESPORTIVAS_3
    FOREIGN KEY (FK_USUARIOS_USU_ID)
    REFERENCES USUARIOS (USU_ID)
    ON DELETE CASCADE;
 
ALTER TABLE ATIVIDADES_RECREATIVAS_PLANEJAMENTO ADD CONSTRAINT FK_ATIVIDADES_RECREATIVAS_PLANEJAMENTO_2
    FOREIGN KEY (FK_PLANEJAMENTOS_MENSAIS_ATV_RECREATIVAS_PMR_ID)
    REFERENCES PLANEJAMENTOS_MENSAIS_ATV_RECREATIVAS (PMR_ID);
 
ALTER TABLE ATIVIDADES_RECREATIVAS_PLANEJAMENTO ADD CONSTRAINT FK_ATIVIDADES_RECREATIVAS_PLANEJAMENTO_3
    FOREIGN KEY (FK_ATIVIDADES_RECREATIVAS_ATR_ID)
    REFERENCES ATIVIDADES_RECREATIVAS (ATR_ID);
 
ALTER TABLE ATIVIDADES_DOS_TREINAMENTOS_FISICOS ADD CONSTRAINT FK_ATIVIDADES_DOS_TREINAMENTOS_FISICOS_2
    FOREIGN KEY (FK_ATIVIDADES_FISICAS_AFI_ID)
    REFERENCES ATIVIDADES_FISICAS (AFI_ID)
    ON DELETE RESTRICT;
 
ALTER TABLE ATIVIDADES_DOS_TREINAMENTOS_FISICOS ADD CONSTRAINT FK_ATIVIDADES_DOS_TREINAMENTOS_FISICOS_3
    FOREIGN KEY (FK_TREINAMENTOS_FISICOS_DIARIO_TFD_ID)
    REFERENCES TREINAMENTOS_FISICOS_DIARIO (TFD_ID)
    ON DELETE SET NULL;
 
ALTER TABLE USU_PM ADD CONSTRAINT FK_USU_PM_1
    FOREIGN KEY (FK_USUARIOS_USU_ID)
    REFERENCES USUARIOS (USU_ID)
    ON DELETE RESTRICT;
 
ALTER TABLE USU_PM ADD CONSTRAINT FK_USU_PM_2
    FOREIGN KEY (FK_PLANEJAMENTOS_MENSAIS_ATV_RECREATIVAS_PMR_ID)
    REFERENCES PLANEJAMENTOS_MENSAIS_ATV_RECREATIVAS (PMR_ID)
    ON DELETE SET NULL;
 
ALTER TABLE PARTICIPACAO_IDOSOS_ATV_RECREATIVAS ADD CONSTRAINT FK_PARTICIPACAO_IDOSOS_ATV_RECREATIVAS_2
    FOREIGN KEY (FK_IDOSO_IDS_ID)
    REFERENCES IDOSO (IDS_ID)
    ON DELETE SET NULL;