CREATE DATABASE IF NOT EXISTS GERACOES_MOD08;
USE GERACOES_MOD08;

/* MOD08_LOGICO: */

CREATE TABLE TAREFAS_LIMPEZA (
    TAR_ID INTEGER AUTO_INCREMENT PRIMARY KEY UNIQUE,
    TAR_NOME VARCHAR(50) NOT NULL,
    TAR_DESCRICAO VARCHAR(250) NOT NULL,
    TAR_STATUS BOOLEAN NOT NULL,
    TAR_OBSERVACAO VARCHAR(500),
    TAR_DATA_PREVISTA DATETIME NOT NULL,
    FK_PLANEJAMENTOS_SEMANAIS_PLA_ID INTEGER,
    FK_FUNCIONARIOS_FUN_ID INTEGER,
    TAR_DATA_REALIZACAO DATETIME NOT NULL,
    FK_SETORES_INSTITUICAO_SET_ID INTEGER
);

CREATE TABLE DOACOES (
    DOA_ID INTEGER AUTO_INCREMENT PRIMARY KEY UNIQUE,
    DOA_NOME VARCHAR(50) NOT NULL,
    DOA_TIPO VARCHAR(50),
    DOA_DESCRICAO VARCHAR(300),
    DOA_VALOR FLOAT NOT NULL,
    FK_FUNCIONARIOS_FUN_ID INTEGER
);

CREATE TABLE PLANEJAMENTOS_SEMANAIS (
    PLA_ID INTEGER AUTO_INCREMENT PRIMARY KEY UNIQUE,
    PLA_DATA_INICIO DATE NOT NULL,
    PLA_DATA_TERMINO DATE NOT NULL,
    FK_FUNCIONARIOS_FUN_ID INTEGER
);

CREATE TABLE CONTAS_MENSAIS (
    CON_ID INTEGER AUTO_INCREMENT PRIMARY KEY UNIQUE,
    CON_STATUS BOOLEAN NOT NULL,
    CON_DESCRICAO VARCHAR(100),
    CON_VALOR FLOAT NOT NULL,
    CON_MES_REFERENCIA INTEGER NOT NULL,
    CON_ANO_REFERENCIA INTEGER NOT NULL,
    CON_VENCIMENTO DATE NOT NULL,
    FK_TIPOS_SERVICOS_SER_ID INTEGER,
    FK_FUNCIONARIOS_FUN_ID INTEGER
);

CREATE TABLE PAGAMENTOS_IDOSOS (
    PAG_ID INTEGER AUTO_INCREMENT PRIMARY KEY UNIQUE,
    PAG_PLANO_TIPO INTEGER NOT NULL,
    PAG_TIPO_PAGAMENTO INTEGER NOT NULL,
    PAG_VALOR DECIMAL(10,2) NOT NULL,
    PAG_ANO INTEGER NOT NULL,
    PAG_MES INTEGER NOT NULL,
    PAG_DATA_VENCIMENTO DATE NOT NULL,
    FK_IDOSOS_IDO_ID INTEGER,
    FK_FUNCIONARIOS_FUN_ID INTEGER
);

CREATE TABLE SETORES_INSTITUICAO (
    SET_ID INTEGER AUTO_INCREMENT PRIMARY KEY UNIQUE,
    SET_NOME VARCHAR(80) NOT NULL
);

CREATE TABLE FUNCIONARIOS (
    FUN_ID INTEGER AUTO_INCREMENT PRIMARY KEY,
    FUN_NOME VARCHAR(100) NOT NULL,
    FUN_CPF INTEGER(11) NOT NULL,
    FUN_STATUS BOOLEAN NOT NULL,
    FUN_DATA_ENTRADA DATE NOT NULL,
    FUN_DATA_NASC DATE NOT NULL,
    LIM_RESPONSAVEL BOOLEAN NOT NULL,
    UNIQUE (FUN_ID, FUN_CPF)
);

CREATE TABLE SALARIOS_FUNCIONARIOS (
    SAL_ID INTEGER AUTO_INCREMENT PRIMARY KEY UNIQUE,
    SAL_MES INTEGER NOT NULL,
    SAL_SALARIO DECIMAL(10,2) NOT NULL,
    SAL_DESCONTO DECIMAL(10,2) NOT NULL,
    SAL_ANO INTEGER NOT NULL,
    SAL_BONUS DECIMAL(10,2) NOT NULL,
    FK_FUNCIONARIOS_FUN_ID INTEGER
);

CREATE TABLE TIPOS_SERVICOS (
    SER_ID INTEGER AUTO_INCREMENT PRIMARY KEY UNIQUE,
    SER_NOME VARCHAR(80) NOT NULL
);

CREATE TABLE IDOSOS (
    IDO_ID INTEGER AUTO_INCREMENT PRIMARY KEY UNIQUE
);
 
ALTER TABLE TAREFAS_LIMPEZA ADD CONSTRAINT FK_TAREFAS_LIMPEZA_2
    FOREIGN KEY (FK_PLANEJAMENTOS_SEMANAIS_PLA_ID)
    REFERENCES PLANEJAMENTOS_SEMANAIS (PLA_ID)
    ON DELETE RESTRICT;
 
ALTER TABLE TAREFAS_LIMPEZA ADD CONSTRAINT FK_TAREFAS_LIMPEZA_3
    FOREIGN KEY (FK_FUNCIONARIOS_FUN_ID)
    REFERENCES FUNCIONARIOS (FUN_ID)
    ON DELETE RESTRICT;
 
ALTER TABLE TAREFAS_LIMPEZA ADD CONSTRAINT FK_TAREFAS_LIMPEZA_4
    FOREIGN KEY (FK_SETORES_INSTITUICAO_SET_ID)
    REFERENCES SETORES_INSTITUICAO (SET_ID)
    ON DELETE CASCADE;
 
ALTER TABLE DOACOES ADD CONSTRAINT FK_DOACOES_2
    FOREIGN KEY (FK_FUNCIONARIOS_FUN_ID)
    REFERENCES FUNCIONARIOS (FUN_ID)
    ON DELETE SET NULL;
 
ALTER TABLE PLANEJAMENTOS_SEMANAIS ADD CONSTRAINT FK_PLANEJAMENTOS_SEMANAIS_2
    FOREIGN KEY (FK_FUNCIONARIOS_FUN_ID)
    REFERENCES FUNCIONARIOS (FUN_ID)
    ON DELETE CASCADE;
 
ALTER TABLE CONTAS_MENSAIS ADD CONSTRAINT FK_CONTAS_MENSAIS_2
    FOREIGN KEY (FK_TIPOS_SERVICOS_SER_ID)
    REFERENCES TIPOS_SERVICOS (SER_ID)
    ON DELETE CASCADE;
 
ALTER TABLE CONTAS_MENSAIS ADD CONSTRAINT FK_CONTAS_MENSAIS_3
    FOREIGN KEY (FK_FUNCIONARIOS_FUN_ID)
    REFERENCES FUNCIONARIOS (FUN_ID)
    ON DELETE CASCADE;
 
ALTER TABLE PAGAMENTOS_IDOSOS ADD CONSTRAINT FK_PAGAMENTOS_IDOSOS_2
    FOREIGN KEY (FK_IDOSOS_IDO_ID)
    REFERENCES IDOSOS (IDO_ID)
    ON DELETE CASCADE;
 
ALTER TABLE PAGAMENTOS_IDOSOS ADD CONSTRAINT FK_PAGAMENTOS_IDOSOS_3
    FOREIGN KEY (FK_FUNCIONARIOS_FUN_ID)
    REFERENCES FUNCIONARIOS (FUN_ID)
    ON DELETE CASCADE;
 
ALTER TABLE SALARIOS_FUNCIONARIOS ADD CONSTRAINT FK_SALARIOS_FUNCIONARIOS_2
    FOREIGN KEY (FK_FUNCIONARIOS_FUN_ID)
    REFERENCES FUNCIONARIOS (FUN_ID)
    ON DELETE CASCADE;