/* BDD_logico_mod03: */

CREATE TABLE EXAMES (
    EXA_ESTADO VARCHAR(10) NOT NULL,
    EXA_HORÁRIO DATETIME NOT NULL,
    EXA_NOME VARCHAR(70) NOT NULL,
    EXA_ID INTEGER NOT NULL,
    EXA_DATA_CRIACAO DATETIME NOT NULL,
    FK_CONSULTAS_ONLINE_CTO_ID INTEGER NOT NULL,
    CTO_ID INTEGER NOT NULL,
    EXA_ID INTEGER NOT NULL,
    PRIMARY KEY (EXA_ID, CTO_ID)
);

CREATE TABLE CONSULTAS_ONLINE (
    CTO_DATA DATE NOT NULL,
    CTO_ID INTEGER NOT NULL PRIMARY KEY,
    CTO_LOCAL VARCHAR(30)NOT NULL,
    CTO_NIVEL_PRIORIDADE VARCHAR(20)NOT NULL,
    CTO_DIAGNOSTICO VARCHAR(90)NOT NULL,
    CTO_MEDICAMENTOS_PRESCRITOS VARCHAR(100)NOT NULL,
    CTO_OBSERVACOES VARCHAR(50)NULL,
    FK_PACIENTES_PAC_ID INTEGER NOT NULL
);

CREATE TABLE MEDICOS (
    MED_NOME VARCHAR(100) NOT NULL,
    MED_ID INTEGERNOT NULL PRIMARY KEY,
    MED_CRM INTEGER NOT NULL
);

CREATE TABLE PACIENTES (
    PAC_CPF INTEGER(11)NOT NULL,
    PAC_NOME VARCHAR(90)NOT NULL,
    PAC_ID INTEGER NOT NULL PRIMARY KEY,
    FK_EXAMES_EXA_ID INTEGER NOT NULL,
    FK_EXAMES_CTO_ID INTEGER NOT NULL
);

CREATE TABLE SECRETARIA(O) (
    SEC_NOME VARCHAR(90) NOT NULL,
    SEC_ID INTEGER NOT NULL,
    FK_CONSULTAS_ONLINE_CTO_ID INTEGER NOT NULL,
    SEC_ID INTEGER NOT NULL,
    CTO_ID INTEGER NOT NULL,
    FK_EXAMES_EXA_ID INTEGER NOT NULL,
    FK_EXAMES_CTO_ID INTEGER NOT NULL,
    PRIMARY KEY (SEC_ID, SEC_ID)
);

CREATE TABLE PRODUTOS (
    PRO_NOME VARCHAR(100)NOT NULL,
    PRO_ID INTEGER NOT NULL PRIMARY KEY,
    PRO_VALOR DECIMAL(5,2)NOT NULL
);

CREATE TABLE FORNECEDORES (
    FOR_NOME VARCHAR(90)NOT NULL,
    FOR_ID INTEGER NOT NULL PRIMARY KEY,
    FOR_TELEFONE INTEGER(11)NULL,
    FOR_EMAIL VARCHAR(15)NOT NULL,
    FOR_CNPJ VARCHAR(30)NOT NULL,
    FK_PRODUTOS_PRO_ID INTEGER NOT NULL
);

CREATE TABLE ENFERMEIROS (
    ENF_ID INTEGER NOT NUL PRIMARY KEY,
    ENF_NOME VARCHAR(70) NOT NULL,
    ENF_CRM INTEGER NOT NULL
);

CREATE TABLE REALIZA (
    FK_MEDICOS_MED_ID INTEGERNOT NULL,
    FK_CONSULTAS_ONLINE_CTO_ID INTEGER NOT NULL,
    MED_NOME VARCHAR(70) NOT NULL,
    ID_MED INTEGER NOT NULL PRIMARY KEY,
    MED_CRM INTEGER NOT NULL
);

CREATE TABLE SOLICITA_PRODUTOS_MEDICOS_ENFERMEIROS (
    FK_PRODUTOS_PRO_ID INTEGER NOT NULL,
    FK_MEDICOS_MED_ID INTEGERNOT NULL,
    FK_ENFERMEIROS_ENF_ID INTEGER NOT NUL
);
 
ALTER TABLE EXAMES ADD CONSTRAINT FK_EXAMES_2
    FOREIGN KEY (FK_CONSULTAS_ONLINE_CTO_ID)
    REFERENCES CONSULTAS_ONLINE (CTO_ID)
    ON DELETE CASCADE;
 
ALTER TABLE CONSULTAS_ONLINE ADD CONSTRAINT FK_CONSULTAS_ONLINE_2
    FOREIGN KEY (FK_PACIENTES_PAC_ID)
    REFERENCES PACIENTES (PAC_ID)
    ON DELETE CASCADE;
 
ALTER TABLE PACIENTES ADD CONSTRAINT FK_PACIENTES_2
    FOREIGN KEY (FK_EXAMES_EXA_ID, FK_EXAMES_CTO_ID)
    REFERENCES EXAMES (EXA_ID, CTO_ID)
    ON DELETE RESTRICT;
 
ALTER TABLE SECRETARIA(O) ADD CONSTRAINT FK_SECRETARIA(O)_2
    FOREIGN KEY (FK_CONSULTAS_ONLINE_CTO_ID)
    REFERENCES CONSULTAS_ONLINE (CTO_ID)
    ON DELETE CASCADE;
 
ALTER TABLE SECRETARIA(O) ADD CONSTRAINT FK_SECRETARIA(O)_3
    FOREIGN KEY (FK_EXAMES_EXA_ID, FK_EXAMES_CTO_ID)
    REFERENCES EXAMES (EXA_ID, CTO_ID)
    ON DELETE RESTRICT;
 
ALTER TABLE FORNECEDORES ADD CONSTRAINT FK_FORNECEDORES_2
    FOREIGN KEY (FK_PRODUTOS_PRO_ID)
    REFERENCES PRODUTOS (PRO_ID)
    ON DELETE RESTRICT;
 
ALTER TABLE REALIZA ADD CONSTRAINT FK_REALIZA_2
    FOREIGN KEY (FK_MEDICOS_MED_ID)
    REFERENCES MEDICOS (MED_ID)
    ON DELETE RESTRICT;
 
ALTER TABLE REALIZA ADD CONSTRAINT FK_REALIZA_3
    FOREIGN KEY (FK_CONSULTAS_ONLINE_CTO_ID)
    REFERENCES CONSULTAS_ONLINE (CTO_ID)
    ON DELETE RESTRICT;
 
ALTER TABLE SOLICITA_PRODUTOS_MEDICOS_ENFERMEIROS ADD CONSTRAINT FK_SOLICITA_PRODUTOS_MEDICOS_ENFERMEIROS_1
    FOREIGN KEY (FK_PRODUTOS_PRO_ID)
    REFERENCES PRODUTOS (PRO_ID)
    ON DELETE RESTRICT;
 
ALTER TABLE SOLICITA_PRODUTOS_MEDICOS_ENFERMEIROS ADD CONSTRAINT FK_SOLICITA_PRODUTOS_MEDICOS_ENFERMEIROS_2
    FOREIGN KEY (FK_MEDICOS_MED_ID)
    REFERENCES MEDICOS (MED_ID)
    ON DELETE NO ACTION;
 
ALTER TABLE SOLICITA_PRODUTOS_MEDICOS_ENFERMEIROS ADD CONSTRAINT FK_SOLICITA_PRODUTOS_MEDICOS_ENFERMEIROS_3
    FOREIGN KEY (FK_ENFERMEIROS_ENF_ID)
    REFERENCES ENFERMEIROS (ENF_ID)
    ON DELETE NO ACTION;