CREATE DATABASE IF NOT EXISTS DIARIO_BORDO;
USE DIARIO_BORDO;

CREATE TABLE IF NOT EXISTS ALIMENTOS (
ALI_PORCAO DECIMAL (10,2) NOT NULL,
ALI_QUANTIDADE DECIMAL (10,2) NOT NULL,
ALI_GORDURA_TOTAL DECIMAL (10,2) NOT NULL,
ALI_GORDURA_SATURADA DECIMAL (10,2) NOT NULL,
ALI_GORDURA_TRANS DECIMAL (10,2) UNIQUE,
ALI_FIBRAS DECIMAL (10,2) UNIQUE,
ALI_SODIO DECIMAL (10,2) NOT NULL,
ALI_PROTEINAS DECIMAL (10,2) NOT NULL,
ALI_CODIGO INTEGER AUTO_INCREMENT PRIMARY KEY,
ALI_CARBOIDRATOS DECIMAL (10,2) NOT NULL,
ALI_CALORICAS DECIMAL (10,2) NOT NULL,
ALI_NOME VARCHAR(30) NOT NULL,
ALI_PESO DECIMAL (10,2) NOT NULL
);

CREATE TABLE IF NOT EXISTS DIARIOS_BORDO (
DIB_TOTAL_LANCHE_NOITE DECIMAL (10,2) NOT NULL,
DIB_TOTAL_JANTAR DECIMAL (10,2) NOT NULL,
DIB_TOTAL_CAFE_TARDE DECIMAL (10,2) NOT NULL,
DIB_TOTAL_LANCHE_TARDE DECIMAL (10,2) NOT NULL,
DIB_TOTAL_ALMOCO DECIMAL (10,2) NOT NULL,
DIB_DATA_CRIACAO DATETIME NOT NULL,
DIB_TOTAL_CAFE_MANHA DECIMAL (10,2) NOT NULL,
DIB_CODIGO INTEGER AUTO_INCREMENT PRIMARY KEY,
DIB_TOTAL_LANCHE_MANHA DECIMAL (10,2) NOT NULL,
DIB_TOTAL_DIA DECIMAL (10,2) NOT NULL,
USU_CODIGO INTEGER NOT NULL
);

CREATE TABLE IF NOT EXISTS USUARIOS (
USU_NOME VARCHAR(100) NOT NULL,
USU_DATA_NASCIMENTO DATE NOT NULL,
USU_EMAIL VARCHAR (255) NOT NULL,
USU_TIPO VARCHAR (30) NOT NULL,
USU_FOTO VARCHAR (30) NOT NULL,
USU_ENDERECO VARCHAR (100) NOT NULL,
USU_ALTURA DECIMAL (10,2) NOT NULL,
USU_GENERO VARCHAR (30) NOT NULL,
USU_AVISOS VARCHAR (30) NOT NULL,
USU_SENHA VARCHAR (50) NOT NULL,
USU_PESO DECIMAL (30) NOT NULL,
USU_CPF VARCHAR (15) UNIQUE,
USU_TELEFONE VARCHAR (20) NOT NULL,
USU_CODIGO INTEGER AUTO_INCREMENT PRIMARY KEY
);

CREATE TABLE IF NOT EXISTS DB_ALIMENTOS (
DBA_TOTAL_CALORIA DECIMAL (10,2) NOT NULL,
DBA_CODIGO INTEGER AUTO_INCREMENT PRIMARY KEY,
DBA_COD_REFEICAO INTEGER NOT NULL,
DBA_PORCAO_INTEIRA INTEGER NOT NULL,
DBA_PORCAO_FRACIONADA DECIMAL (10,2) NOT NULL,
DBA_HORARIO TIME NOT NULL,
ALI_CODIGO INTEGER NOT NULL,
DIB_CODIGO INTEGER NOT NULL,
FOREIGN KEY(ALI_CODIGO) REFERENCES ALIMENTOS (ALI_CODIGO),
FOREIGN KEY(DIB_CODIGO) REFERENCES DIARIOS_BORDO (DIB_CODIGO)
);

CREATE TABLE IF NOT EXISTS ALIMENTOS_FAVORITOS (
ALF_CODIGO INTEGER AUTO_INCREMENT PRIMARY KEY,
ALI_CODIGO INTEGER NOT NULL,
USU_CODIGO INTEGER NOT NULL,
FOREIGN KEY(ALI_CODIGO) REFERENCES ALIMENTOS (ALI_CODIGO),
FOREIGN KEY(USU_CODIGO) REFERENCES USUARIOS (USU_CODIGO)
);

CREATE TABLE IF NOT EXISTS PESOS_ALTURAS (
PEA_DATA_HORA_CADASTRO DATETIME NOT NULL,
PEA_ALTURA DECIMAL (10,2) NOT NULL,
PEA_PESO DECIMAL (10,2) NOT NULL,
PEA_CODIGO INTEGER AUTO_INCREMENT PRIMARY KEY,
USU_CODIGO INTEGER NOT NULL,
FOREIGN KEY(USU_CODIGO) REFERENCES USUARIOS (USU_CODIGO)
);

CREATE TABLE IF NOT EXISTS PLANO_ALIMENTAR_MOD7 (
PLA_CODIGO INTEGER AUTO_INCREMENT PRIMARY KEY,
PLA_CALORIAS_TOTAIS_PLANO DECIMAL (10,2) NOT NULL,
USU_CODIGO INTEGER NOT NULL,
FOREIGN KEY(USU_CODIGO) REFERENCES USUARIOS (USU_CODIGO)
);

ALTER TABLE DIARIOS_BORDO ADD FOREIGN KEY(USU_CODIGO) REFERENCES USUARIOS (USU_CODIGO);
