-- Geração de Modelo físico
-- Sql ANSI 2003 - brModelo.


CREATE TABLE REUNIOES_AGENDADAS (
REU_ID INTEGER AUTO_INCREMENT NOT NULL PRIMARY KEY,
REU_DATA_HORA DATETIME NOT NULL,
REU_REPRESENTANTES VARCHAR(100) NOT NULL,
REU_LOCAL VARCHAR(100) NOT NULL,
REU_ASSUNTO_PAUTADO VARCHAR(500) NOT NULL,
EST_ID INTEGER NOT NULL,
REC_ID INTEGER NOT NULL,
CON_ID INTEGER NOT NULL
);

CREATE TABLE RECLAMACOES (
REC_ID INTEGER AUTO_INCREMENT NOT NULL PRIMARY KEY,
REC_PONTUCAO_RECLAMACAO FLOAT NOT NULL,
REC_DATA_RECLAMACAO DATETIME NOT NULL,
REC_CONTEUDO_RECLAMACAO TEXT NOT NULL,
CON_ID INTEGER NOT NULL,
EST_ID INTEGER NOT NULL
);

CREATE TABLE RESPOSTA_RECLAMACAO (
RER_ID INTEGER AUTO_INCREMENT NOT NULL PRIMARY KEY,
RER_STATUS_RESOLVIDO BOOLEAN NOT NULL,
RER_DATA_HORA DATETIME NOT NULL,
REC_ID INTEGER NOT NULL,
FOREIGN KEY(REC_ID) REFERENCES RECLAMACOES (REC_ID)
);

CREATE TABLE FEEDBACKS (
FEE_DATA_HORA DATETIME NOT NULL,
FEE_ID INTEGER AUTO_INCREMENT NOT NULL PRIMARY KEY,
FEE_PROBLEMA TEXT NOT NULL,
FEE_SOLUCOES_DEFEINIDAS TEXT NOT NULL,
FEE_STATUS_RESOLVIDO BOOLEAN NOT NULL,
REU_ID INTEGER NOT NULL,
FOREIGN KEY(REU_ID) REFERENCES REUNIOES_AGENDADAS (REU_ID)
);

CREATE TABLE CONSUMIDORES (
CON_ID INTEGER AUTO_INCREMENT NOT NULL PRIMARY KEY,
CON_NOME VARCHAR(100) NOT NULL UNIQUE
);

CREATE TABLE TIPOS_ESTABELECIMENTOS (
TES_CATEGORIA VARCHAR(100) NOT NULL,
TES_ID INTEGER AUTO_INCREMENT NOT NULL PRIMARY KEY
);

CREATE TABLE ESTABELECIMENTOS (
EST_NOME_ESTABELECIMENTO VARCHAR(100) NOT NULL UNIQUE,
EST_DATA_CADASTRO DATETIME NOT NULL,
EST_ID INTEGER AUTO_INCREMENT NOT NULL PRIMARY KEY,
EST_PONTUACAO FLOAT NOT NULL,
TES_ID INTEGER NOT NULL,
FOREIGN KEY(TES_ID) REFERENCES TIPOS_ESTABELECIMENTOS (TES_ID)
);

CREATE TABLE HISTORICO_PONTUACAO (
HIP_ID INTEGER AUTO_INCREMENT NOT NULL PRIMARY KEY,
HIP_DATA_HORA DATETIME NOT NULL,
HIP_PONTUACAO FLOAT NOT NULL,
EST_ID INTEGER NOT NULL,
FOREIGN KEY(EST_ID) REFERENCES ESTABELECIMENTOS (EST_ID)
);

CREATE TABLE HISTORICO_POSICAO (
HIC_ID INTEGER AUTO_INCREMENT NOT NULL PRIMARY KEY,
HIC_COLOCACAO INTEGER NOT NULL,
HIC_DATA_HORA DATETIME NOT NULL,
EST_ID INTEGER NOT NULL,
FOREIGN KEY(EST_ID) REFERENCES ESTABELECIMENTOS (EST_ID)
);

ALTER TABLE REUNIOES_AGENDADAS ADD FOREIGN KEY(EST_ID) REFERENCES ESTABELECIMENTOS (EST_ID);
ALTER TABLE REUNIOES_AGENDADAS ADD FOREIGN KEY(REC_ID) REFERENCES RECLAMACOES (REC_ID);
ALTER TABLE REUNIOES_AGENDADAS ADD FOREIGN KEY(CON_ID) REFERENCES CONSUMIDORES (CON_ID);
ALTER TABLE RECLAMACOES ADD FOREIGN KEY(CON_ID) REFERENCES CONSUMIDORES (CON_ID);
ALTER TABLE RECLAMACOES ADD FOREIGN KEY(EST_ID) REFERENCES ESTABELECIMENTOS (EST_ID);
