-- Geração de Modelo físico
-- Sql ANSI 2003 - brModelo.



CREATE TABLE PUNICOES (
PUN_MOTIVO VARCHAR(200) NOT NULL,
PUN_DATA_HORA_PUNICAO DATETIME NOT NULL,
PUN_DURACAO_PUNICAO INTEGER,
PUN_ID INTEGER NOT NULL PRIMARY KEY,
COS_ID INTEGER NOT NULL
)

CREATE TABLE CONSUMIDORES (
COS_NOME_CONTATO VARCHAR(50),
COS_E-MAIL VARCHAR(30),
COS_ID INTEGER PRIMARY KEY
)

CREATE TABLE CONTATOS (
CON_ASSUNTO VARCHAR(30) NOT NULL,
CON_DATA_HORA_ENVIO DATETIME NOT NULL,
CON_DATA_HORA_RESPOSTA DATETIME NOT NULL,
CON_RESPONDIDO BOOLEAN NOT NULL,
CON_TEXTO VARCHAR(200) NOT NULL,
CON_ID INTEGER NOT NULL PRIMARY KEY,
COS_ID INTEGER NOT NULL,
ADM_ID INTEGER NOT NULL,
FOREIGN KEY(COS_ID) REFERENCES CONSUMIDORES (COS_ID)
)

CREATE TABLE ADMINISTRADORES (
ADM_DATA_REGISTRO DATE NOT NULL,
ADM_ULTIMA_VISITA DATETIME NOT NULL,
ADM_SENHA TEXTO(30) NOT NULL,
ADM_E-MAIL VARCHAR(30) NOT NULL,
ADM_NOME VARCHAR(50) NOT NULL,
ADM_ID INTEGER NOT NULL PRIMARY KEY
)

CREATE TABLE HISTORICO_ACESSO_ADMINISTRADOR (
HIS_PLATAFORMA VARCHAR(30) NOT NULL,
HIS_DATA_ULTIMO_ACESSO DATETIME NOT NULL,
HIS_ID INTEGER NOT NULL PRIMARY KEY,
ADM_ID INTEGER NOT NULL,
FOREIGN KEY(ADM_ID) REFERENCES ADMINISTRADORES (ADM_ID)
)

CREATE TABLE NOTIFICACOES_ADMINISTRADORES (
NOT_TITULO VARCHAR(30) NOT NULL,
NOT_DATA_HORA DATETIME NOT NULL,
NOT_ID INTEGER NOT NULL PRIMARY KEY,
TPN_ID INTEGER NOT NULL
)

CREATE TABLE TIPOS_PRODUTOS_SERVICOS (
PRS_PRODUTOS_SERVICOS VARCHAR(50) NOT NULL,
PRS_ID INTEGER NOT NULL PRIMARY KEY
)

CREATE TABLE TIPOS_RECLAMACOES (
TPR_CATEGORIA VARCHAR(30) NOT NULL,
TPR_ID INTEGER NOT NULL PRIMARY KEY
)

CREATE TABLE RESPOSTA_RECLAMACAO (
RES_AUTORIZADO BOOLEAN NOT NULL ,
RES_DATA_HORA_AUTORIZACAO DATETIME NOT NULL,
RES_ID INTEGER NOT NULL PRIMARY KEY,
NOT_ID INTEGER NOT NULL,
FOREIGN KEY(NOT_ID) REFERENCES NOTIFICACOES_ADMINISTRADORES (NOT_ID)
)

CREATE TABLE TIPOS_ESTABELECIMENTOS (
TES_CATEGORIA VARCHAR(30) NOT NULL,
TES_ID INTEGER NOT NULL PRIMARY KEY
)

CREATE TABLE DENUNCIA (
DEN_AUTORIZADO BOOLEAN NOT NULL,
DEN_JUSTIFICATIVA VARCHAR(500) NOT NULL,
DEN_MOTIVO INTEGER NOT NULL,
DEN_DATA_HORA_AUTORIZACAO DATETIME NOT NULL,
DEN_STATUS_APROVACAO BOOLEAN NOT NULL,
DEN_ID INTEGER NOT NULL PRIMARY KEY,
NOT_ID INTEGER NOT NULL,
FOREIGN KEY(NOT_ID) REFERENCES NOTIFICACOES_ADMINISTRADORES (NOT_ID)
)

CREATE TABLE TIPOS_NOTIFICACOES (
TPN_DESCRICAO VARCHAR(30) NOT NULL ,
TPN_ID INTEGER NOT NULL PRIMARY KEY
)

CREATE TABLE RECLAMACOES (
REC_RESPONDIDA BOOLEAN NOT NULL,
REC_TITULO_RECLAMACAO VARCHAR(50) NOT NULL,
REC_MOTIVO_EXCLUSAO VARCHAR(50) NOT NULL,
REC_AUTORIZADO BOOLEAN NOT NULL,
REC_LINK_IMAGEM VARCHAR(200) NOT NULL,
REC_DATA_HORA_AUTORIZACAO DATETIME NOT NULL,
REC_DESCRICAO TEXT NOT NULL,
REC_ID_RECLAMACAO INTEGER NOT NULL PRIMARY KEY,
NOT_ID INTEGER NOT NULL,
ADM_ID INTEGER NOT NULL,
FOREIGN KEY(NOT_ID) REFERENCES NOTIFICACOES_ADMINISTRADORES (NOT_ID),
FOREIGN KEY(ADM_ID) REFERENCES ADMINISTRADORES (ADM_ID)
)

CREATE TABLE TIPO_CRITERIOS_RECLAMACOES (
TCR_ID INTEGER NOT NULL PRIMARY KEY,
REC_ID_RECLAMACAO INTEGER NOT NULL,
TPR_ID INTEGER NOT NULL,
FOREIGN KEY(REC_ID_RECLAMACAO) REFERENCES RECLAMACOES (REC_ID_RECLAMACAO)/*falha: chave estrangeira*/
)

ALTER TABLE PUNICOES ADD FOREIGN KEY(COS_ID) REFERENCES CONSUMIDORES (COS_ID)
ALTER TABLE CONTATOS ADD FOREIGN KEY(ADM_ID) REFERENCES ADMINISTRADORES (ADM_ID)
ALTER TABLE NOTIFICACOES_ADMINISTRADORES ADD FOREIGN KEY(TPN_ID) REFERENCES TIPOS_NOTIFICACOES (TPN_ID)
