CREATE DATABASE GERACOES;
USE GERACOES;

CREATE TABLE USUARIOS (
    USU_ID INTEGER AUTO_INCREMENT PRIMARY KEY,
    USU_PRONTUARIO INTEGER,
    USU_RG VARCHAR(9) NOT NULL,
    USU_DATA_NASCIMENTO DATE NOT NULL,
    USU_EMAIL VARCHAR(255),
    USU_CELULAR VARCHAR(11),
    USU_TELEFONE VARCHAR(10),
    USU_ENDERECO VARCHAR(100) NOT NULL,
    USU_CEP VARCHAR(8) NOT NULL,
    USU_LOGRADOURO VARCHAR(255),
    USU_COMPLEMENTO VARCHAR(50),
    USU_FUNCAO INTEGER NOT NULL,
    USU_CPF VARCHAR(11) NOT NULL,
    USU_NOME VARCHAR(128) NOT NULL,
    USU_CONTA_ATIVA BOOLEAN,
    USU_SENHA_ACESSO VARCHAR(64) NOT NULL,
    FK_CIDADES_CID_ID INTEGER,
	USU_TOKEN VARCHAR(64) NULL,
	USU_TOKEN_DATE DATETIME(6) NULL,
    UNIQUE (USU_ID, USU_PRONTUARIO, USU_RG, USU_CPF, USU_EMAIL)
);

CREATE TABLE NUTRICIONISTAS (
    NUT_COD_PROFISSIONAL VARCHAR(8) NOT NULL,
    NUT_FORMACAO VARCHAR(255) NOT NULL,
    FK_USUARIOS_USU_ID INTEGER PRIMARY KEY
);

CREATE TABLE ENFERMEIROS (
    ENF_COD_PROFISSIONAL VARCHAR(8) NOT NULL,
    ENF_FORMACAO VARCHAR(255) NOT NULL,
    FK_USUARIOS_USU_ID INTEGER PRIMARY KEY
);

CREATE TABLE EDUCADORES_FISICOS (
    EDU_COD_PROFISSIONAL VARCHAR(8) NOT NULL,
    EDU_FORMACAO VARCHAR(255) NOT NULL,
    FK_USUARIOS_USU_ID INTEGER PRIMARY KEY
);

CREATE TABLE SETOR_LIMPEZA (
    SET_NIVEL INTEGER(1) NOT NULL,
    FK_USUARIOS_USU_ID INTEGER PRIMARY KEY
);

CREATE TABLE MEDICOS (
    MED_COD_PROFISSIONAL VARCHAR(8) NOT NULL,
    MED_FORMACAO VARCHAR(255) NOT NULL,
    FK_USUARIOS_USU_ID INTEGER PRIMARY KEY
);

CREATE TABLE GESTORES (
    GES_NIVEL INTEGER NOT NULL,
    FK_USUARIOS_USU_ID INTEGER PRIMARY KEY
);

CREATE TABLE DOACOES (
    DOA_DATA DATE,
    DOA_DOADOR VARCHAR(128) NOT NULL,
    DOA_ID INTEGER AUTO_INCREMENT PRIMARY KEY UNIQUE,
    DOP_PRODUTO VARCHAR(128),
    DOF_VALOR DOUBLE,
    DOACOES_TIPO INT,
    FK_GESTORES_FK_USUARIOS_USU_ID INTEGER
);

CREATE TABLE FISIOTERAPEUTAS (
    FIS_COD_PROFISSIONAL VARCHAR(8) NOT NULL,
    FIS_FORMACAO VARCHAR(255) NOT NULL,
    FK_USUARIOS_USU_ID INTEGER PRIMARY KEY
);

CREATE TABLE CIDADES (
    CID_ID INTEGER AUTO_INCREMENT PRIMARY KEY UNIQUE,
    CID_NOME VARCHAR(128) NOT NULL,
    FK_ESTADOS_EST_ID INTEGER
);

CREATE TABLE ESTADOS (
    EST_ID INTEGER AUTO_INCREMENT PRIMARY KEY UNIQUE,
    EST_SIGLA VARCHAR(2) NOT NULL,
    EST_NOME VARCHAR(50) NOT NULL
);

CREATE TABLE FEEDBACKS (
    FED_ID INTEGER AUTO_INCREMENT PRIMARY KEY UNIQUE,
    FED_MENSAGEM TEXT NOT NULL,
    FED_HORA TIME NOT NULL,
    FK_TIPOS_FEEDBACK_TFE_ID INTEGER,
    FK_USUARIOS_USU_ID INTEGER,
    FK_GESTORES_FK_USUARIOS_USU_ID INTEGER
);

CREATE TABLE TIPOS_FEEDBACK (
    TFE_ID INTEGER AUTO_INCREMENT PRIMARY KEY UNIQUE,
    TFE_TIPO VARCHAR(128)
);
 
ALTER TABLE USUARIOS ADD CONSTRAINT FK_USUARIOS_2
    FOREIGN KEY (FK_CIDADES_CID_ID)
    REFERENCES CIDADES (CID_ID)
    ON DELETE CASCADE;
 
ALTER TABLE NUTRICIONISTAS ADD CONSTRAINT FK_NUTRICIONISTAS_2
    FOREIGN KEY (FK_USUARIOS_USU_ID)
    REFERENCES USUARIOS (USU_ID)
    ON DELETE CASCADE;
 
ALTER TABLE ENFERMEIROS ADD CONSTRAINT FK_ENFERMEIROS_2
    FOREIGN KEY (FK_USUARIOS_USU_ID)
    REFERENCES USUARIOS (USU_ID)
    ON DELETE CASCADE;
 
ALTER TABLE EDUCADORES_FISICOS ADD CONSTRAINT FK_EDUCADORES_FISICOS_2
    FOREIGN KEY (FK_USUARIOS_USU_ID)
    REFERENCES USUARIOS (USU_ID)
    ON DELETE CASCADE;
 
ALTER TABLE SETOR_LIMPEZA ADD CONSTRAINT FK_SETOR_LIMPEZA_2
    FOREIGN KEY (FK_USUARIOS_USU_ID)
    REFERENCES USUARIOS (USU_ID)
    ON DELETE CASCADE;
 
ALTER TABLE MEDICOS ADD CONSTRAINT FK_MEDICOS_2
    FOREIGN KEY (FK_USUARIOS_USU_ID)
    REFERENCES USUARIOS (USU_ID)
    ON DELETE CASCADE;
 
ALTER TABLE GESTORES ADD CONSTRAINT FK_GESTORES_2
    FOREIGN KEY (FK_USUARIOS_USU_ID)
    REFERENCES USUARIOS (USU_ID)
    ON DELETE CASCADE;
 
ALTER TABLE DOACOES ADD CONSTRAINT FK_DOACOES_2
    FOREIGN KEY (FK_GESTORES_FK_USUARIOS_USU_ID)
    REFERENCES GESTORES (FK_USUARIOS_USU_ID)
    ON DELETE CASCADE;
 
ALTER TABLE FISIOTERAPEUTAS ADD CONSTRAINT FK_FISIOTERAPEUTAS_2
    FOREIGN KEY (FK_USUARIOS_USU_ID)
    REFERENCES USUARIOS (USU_ID)
    ON DELETE CASCADE;
 
ALTER TABLE CIDADES ADD CONSTRAINT FK_CIDADES_2
    FOREIGN KEY (FK_ESTADOS_EST_ID)
    REFERENCES ESTADOS (EST_ID)
    ON DELETE CASCADE;
 
ALTER TABLE FEEDBACKS ADD CONSTRAINT FK_FEEDBACKS_2
    FOREIGN KEY (FK_TIPOS_FEEDBACK_TFE_ID)
    REFERENCES TIPOS_FEEDBACK (TFE_ID)
    ON DELETE CASCADE;
 
ALTER TABLE FEEDBACKS ADD CONSTRAINT FK_FEEDBACKS_3
    FOREIGN KEY (FK_USUARIOS_USU_ID)
    REFERENCES USUARIOS (USU_ID)
    ON DELETE CASCADE;
 
ALTER TABLE FEEDBACKS ADD CONSTRAINT FK_FEEDBACKS_4
    FOREIGN KEY (FK_GESTORES_FK_USUARIOS_USU_ID)
    REFERENCES GESTORES (FK_USUARIOS_USU_ID)
    ON DELETE CASCADE;