/* Lógico_Mod4: */

CREATE TABLE MEDICOS (
    MED_ID INTEGER,
    MED_PRONTUARIO VARCHAR(6) PRIMARY KEY,
    MED_NOMEMEDICO VARCHAR(50)
);

CREATE TABLE PACIENTES (
    PCT_NOMEPACIENTE VARCHAR(50),
    PCT_CPF VARCHAR(11),
    PCT_PRONTUARIO VARCHAR(6),
    PCT_ID INTEGER,
    PRIMARY KEY (PCT_CPF, PCT_PRONTUARIO)
);

CREATE TABLE ENFERMEIROS (
    ENF_NOMEENFERMEIRO VARCHAR(50),
    ENF_PRONTUARIO VARCHAR(6) PRIMARY KEY,
    ENF_ID INTEGER
);

CREATE TABLE ADMINISTRADORES (
    ADM_NOMEADMINISTRADORES VARCHAR(50),
    ADM_PRONTUARIO VARCHAR(6) PRIMARY KEY,
    ADM_ID INTEGER
);

CREATE TABLE TRIAGENS (
    TR_ID INTEGER,
    TR_PRESSAOSISTOLICA INTEGER,
    TR_PRESSAODIASTOLICA INTEGER,
    TR_PESO DECIMAL(4,2),
    TR_ALTURA DECIMAL(3,1),
    TR_SINTOMAS VARCHAR(200),
    TR_TEMPERATURA DECIMAL(3,1),
    TR_ALERGIAS VARCHAR(150),
    TR_INFORMACOESADICIONAIS VARCHAR(100),
    TR_ATENDIMENTOPREFERENCIAL BOOLEAN,
    TR_ENDERECO_SETOR VARCHAR(30),
    TR_HORA_TRIAGEM TIME,
    FK_ENFERMEIROS_ENF_PRONTUARIO VARCHAR(6),
    FK_CONSULTAS_PRESENCIAIS_CON_ID INTEGER
);

CREATE TABLE INTERNACOES_MEDICAS (
    INM_TEMPOINTERNACAO INTEGER,
    INM_ID INTEGER PRIMARY KEY,
    INM_CAUSAINTERNACAO VARCHAR(100),
    INM_PRESCRICAOMEDICA VARCHAR(255),
    INM_ACOMPANHAMENTOCLINICO VARCHAR(50),
    INM_NECESSIDADESCLINICAS VARCHAR(100),
    FK_CONSULTAS_PRESENCIAIS_CON_ID INTEGER
);

CREATE TABLE EXAMES_MEDICOS (
    EX_ID INTEGER PRIMARY KEY,
    FK_CONSULTAS_PRESENCIAIS_CON_ID INTEGER
);

CREATE TABLE PRESCRICOES_MEDICAS (
    PM_ID INTEGER PRIMARY KEY,
    PM_URL_ARQUIVO_PRESCRICAO_MEDICA VARCHAR(255),
    FK_CONSULTAS_PRESENCIAIS_CON_ID INTEGER
);

CREATE TABLE CONSULTAS_PRESENCIAIS (
    CON_ID INTEGER PRIMARY KEY,
    CON_DATA_ATEDIMENTO DATE,
    CON_HORA_ATENDIMENTO TIME,
    CON_DESCRICAO VARCHAR(250),
    CON_RETORNO BOOLEAN,
    CON_DATA_RETORNO DATE,
    FK_PACIENTES_PCT_CPF VARCHAR(11),
    FK_PACIENTES_PCT_PRONTUARIO VARCHAR(6),
    FK_MEDICOS_MED_PRONTUARIO VARCHAR(6)
);

CREATE TABLE REMEDIOS (
    REM_ID INTEGER PRIMARY KEY,
    REM_NOME VARCHAR(50),
    FK_PRESCRICOES_MEDICAS_PM_ID INTEGER,
    PRR_PERIODO_DIAS INTEGER,
    PRR_PERIODICIDADE_HORAS INTEGER
);
 
ALTER TABLE TRIAGENS ADD CONSTRAINT FK_TRIAGENS_1
    FOREIGN KEY (FK_ENFERMEIROS_ENF_PRONTUARIO)
    REFERENCES ENFERMEIROS (ENF_PRONTUARIO)
    ON DELETE CASCADE;
 
ALTER TABLE TRIAGENS ADD CONSTRAINT FK_TRIAGENS_2
    FOREIGN KEY (FK_CONSULTAS_PRESENCIAIS_CON_ID)
    REFERENCES CONSULTAS_PRESENCIAIS (CON_ID)
    ON DELETE CASCADE;
 
ALTER TABLE INTERNACOES_MEDICAS ADD CONSTRAINT FK_INTERNACOES_MEDICAS_2
    FOREIGN KEY (FK_CONSULTAS_PRESENCIAIS_CON_ID)
    REFERENCES CONSULTAS_PRESENCIAIS (CON_ID)
    ON DELETE CASCADE;
 
ALTER TABLE EXAMES_MEDICOS ADD CONSTRAINT FK_EXAMES_MEDICOS_2
    FOREIGN KEY (FK_CONSULTAS_PRESENCIAIS_CON_ID)
    REFERENCES CONSULTAS_PRESENCIAIS (CON_ID)
    ON DELETE CASCADE;
 
ALTER TABLE PRESCRICOES_MEDICAS ADD CONSTRAINT FK_PRESCRICOES_MEDICAS_2
    FOREIGN KEY (FK_CONSULTAS_PRESENCIAIS_CON_ID)
    REFERENCES CONSULTAS_PRESENCIAIS (CON_ID)
    ON DELETE CASCADE;
 
ALTER TABLE CONSULTAS_PRESENCIAIS ADD CONSTRAINT FK_CONSULTAS_PRESENCIAIS_2
    FOREIGN KEY (FK_PACIENTES_PCT_CPF, FK_PACIENTES_PCT_PRONTUARIO)
    REFERENCES PACIENTES (PCT_CPF, PCT_PRONTUARIO)
    ON DELETE CASCADE;
 
ALTER TABLE CONSULTAS_PRESENCIAIS ADD CONSTRAINT FK_CONSULTAS_PRESENCIAIS_3
    FOREIGN KEY (FK_MEDICOS_MED_PRONTUARIO)
    REFERENCES MEDICOS (MED_PRONTUARIO)
    ON DELETE CASCADE;
 
ALTER TABLE REMEDIOS ADD CONSTRAINT FK_REMEDIOS_2
    FOREIGN KEY (FK_PRESCRICOES_MEDICAS_PM_ID)
    REFERENCES PRESCRICOES_MEDICAS (PM_ID)
    ON DELETE CASCADE;