/* BDD_Modulo2-logico: */

CREATE TABLE MEDICOS (
    MED_NOME VARCHAR(200) NOT NULL UNIQUE,
    MED_ESPECIALIDADE VARCHAR(50) NOT NULL,
    MED_ID INTEGER AUTO_INCREMENT PRIMARY KEY
);

CREATE TABLE PACIENTES (
    PAC_ID INTEGER AUTO_INCREMENT PRIMARY KEY,
    PAC_TELEFONE VARCHAR(11),
    PAC_ESTADO VARCHAR(20),
    PAC_FOTO VARCHAR(255),
    PAC_NOME VARCHAR(200) NOT NULL,
    PAC_CPF VARCHAR(11) NOT NULL UNIQUE,
    PAC_CIDADE VARCHAR(50),
    PAC_ENDERECO VARCHAR(100),
    PAC_DATA_NASCIMENTO DATE,
    PAC_EMAIL VARCHAR(35) UNIQUE
);

CREATE TABLE SECRETARIOS (
    SEC_ID INTEGER AUTO_INCREMENT PRIMARY KEY,
    SEC_NOME VARCHAR(200) NOT NULL
);

CREATE TABLE CONSULTAS_ONLINE (
    CTO_DATA DATE NOT NULL,
    CTO_ID INTEGER AUTO_INCREMENT PRIMARY KEY,
    CTO_HORA_INICIO TIME,
    CTO_DIAGNOSTICO VARCHAR(1000),
    CTO_PRESCRICAO VARCHAR(200),
    CTO_OBSERVACOES VARCHAR(1000),
    CTO_HORA_TERMINO TIME,
    CTO_STATUS INTEGER,
    CTO_LINK_MEET VARCHAR(255) UNIQUE,
    CTO_JUSTIFICATIVA VARCHAR(500),
    FK_PACIENTES_PAC_ID INTEGER,
    FK_MEDICOS_MED_ID INTEGER,
    FK_SOLICITACAO_AGEND_CON_ONLINE_SOL_ID INTEGER
);

CREATE TABLE TRIAGEM_C_ONLINE (
    TRO_COLESTEROL INTEGER,
    TRO_DIARREIA BOOLEAN,
    TRO_VOMITO BOOLEAN,
    TRO_TOSSE BOOLEAN,
    TRO_DOR_DE_CABECA BOOLEAN,
    TRO_FALTA_DE_AR BOOLEAN,
    TRO_FEBRE BOOLEAN,
    TRO_DOR_NO_CORPO BOOLEAN,
    TRO_DOR_DE_GARGANTA BOOLEAN,
    TRO_DIABETES INTEGER,
    TRO_CORIZA BOOLEAN,
    TRO_LESAO INTEGER,
    TRO_PESO INTEGER,
    TRO_ID INTEGER AUTO_INCREMENT PRIMARY KEY,
    TRO_HIPERTENSAO INTEGER,
    FK_SECRETARIOS_SEC_ID INTEGER,
    FK_CONSULTAS_ONLINE_CTO_ID INTEGER
);

CREATE TABLE SOLICITACAO_AGEND_CON_ONLINE (
    SOL_DATA DATE,
    SOL_ID  INTEGER AUTO_INCREMENT PRIMARY KEY,
    SOL_STATUS INTEGER,
    SOL_HORARIO TIME,
    FK_PACIENTES_PAC_ID INTEGER,
    FK_ESPECIALIDADES_ESP_ID INTEGER
);

CREATE TABLE ESPECIALIDADES (
    ESP_ID INTEGER AUTO_INCREMENT NOT NULL PRIMARY KEY,
    ESP_NOME VARCHAR(50) NOT NULL
);

CREATE TABLE ENCAMINHAMENTO_CONSULTA_PRESENCIAL (
    ENP_ID  INTEGER AUTO_INCREMENT PRIMARY KEY,
    ENP_DATA DATE,
    ENP_HORARIO TIME,
    ENP_ESPECIALISTA VARCHAR(50),
    ENP_SINTOMAS VARCHAR(250),
    ENP_DIAGNOSTICO VARCHAR(1000),
    ENP_PRESCRICAO VARCHAR(200),
    ENP_OBSERVACOES VARCHAR(1000),
    FK_CONSULTAS_ONLINE_CTO_ID INTEGER
);

CREATE TABLE GERENCIA_SOL (
    FK_SECRETARIOS_SEC_ID INTEGER,
    FK_SOLICITACAO_AGEND_CON_ONLINE_SOL_ID INTEGER
);

CREATE TABLE ESP_MEDICO (
    FK_MEDICOS_MED_ID INTEGER  AUTO_INCREMENT,
    FK_ESPECIALIDADES_ESP_ID INTEGER,
    ESM_ID INTEGER AUTO_INCREMENT PRIMARY KEY
);
 
ALTER TABLE CONSULTAS_ONLINE ADD CONSTRAINT FK_CONSULTAS_ONLINE_2
    FOREIGN KEY (FK_PACIENTES_PAC_ID)
    REFERENCES PACIENTES (PAC_ID)
    ON DELETE CASCADE;
 
ALTER TABLE CONSULTAS_ONLINE ADD CONSTRAINT FK_CONSULTAS_ONLINE_3
    FOREIGN KEY (FK_MEDICOS_MED_ID)
    REFERENCES MEDICOS (MED_ID)
    ON DELETE CASCADE;
 
ALTER TABLE CONSULTAS_ONLINE ADD CONSTRAINT FK_CONSULTAS_ONLINE_4
    FOREIGN KEY (FK_SOLICITACAO_AGEND_CON_ONLINE_SOL_ID)
    REFERENCES SOLICITACAO_AGEND_CON_ONLINE (SOL_ID )
    ON DELETE CASCADE;
 
ALTER TABLE TRIAGEM_C_ONLINE ADD CONSTRAINT FK_TRIAGEM_C_ONLINE_2
    FOREIGN KEY (FK_SECRETARIOS_SEC_ID)
    REFERENCES SECRETARIOS (SEC_ID)
    ON DELETE CASCADE;
 
ALTER TABLE TRIAGEM_C_ONLINE ADD CONSTRAINT FK_TRIAGEM_C_ONLINE_3
    FOREIGN KEY (FK_CONSULTAS_ONLINE_CTO_ID)
    REFERENCES CONSULTAS_ONLINE (CTO_ID)
    ON DELETE CASCADE;
 
ALTER TABLE SOLICITACAO_AGEND_CON_ONLINE ADD CONSTRAINT FK_SOLICITACAO_AGEND_CON_ONLINE_2
    FOREIGN KEY (FK_PACIENTES_PAC_ID)
    REFERENCES PACIENTES (PAC_ID)
    ON DELETE CASCADE;
 
ALTER TABLE SOLICITACAO_AGEND_CON_ONLINE ADD CONSTRAINT FK_SOLICITACAO_AGEND_CON_ONLINE_3
    FOREIGN KEY (FK_ESPECIALIDADES_ESP_ID)
    REFERENCES ESPECIALIDADES (ESP_ID)
    ON DELETE CASCADE;
 
ALTER TABLE ENCAMINHAMENTO_CONSULTA_PRESENCIAL ADD CONSTRAINT FK_ENCAMINHAMENTO_CONSULTA_PRESENCIAL_2
    FOREIGN KEY (FK_CONSULTAS_ONLINE_CTO_ID)
    REFERENCES CONSULTAS_ONLINE (CTO_ID)
    ON DELETE CASCADE;
 
ALTER TABLE GERENCIA_SOL ADD CONSTRAINT FK_GERENCIA_SOL_1
    FOREIGN KEY (FK_SECRETARIOS_SEC_ID)
    REFERENCES SECRETARIOS (SEC_ID)
    ON DELETE RESTRICT;
 
ALTER TABLE GERENCIA_SOL ADD CONSTRAINT FK_GERENCIA_SOL_2
    FOREIGN KEY (FK_SOLICITACAO_AGEND_CON_ONLINE_SOL_ID)
    REFERENCES SOLICITACAO_AGEND_CON_ONLINE (SOL_ID )
    ON DELETE SET NULL;
 
ALTER TABLE ESP_MEDICO ADD CONSTRAINT FK_ESP_MEDICO_2
    FOREIGN KEY (FK_MEDICOS_MED_ID)
    REFERENCES MEDICOS (MED_ID)
    ON DELETE RESTRICT;
 
ALTER TABLE ESP_MEDICO ADD CONSTRAINT FK_ESP_MEDICO_3
    FOREIGN KEY (FK_ESPECIALIDADES_ESP_ID)
    REFERENCES ESPECIALIDADES (ESP_ID)
    ON DELETE RESTRICT;