/* DER_MOD4: */

CREATE TABLE USUARIOS (
    USU_STATUS INTEGER,
    USU_TIPO_USUARIO INTEGER,
    USU_ID INTEGER AUTO_INCREMENT PRIMARY KEY
);

CREATE TABLE ANUNCIOS (
    ANU_TEXTO VARCHAR(300),
    ANU_ID INTENGER AUTO_INCREMENT PRIMARY KEY,
    ANU_MIDIA VARCHAR(600),
    ANU_MIC_ID INTENGER,
    FK_USUARIOS_USU_ID INTEGER
);

CREATE TABLE COMENTARIOS (
    COM_ID INTENGER AUTO_INCREMENT PRIMARY KEY,
    COM_DATA DATETIME,
    COM_TEXTO VARCHAR(300),
    FK_USUARIOS_USU_ID INTEGER,
    FK_POSTAGENS_POS_ID INTENGER
);

CREATE TABLE POSTAGENS (
    POS_MIDIA VARCHAR(600),
    POS_ID INTENGER AUTO_INCREMENT PRIMARY KEY,
    POS_DATA DATETIME,
    POS_TEXTO VARCHAR(300),
    FK_USUARIOS_USU_ID INTEGER
);

CREATE TABLE DENUNCIAS (
    DEN_ID INTENGER AUTO_INCREMENT PRIMARY KEY,
    DEN_MOTIVO CHECKBOX,
    DEN_DATA DATE,
    FK_POSTAGENS_POS_ID INTENGER,
    FK_USUARIOS_USU_ID INTEGER
);

CREATE TABLE EVENTOS (
    EVE_NOME VARCHAR(100),
    EVE_ID INTENGER AUTO_INCREMENT PRIMARY KEY,
    EVE_LOCAL VARCHAR(600),
    EVE_DATA DATETIME,
    EVE_MIDIA VARCHAR(600),
    FK_USUARIOS_USU_ID INTEGER
);

CREATE TABLE AVALIACOES (
    AVA_NOTA DOUBLE,
    AVA_ID INTENGER AUTO_INCREMENT PRIMARY KEY,
    FK_USUARIOS_USU_ID INTEGER,
    FK_MICROCERVEJEIRAS_MIC_ID INTENGER
);

CREATE TABLE MICROCERVEJEIRAS (
    MIC_ID INTENGER AUTO_INCREMENT PRIMARY KEY
);

CREATE TABLE MENSAGENS (
    FK_USUARIOS_USU_ID INTEGER,
    FK_USUARIOS_USU_ID_ INTEGER,
    MEN_MIDIA VARCHAR,
    MEN_TEXTO VARCHAR(300),
    MEN_DATA DATETIME,
    MEN_ID INTEGER AUTO_INCREMENT PRIMARY KEY
);

CREATE TABLE BRINDAR_POSTAGEM (
    FK_POSTAGENS_POS_ID INTENGER,
    FK_USUARIOS_USU_ID INTEGER,
    BRP_ID INTEGER AUTO_INCREMENT PRIMARY KEY
);
 
ALTER TABLE ANUNCIOS ADD CONSTRAINT FK_ANUNCIOS_2
    FOREIGN KEY (FK_USUARIOS_USU_ID)
    REFERENCES USUARIOS (USU_ID)
    ON DELETE CASCADE;
 
ALTER TABLE COMENTARIOS ADD CONSTRAINT FK_COMENTARIOS_2
    FOREIGN KEY (FK_USUARIOS_USU_ID)
    REFERENCES USUARIOS (USU_ID)
    ON DELETE CASCADE;
 
ALTER TABLE COMENTARIOS ADD CONSTRAINT FK_COMENTARIOS_3
    FOREIGN KEY (FK_POSTAGENS_POS_ID)
    REFERENCES POSTAGENS (POS_ID)
    ON DELETE CASCADE;
 
ALTER TABLE POSTAGENS ADD CONSTRAINT FK_POSTAGENS_2
    FOREIGN KEY (FK_USUARIOS_USU_ID)
    REFERENCES USUARIOS (USU_ID)
    ON DELETE CASCADE;
 
ALTER TABLE DENUNCIAS ADD CONSTRAINT FK_DENUNCIAS_2
    FOREIGN KEY (FK_POSTAGENS_POS_ID)
    REFERENCES POSTAGENS (POS_ID)
    ON DELETE CASCADE;
 
ALTER TABLE DENUNCIAS ADD CONSTRAINT FK_DENUNCIAS_3
    FOREIGN KEY (FK_USUARIOS_USU_ID)
    REFERENCES USUARIOS (USU_ID)
    ON DELETE CASCADE;
 
ALTER TABLE EVENTOS ADD CONSTRAINT FK_EVENTOS_2
    FOREIGN KEY (FK_USUARIOS_USU_ID)
    REFERENCES USUARIOS (USU_ID)
    ON DELETE CASCADE;
 
ALTER TABLE AVALIACOES ADD CONSTRAINT FK_AVALIACOES_2
    FOREIGN KEY (FK_USUARIOS_USU_ID)
    REFERENCES USUARIOS (USU_ID)
    ON DELETE CASCADE;
 
ALTER TABLE AVALIACOES ADD CONSTRAINT FK_AVALIACOES_3
    FOREIGN KEY (FK_MICROCERVEJEIRAS_MIC_ID)
    REFERENCES MICROCERVEJEIRAS (MIC_ID)
    ON DELETE CASCADE;
 
ALTER TABLE MENSAGENS ADD CONSTRAINT FK_MENSAGENS_1
    FOREIGN KEY (FK_USUARIOS_USU_ID)
    REFERENCES USUARIOS (USU_ID)
    ON DELETE CASCADE;
 
ALTER TABLE MENSAGENS ADD CONSTRAINT FK_MENSAGENS_2
    FOREIGN KEY (FK_USUARIOS_USU_ID_)
    REFERENCES USUARIOS (USU_ID)
    ON DELETE CASCADE;
 
ALTER TABLE BRINDAR_POSTAGEM ADD CONSTRAINT FK_BRINDAR_POSTAGEM_2
    FOREIGN KEY (FK_POSTAGENS_POS_ID)
    REFERENCES POSTAGENS (POS_ID)
    ON DELETE SET NULL;
 
ALTER TABLE BRINDAR_POSTAGEM ADD CONSTRAINT FK_BRINDAR_POSTAGEM_3
    FOREIGN KEY (FK_USUARIOS_USU_ID)
    REFERENCES USUARIOS (USU_ID)
    ON DELETE SET NULL;