/* Lógico_1: */

CREATE TABLE PONTOS_COLETA (
    PCO_MODELO_DATA ENUM('M','S','A') NOT NULL,
    PCO_ID INTEGER AUTO_INCREMENT,
    PCO_NOME VARCHAR(50) NOT NULL,
    FK_PCO_ENDERECO_PCO_ENDERECO_PK INTEGER NOT NULL,
    PCO_CNPJ VARCHAR(18) NOT NULL,
    PCO_IMAGEM VARCHAR(255),
    PCO_AVALIACAO TEXT,
    PCO_DATA_TERMINO DATE NOT NULL,
    PCO_TELEFONE VARCHAR(20) NOT NULL,
    PCO_DATA_INICIO DATE NOT NULL,
    PRIMARY KEY (PCO_ID, PCO_DATA_INICIO),
    UNIQUE (PCO_ID, PCO_CNPJ, PCO_DATA_TERMINO, PCO_DATA_INICIO)
);

CREATE TABLE TIPO_RESIDUOS (
    TRE_DESCRICAO TEXT,
    TRE_NOME VARCHAR(50) NOT NULL,
    TRE_ID INTEGER AUTO_INCREMENT PRIMARY KEY UNIQUE
);

CREATE TABLE RESIDUOS_SOLIDOS (
    RES_ID INTEGER AUTO_INCREMENT PRIMARY KEY UNIQUE,
    RES_QUANTIDADE INTEGER(30) NOT NULL,
    RES_NOME_RESIDUO VARCHAR(50) NOT NULL,
    RES_TIPO_RESIDUO ENUM('INDUSTRIAIS','HOSPITALARES','SOLIDOS URBANOS', 'CONSTRUCAO CIVIL','NUCLEARES') NOT NULL,
    FK_TIPO_RESIDUOS_TRE_ID INTEGER NOT NULL
);

CREATE TABLE USUARIOS (
    USU_ID INTEGER AUTO_INCREMENT PRIMARY KEY UNIQUE
);

CREATE TABLE DESCARTE_RESIDUOS (
    DESRE_ID INTEGER AUTO_INCREMENT PRIMARY KEY,
    DESRE_NOME_PONTO_COLETA VARCHAR(50) NOT NULL,
    FK_PONTOS_COLETA_PCO_ID INTEGER,
    FK_USUARIOS_USU_ID INTEGER,
    FK_RESIDUOS_SOLIDOS_RES_ID INTEGER,
    UNIQUE (DESRE_ID, DESRE_NOME_PONTO_COLETA)
);

CREATE TABLE PROPRIETARIOS (
    PROP_ID INTEGER AUTO_INCREMENT UNIQUE,
    PROP_NOME VARCHAR(100) NOT NULL,
    PROP_CPF VARCHAR(15) NOT NULL,
    PROP_RG VARCHAR(15) NOT NULL,
    FK_PROP_ENDERECO_PROP_ENDERECO_PK INTEGER NOT NULL,
    PROP_TELEFONE VARCHAR(20) NOT NULL,
    PRIMARY KEY (PROP_ID, PROP_CPF)
);

CREATE TABLE PCO_ENDERECO (
    PCO_ENDERECO_PK INTEGER AUTO_INCREMENT PRIMARY KEY UNIQUE,
    PCO_NUMERO INT(4) NOT NULL,
    PCO_RUA VARCHAR(100) NOT NULL,
    PCO_BAIRRO VARCHAR(100) NOT NULL,
    PCO_CEP VARCHAR(9) NOT NULL,
    PCO_LOGRADOURO TEXT,
    PCO_LATITUDE DECIMAL(8,6) NOT NULL,
    PCO_LONGITUDE DECIMAL(8,6) NOT NULL
);

CREATE TABLE PROP_ENDERECO (
    PROP_ENDERECO_PK INTEGER AUTO_INCREMENT PRIMARY KEY,
    PROP_RUA VARCHAR(100) NOT NULL,
    PROP_NUMERO INT(4) NOT NULL,
    PROP_BAIRRO VARCHAR(100) NOT NULL,
    PROP_CEP VARCHAR(9) NOT NULL,
    PROP_LOGRADOURO TEXT NOT NULL,
    UNIQUE (PROP_ENDERECO_PK, PROP_CEP)
);

CREATE TABLE PONTOS_COLETA_RESIDUOS_ACEITOS (
    FK_PONTOS_COLETA_PCO_ID INTEGER,
    FK_TIPO_RESIDUOS_TRE_ID INTEGER,
    PCRA_ID INTEGER AUTO_INCREMENT PRIMARY KEY UNIQUE
);

CREATE TABLE POSSUI_PROPRIETARIOS (
    FK_PROPRIETARIOS_PROP_ID INTEGER,
    FK_PONTOS_COLETA_PCO_ID INTEGER,
    PSPROP_ID INTEGER AUTO_INCREMENT PRIMARY KEY UNIQUE
);
 
ALTER TABLE PONTOS_COLETA ADD CONSTRAINT FK_PONTOS_COLETA_2
    FOREIGN KEY (FK_PCO_ENDERECO_PCO_ENDERECO_PK)
    REFERENCES PCO_ENDERECO (PCO_ENDERECO_PK)
    ON DELETE SET NULL;
 
ALTER TABLE RESIDUOS_SOLIDOS ADD CONSTRAINT FK_RESIDUOS_SOLIDOS_2
    FOREIGN KEY (FK_TIPO_RESIDUOS_TRE_ID)
    REFERENCES TIPO_RESIDUOS (TRE_ID)
    ON DELETE CASCADE;
 
ALTER TABLE DESCARTE_RESIDUOS ADD CONSTRAINT FK_DESCARTE_RESIDUOS_2
    FOREIGN KEY (FK_PONTOS_COLETA_PCO_ID, ???)
    REFERENCES PONTOS_COLETA (PCO_ID, ???)
    ON DELETE CASCADE;
 
ALTER TABLE DESCARTE_RESIDUOS ADD CONSTRAINT FK_DESCARTE_RESIDUOS_3
    FOREIGN KEY (FK_USUARIOS_USU_ID)
    REFERENCES USUARIOS (USU_ID)
    ON DELETE CASCADE;
 
ALTER TABLE DESCARTE_RESIDUOS ADD CONSTRAINT FK_DESCARTE_RESIDUOS_4
    FOREIGN KEY (FK_RESIDUOS_SOLIDOS_RES_ID)
    REFERENCES RESIDUOS_SOLIDOS (RES_ID)
    ON DELETE CASCADE;
 
ALTER TABLE PROPRIETARIOS ADD CONSTRAINT FK_PROPRIETARIOS_2
    FOREIGN KEY (FK_PROP_ENDERECO_PROP_ENDERECO_PK)
    REFERENCES PROP_ENDERECO (PROP_ENDERECO_PK)
    ON DELETE SET NULL;
 
ALTER TABLE PONTOS_COLETA_RESIDUOS_ACEITOS ADD CONSTRAINT FK_PONTOS_COLETA_RESIDUOS_ACEITOS_2
    FOREIGN KEY (FK_PONTOS_COLETA_PCO_ID, ???)
    REFERENCES PONTOS_COLETA (PCO_ID, ???)
    ON DELETE SET NULL;
 
ALTER TABLE PONTOS_COLETA_RESIDUOS_ACEITOS ADD CONSTRAINT FK_PONTOS_COLETA_RESIDUOS_ACEITOS_3
    FOREIGN KEY (FK_TIPO_RESIDUOS_TRE_ID)
    REFERENCES TIPO_RESIDUOS (TRE_ID)
    ON DELETE SET NULL;
 
ALTER TABLE POSSUI_PROPRIETARIOS ADD CONSTRAINT FK_POSSUI_PROPRIETARIOS_2
    FOREIGN KEY (FK_PROPRIETARIOS_PROP_ID, ???)
    REFERENCES PROPRIETARIOS (PROP_ID, ???)
    ON DELETE RESTRICT;
 
ALTER TABLE POSSUI_PROPRIETARIOS ADD CONSTRAINT FK_POSSUI_PROPRIETARIOS_3
    FOREIGN KEY (FK_PONTOS_COLETA_PCO_ID, ???)
    REFERENCES PONTOS_COLETA (PCO_ID, ???)
    ON DELETE RESTRICT;