drop database MOD2;
CREATE DATABASE MOD2;

use MOD2;


CREATE TABLE CERVEJAS (
    CER_ID int PRIMARY KEY auto_increment,
    CER_CRIADOR_CERVEJA varchar(100),
    CER_NOME varchar(50),
    FK_ESTILOS_CERVEJAS_EST_ID INT ,
    FK_MICROCERVEJARIAS_MIC_ID int
);

CREATE TABLE HARMONIZACOES (
    HAR_ID int PRIMARY KEY auto_increment,
    HAR_NOME_RECEITA_COMIDA varchar(100),
    HAR_INGREDINTE varchar(300),
    HAR_MODPREPARO varchar(1000),
    HAR_FOTO VARCHAR(255)
);

CREATE TABLE INGREDIENTES (
    ING_ID int PRIMARY KEY auto_increment,
    ING_DESCRICAO varchar(300),
    ING_NOME varchar (300),
    ING_TIPO int
);

CREATE TABLE MICROCERVEJARIAS (
	MIC_ID int PRIMARY KEY auto_increment ,
    MIC_NOME varchar(50),
    MIC_TELEFONE varchar(13),
    MIC_ENDERECO varchar(100),
    MIC_DESCRICAO varchar(100),
    MIC_REDES_SOCIAIS varchar(255),
    MIC_CNPJ VARCHAR (18)
);

CREATE TABLE RECEITAS_CERVEJAS (
	REC_ID int PRIMARY KEY auto_increment ,
    REC_NOME varchar(50),
    REC_NOME_CRIADOR varchar(50),
    FK_ESTILOS_CERVEJAS_EST_ID INT ,
    FK_HARMONIZACOES_HAR_ID int,
    FK_MICROCERVEJARIAS_MIC_ID int,
    FK_CERVEJAS_CER_ID int,
    FK_USUARIOS_USU_ID INT
);

CREATE TABLE ESTILOS_CERVEJAS (

	EST_ID INT  PRIMARY KEY auto_increment,
    EST_NOME VARCHAR (50), 
    EST_ABVMIN FLOAT, 
    EST_ABVMAX FLOAT,
    EST_EBCMIN FLOAT,
    EST_EBCMAX FLOAT,
    EST_IBU_RECOMENDADO FLOAT
);

CREATE TABLE USUARIOS (
    USU_ID INT PRIMARY KEY auto_increment,
    USU_NOME VARCHAR (100),
    USU_CPF VARCHAR (14),
    FK_MICROCERVEJARIAS_MIC_ID int
);

CREATE TABLE MODOS_DE_PREPARO (
	
    MDP_ID INT PRIMARY KEY auto_increment,
    FK_INGREDIENTES_ING_ID int,
    FK_RECEITAS_CERVEJAS_REC_ID int,
    MDP_TEMPO INT,
    MDP_MODO VARCHAR (500),
    MDP_INGREDIENTE VARCHAR (300),
    MDP_QUANTIDADE INT
);

CREATE TABLE HARMONIZACOES_ESTILOS_CERVEJAS (
	 HARM_EST_ID INT  PRIMARY KEY auto_increment, 
    FK_ESTILOS_CERVEJAS_EST_ID INT ,
    FK_HARMONIZACOES_HAR_ID int
   
);

CREATE TABLE ESTOQUE_USUARIOS (
	EST_ID INT PRIMARY KEY auto_increment,
    FK_USUARIOS_USU_ID INT,
    FK_INGREDIENTES_ING_ID int,
    EST_INGREDIENTE VARCHAR (100),
    EST_PRECO_UNI DECIMAL(5, 2),
    EST_QUANTIDADE INT,
    EST_DATA_VALID DATE
);
 
ALTER TABLE CERVEJAS ADD CONSTRAINT FK_CERVEJAS_2
    FOREIGN KEY (FK_ESTILOS_CERVEJAS_EST_ID)
    REFERENCES ESTILOS_CERVEJAS (EST_ID)
    ON DELETE RESTRICT;
 
ALTER TABLE CERVEJAS ADD CONSTRAINT FK_CERVEJAS_3
    FOREIGN KEY (FK_MICROCERVEJARIAS_MIC_ID)
    REFERENCES MICROCERVEJARIAS (MIC_ID)
    ON DELETE RESTRICT;
 
ALTER TABLE RECEITAS_CERVEJAS ADD CONSTRAINT FK_RECEITAS_CERVEJAS_2
    FOREIGN KEY (FK_ESTILOS_CERVEJAS_EST_ID)
    REFERENCES ESTILOS_CERVEJAS (EST_ID)
    ON DELETE CASCADE;
 
ALTER TABLE RECEITAS_CERVEJAS ADD CONSTRAINT FK_RECEITAS_CERVEJAS_3
    FOREIGN KEY (FK_HARMONIZACOES_HAR_ID)
    REFERENCES HARMONIZACOES (HAR_ID)
    ON DELETE CASCADE;
 
ALTER TABLE RECEITAS_CERVEJAS ADD CONSTRAINT FK_RECEITAS_CERVEJAS_4
    FOREIGN KEY (FK_MICROCERVEJARIAS_MIC_ID)
    REFERENCES MICROCERVEJARIAS (MIC_ID)
    ON DELETE CASCADE;
 
ALTER TABLE RECEITAS_CERVEJAS ADD CONSTRAINT FK_RECEITAS_CERVEJAS_5
    FOREIGN KEY (FK_CERVEJAS_CER_ID)
    REFERENCES CERVEJAS (CER_ID)
    ON DELETE RESTRICT;
 
ALTER TABLE RECEITAS_CERVEJAS ADD CONSTRAINT FK_RECEITAS_CERVEJAS_6
    FOREIGN KEY (FK_USUARIOS_USU_ID)
    REFERENCES USUARIOS (USU_ID)
    ON DELETE CASCADE;
 
ALTER TABLE USUARIOS ADD CONSTRAINT FK_USUARIOS_2
    FOREIGN KEY (FK_MICROCERVEJARIAS_MIC_ID)
    REFERENCES MICROCERVEJARIAS (MIC_ID)
    ON DELETE RESTRICT;
 
ALTER TABLE MODOS_DE_PREPARO ADD CONSTRAINT FK_MODOS_DE_PREPARO_2
    FOREIGN KEY (FK_INGREDIENTES_ING_ID)
    REFERENCES INGREDIENTES (ING_ID)
    ON DELETE RESTRICT;
 
ALTER TABLE MODOS_DE_PREPARO ADD CONSTRAINT FK_MODOS_DE_PREPARO_3
    FOREIGN KEY (FK_RECEITAS_CERVEJAS_REC_ID)
    REFERENCES RECEITAS_CERVEJAS (REC_ID)
    ON DELETE SET NULL;
 
ALTER TABLE HARMONIZACOES_ESTILOS_CERVEJAS ADD CONSTRAINT FK_HARMONIZACOES_ESTILOS_CERVEJAS_1
    FOREIGN KEY (FK_ESTILOS_CERVEJAS_EST_ID)
    REFERENCES ESTILOS_CERVEJAS (EST_ID)
    ON DELETE RESTRICT;
 
ALTER TABLE HARMONIZACOES_ESTILOS_CERVEJAS ADD CONSTRAINT FK_HARMONIZACOES_ESTILOS_CERVEJAS_2
    FOREIGN KEY (FK_HARMONIZACOES_HAR_ID)
    REFERENCES HARMONIZACOES (HAR_ID)
    ON DELETE SET NULL;
 
ALTER TABLE ESTOQUE_USUARIOS ADD CONSTRAINT FK_ESTOQUE_USUARIOS_2
    FOREIGN KEY (FK_USUARIOS_USU_ID)
    REFERENCES USUARIOS (USU_ID)
    ON DELETE RESTRICT;
 
ALTER TABLE ESTOQUE_USUARIOS ADD CONSTRAINT FK_ESTOQUE_USUARIOS_3
    FOREIGN KEY (FK_INGREDIENTES_ING_ID)
    REFERENCES INGREDIENTES (ING_ID)
    ON DELETE SET NULL;